/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as operations from "../operations/index.js";
import { PipeshubError } from "./pipeshub-error.js";

/**
 * Server error. Possible causes:
 *
 * @remarks
 *
 * - Explicit `InternalServerError`
 *   or any other 500 `BaseError` thrown by the handler.
 * - Non-`BaseError` exception caught by the
 *   global error middleware.
 * - Response serializer fallback.
 */
export type GetSearchByIdInternalServerErrorData = {
  error: operations.GetSearchByIdInternalServerErrorError;
};

/**
 * Server error. Possible causes:
 *
 * @remarks
 *
 * - Explicit `InternalServerError`
 *   or any other 500 `BaseError` thrown by the handler.
 * - Non-`BaseError` exception caught by the
 *   global error middleware.
 * - Response serializer fallback.
 */
export class GetSearchByIdInternalServerError extends PipeshubError {
  error: operations.GetSearchByIdInternalServerErrorError;

  /** The original data that was passed to this error instance. */
  data$: GetSearchByIdInternalServerErrorData;

  constructor(
    err: GetSearchByIdInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetSearchByIdInternalServerError";
  }
}

/**
 * Reserved for parity with sibling routes; this endpoint
 *
 * @remarks
 * currently returns `200` with an empty array for an unknown
 * id rather than emitting `404`.
 */
export type GetSearchByIdNotFoundErrorData = {
  error: operations.GetSearchByIdNotFoundError;
};

/**
 * Reserved for parity with sibling routes; this endpoint
 *
 * @remarks
 * currently returns `200` with an empty array for an unknown
 * id rather than emitting `404`.
 */
export class GetSearchByIdNotFoundError extends PipeshubError {
  error: operations.GetSearchByIdNotFoundError;

  /** The original data that was passed to this error instance. */
  data$: GetSearchByIdNotFoundErrorData;

  constructor(
    err: GetSearchByIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetSearchByIdNotFoundError";
  }
}

/**
 * Bearer token lacks the `semantic:read` scope.
 *
 * @remarks
 */
export type GetSearchByIdForbiddenErrorData = {
  error: operations.GetSearchByIdErrorHTTPForbidden;
};

/**
 * Bearer token lacks the `semantic:read` scope.
 *
 * @remarks
 */
export class GetSearchByIdForbiddenError extends PipeshubError {
  error: operations.GetSearchByIdErrorHTTPForbidden;

  /** The original data that was passed to this error instance. */
  data$: GetSearchByIdForbiddenErrorData;

  constructor(
    err: GetSearchByIdForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetSearchByIdForbiddenError";
  }
}

/**
 * Missing or invalid bearer token.
 *
 * @remarks
 */
export type GetSearchByIdUnauthorizedErrorData = {
  error: operations.GetSearchByIdErrorHTTPUnauthorized;
};

/**
 * Missing or invalid bearer token.
 *
 * @remarks
 */
export class GetSearchByIdUnauthorizedError extends PipeshubError {
  error: operations.GetSearchByIdErrorHTTPUnauthorized;

  /** The original data that was passed to this error instance. */
  data$: GetSearchByIdUnauthorizedErrorData;

  constructor(
    err: GetSearchByIdUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetSearchByIdUnauthorizedError";
  }
}

/**
 * Invalid request — `searchId`
 *
 * @remarks
 * failed Zod validation (not a valid ObjectId).
 */
export type GetSearchByIdBadRequestErrorData = {
  error: operations.GetSearchByIdErrorValidationError;
};

/**
 * Invalid request — `searchId`
 *
 * @remarks
 * failed Zod validation (not a valid ObjectId).
 */
export class GetSearchByIdBadRequestError extends PipeshubError {
  error: operations.GetSearchByIdErrorValidationError;

  /** The original data that was passed to this error instance. */
  data$: GetSearchByIdBadRequestErrorData;

  constructor(
    err: GetSearchByIdBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "GetSearchByIdBadRequestError";
  }
}

/** @internal */
export const GetSearchByIdInternalServerError$inboundSchema: z.ZodMiniType<
  GetSearchByIdInternalServerError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() =>
      operations.GetSearchByIdInternalServerErrorError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSearchByIdInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetSearchByIdNotFoundError$inboundSchema: z.ZodMiniType<
  GetSearchByIdNotFoundError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() => operations.GetSearchByIdNotFoundError$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSearchByIdNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetSearchByIdForbiddenError$inboundSchema: z.ZodMiniType<
  GetSearchByIdForbiddenError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() =>
      operations.GetSearchByIdErrorHTTPForbidden$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSearchByIdForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetSearchByIdUnauthorizedError$inboundSchema: z.ZodMiniType<
  GetSearchByIdUnauthorizedError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() =>
      operations.GetSearchByIdErrorHTTPUnauthorized$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSearchByIdUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const GetSearchByIdBadRequestError$inboundSchema: z.ZodMiniType<
  GetSearchByIdBadRequestError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() =>
      operations.GetSearchByIdErrorValidationError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new GetSearchByIdBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
