/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";
import { PipeshubError } from "./pipeshub-error.js";

/**
 * JSON body when OAuth client management routes exceed the per-minute rate limit (same limiter as other `/oauth-clients/*` routes).
 */
export type OAuthClientManagementRateLimitErrorData = {
  error: models.OAuthClientManagementRateLimitErrorError;
};

/**
 * JSON body when OAuth client management routes exceed the per-minute rate limit (same limiter as other `/oauth-clients/*` routes).
 */
export class OAuthClientManagementRateLimitError extends PipeshubError {
  error: models.OAuthClientManagementRateLimitErrorError;

  /** The original data that was passed to this error instance. */
  data$: OAuthClientManagementRateLimitErrorData;

  constructor(
    err: OAuthClientManagementRateLimitErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "OAuthClientManagementRateLimitError";
  }
}

/** @internal */
export const OAuthClientManagementRateLimitError$inboundSchema: z.ZodMiniType<
  OAuthClientManagementRateLimitError,
  unknown
> = z.pipe(
  z.object({
    error: z.lazy(() =>
      models.OAuthClientManagementRateLimitErrorError$inboundSchema
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new OAuthClientManagementRateLimitError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
