/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsAddAgentConversationMessage } from "../funcs/agents-add-agent-conversation-message.js";
import { agentsArchiveAgentConversation } from "../funcs/agents-archive-agent-conversation.js";
import { agentsCancelAgentConversationStream } from "../funcs/agents-cancel-agent-conversation-stream.js";
import { agentsCreateAgentConversation } from "../funcs/agents-create-agent-conversation.js";
import { agentsCreateAgent } from "../funcs/agents-create-agent.js";
import { agentsDeleteAgentConversationById } from "../funcs/agents-delete-agent-conversation-by-id.js";
import { agentsDeleteAgentConversationChatAttachment } from "../funcs/agents-delete-agent-conversation-chat-attachment.js";
import { agentsDeleteAgent } from "../funcs/agents-delete-agent.js";
import { agentsGetAgentConversationById } from "../funcs/agents-get-agent-conversation-by-id.js";
import { agentsGetAgent } from "../funcs/agents-get-agent.js";
import { agentsListAgentArchivedConversationsGrouped } from "../funcs/agents-list-agent-archived-conversations-grouped.js";
import { agentsListAgentConversationArchives } from "../funcs/agents-list-agent-conversation-archives.js";
import { agentsListAgentConversations } from "../funcs/agents-list-agent-conversations.js";
import { agentsListAgents } from "../funcs/agents-list-agents.js";
import { agentsRegenerateAgentConversationMessage } from "../funcs/agents-regenerate-agent-conversation-message.js";
import { agentsStreamAgentConversationMessage } from "../funcs/agents-stream-agent-conversation-message.js";
import { agentsStreamAgentConversation } from "../funcs/agents-stream-agent-conversation.js";
import { agentsUnarchiveAgentConversation } from "../funcs/agents-unarchive-agent-conversation.js";
import { agentsUpdateAgentConversationMessageFeedback } from "../funcs/agents-update-agent-conversation-message-feedback.js";
import { agentsUpdateAgentConversationTitle } from "../funcs/agents-update-agent-conversation-title.js";
import { agentsUpdateAgent } from "../funcs/agents-update-agent.js";
import { agentsUploadAgentConversationChatAttachments } from "../funcs/agents-upload-agent-conversation-chat-attachments.js";
import { projectsSetAgentConversationProjectVisibility } from "../funcs/projects-set-agent-conversation-project-visibility.js";
import { projectsSetAgentConversationProject } from "../funcs/projects-set-agent-conversation-project.js";
import { EventStream } from "../lib/event-streams.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Agents extends ClientSDK {
  /**
   * List agents
   *
   * @remarks
   * Retrieve a paginated list of agents available to the authenticated user.
   *
   * **Overview**
   *
   * Returns agents accessible through direct, team, or org-level permissions.
   * Search is performed across agent name, description, and tags. Sorting and
   * pagination are applied by the AI backend and the resulting envelope is
   * forwarded unchanged by the Node gateway.
   *
   * **Gateway contract**
   *
   * The Node route supports only these query params: `page`, `limit`, `search`,
   * `sort_by`, and `sort_order`.
   *
   * The Python backend also understands `isDeleted`, but this gateway route
   * does not forward it, so it is not part of the public API contract here.
   */
  async listAgents(
    request?: operations.ListAgentsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.AgentListResponse> {
    return unwrapAsync(agentsListAgents(
      this,
      request,
      options,
    ));
  }

  /**
   * Create agent
   *
   * @remarks
   * Create a new custom AI agent.
   *
   * **Overview:**
   * Agents are specialized AI assistants configured for specific tasks.
   * They can have custom system prompts, access to specific tools, and
   * be limited to certain knowledge bases.
   *
   * **Agent Configuration:**
   * - **System prompt:** Instructions that define agent behavior
   * - **Tools:** Capabilities like web search, code execution, etc.
   * - **Knowledge bases:** Data sources the agent can access
   * - **Model config:** AI model settings (temperature, max tokens)
   *
   * **Use Cases:**
   * - Customer support bot with product knowledge
   * - Code review assistant with repository access
   * - HR assistant with policy documents
   */
  async createAgent(
    request: models.AgentCreateRequest,
    options?: RequestOptions,
  ): Promise<models.AgentCreateResponse> {
    return unwrapAsync(agentsCreateAgent(
      this,
      request,
      options,
    ));
  }

  /**
   * Get agent
   *
   * @remarks
   * Retrieve agent details by its unique key.
   *
   * **Gateway not-found behavior:**
   * Unknown `agentKey`, lookup after soft-delete, and other AI-backend failures
   * that return 404 from the Python query service are surfaced by the Node
   * gateway as **HTTP 404** with an `ErrorResponse` body.
   */
  async getAgent(
    request: operations.GetAgentRequest,
    options?: RequestOptions,
  ): Promise<models.GetAgentResponse> {
    return unwrapAsync(agentsGetAgent(
      this,
      request,
      options,
    ));
  }

  /**
   * Update agent
   *
   * @remarks
   * Apply a partial update to an existing agent configuration.
   *
   * **Gateway contract**
   *
   * The Node gateway validates the request body via Zod middleware before
   * forwarding to the Python agent service. The `agentKey` path param and
   * the request body are both validated. Query parameters are ignored by
   * the controller.
   *
   * **Update semantics**
   *
   * Only fields present in the request body are updated. `models` may be
   * omitted (the agent's existing models are kept), set to an empty array
   * (clears the agent's models so it falls back to the organization's
   * default LLM at chat time), or set to a non-empty array. When a
   * non-empty array is provided, the gateway Zod middleware requires at
   * least one object entry with `isReasoning: true`.
   *
   * **Permissions**
   *
   * The authenticated user must have `can_edit` on the agent (typically the
   * owner). Service-account and `shareWithOrg` transitions follow additional
   * Python business rules.
   *
   * **Success response**
   *
   * Returns a lightweight success envelope only. Use
   * `GET /agents/{agentKey}` to read the persisted agent after an update.
   */
  async updateAgent(
    request: operations.UpdateAgentRequest,
    options?: RequestOptions,
  ): Promise<models.AgentUpdateResponse> {
    return unwrapAsync(agentsUpdateAgent(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete agent
   *
   * @remarks
   * Soft-delete an agent (tombstone) in the graph database.
   *
   * **Overview:**
   * The Python query service marks the agent instance deleted inside a transaction.
   * List and search endpoints exclude tombstoned agents. Toolsets, tools, and
   * knowledge linked to the agent are not removed by this call.
   *
   * **Permissions:**
   * Only the agent owner may delete (`can_delete` on the permission check).
   *
   * **Warning:**
   * All conversations with this agent will become inaccessible.
   *
   * **Gateway not-found behavior:**
   * Unknown `agentKey`, deleting an already-deleted agent, and `GET /agents/{agentKey}`
   * after delete return **HTTP 404** with an `ErrorResponse` body.
   */
  async deleteAgent(
    request: operations.DeleteAgentRequest,
    options?: RequestOptions,
  ): Promise<models.AgentDeleteResponse> {
    return unwrapAsync(agentsDeleteAgent(
      this,
      request,
      options,
    ));
  }

  /**
   * List archived agent conversations grouped by agent
   *
   * @remarks
   * Returns archived agent conversations for the current user, grouped by
   * `agentKey`, with pagination over agent groups. Excludes conversations
   * whose agent was soft-deleted upstream.
   */
  async listAgentArchivedConversationsGrouped(
    request?:
      | operations.ListAgentArchivedConversationsGroupedRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<models.AgentArchivedGroupsResponse> {
    return unwrapAsync(agentsListAgentArchivedConversationsGrouped(
      this,
      request,
      options,
    ));
  }

  /**
   * List archived conversations for an agent
   *
   * @remarks
   * Paginated list of archived conversations for the given agent key.
   */
  async listAgentConversationArchives(
    request: operations.ListAgentConversationArchivesRequest,
    options?: RequestOptions,
  ): Promise<models.AgentArchivedConversationListResponse> {
    return unwrapAsync(agentsListAgentConversationArchives(
      this,
      request,
      options,
    ));
  }

  /**
   * Upload agent chat attachments
   *
   * @remarks
   * Multipart upload of PDF, JPEG, or PNG files for agent chat. Same limits as assistant
   * chat (`POST /conversations/attachments/upload`): up to 10 files, 5 MiB each. Proxies to
   * the AI backend. Optional `conversationId` associates uploads with an existing agent thread.
   */
  async uploadAgentConversationChatAttachments(
    request: operations.UploadAgentConversationChatAttachmentsRequest,
    options?: RequestOptions,
  ): Promise<models.ChatAttachmentUploadResponse> {
    return unwrapAsync(agentsUploadAgentConversationChatAttachments(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an agent chat attachment
   *
   * @remarks
   * Deletes a previously uploaded attachment by proxying `DELETE` to the query service
   * (`/api/v1/chat/attachments/{recordId}`). The Node handler always ends the response **without
   * a JSON body** on success (empty body); the **status code** is the upstream status, or **204**
   * if none is returned.
   *
   * On validation failure in the gateway (invalid / blank path params), the response is **400**
   * with a small JSON error object. Same fire-and-forget semantics as
   * `DELETE /conversations/attachments/{recordId}` on the client.
   */
  async deleteAgentConversationChatAttachment(
    request: operations.DeleteAgentConversationChatAttachmentRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(agentsDeleteAgentConversationChatAttachment(
      this,
      request,
      options,
    ));
  }

  /**
   * Create agent conversation with streaming response
   *
   * @remarks
   * Start a new conversation with the specified agent and stream the AI
   * response as Server-Sent Events (SSE). The first user message is saved
   * and forwarded to the upstream agent backend; subsequent tokens, tool
   * calls, and lifecycle events are emitted on the open SSE connection.
   *
   * AG-UI is the sole wire protocol. The request must include
   * `chatMode: quick`; see `AgentStreamSSEEvent` for the event vocabulary.
   */
  async streamAgentConversation(
    request: operations.StreamAgentConversationRequest,
    options?: RequestOptions,
  ): Promise<EventStream<models.AgentStreamSSEEvent>> {
    return unwrapAsync(agentsStreamAgentConversation(
      this,
      request,
      options,
    ));
  }

  /**
   * Add message to agent conversation with streaming response
   *
   * @remarks
   * Append a user message to an existing agent conversation and stream the
   * assistant reply over SSE.
   *
   * AG-UI is the sole wire protocol. The request must include
   * `chatMode: quick`; see `AgentMessageStreamSSEEvent` for the event
   * vocabulary.
   */
  async streamAgentConversationMessage(
    request: operations.StreamAgentConversationMessageRequest,
    options?: RequestOptions,
  ): Promise<EventStream<models.AgentMessageStreamSSEEvent>> {
    return unwrapAsync(agentsStreamAgentConversationMessage(
      this,
      request,
      options,
    ));
  }

  /**
   * Regenerate agent conversation message
   *
   * @remarks
   * Regenerate the AI response for a specific message in an agent
   * conversation and stream the new answer over Server-Sent Events.
   *
   * **Constraints:**
   *
   * - Only the last message in the conversation can be regenerated.
   * - The target message must be of type `bot_response`.
   *
   * **Request body:**
   *
   * `chatMode: quick` is required. Other fields are optional and reuse
   * the original model/context when omitted. The body supports:
   * - `filters`
   * - `chatMode`
   * - `modelKey`
   * - `modelName`
   * - `modelFriendlyName`
   * - `timezone`
   * - `currentTime`
   * - `tools`
   * - `protocol`
   * - `agentCapabilities`
   *
   * **Streaming behavior:**
   *
   * The response is delivered as an AG-UI `text/event-stream`. Stable
   * outcomes are `RUN_FINISHED` and `RUN_ERROR`; see
   * `AgentRegenerateSSEEvent`.
   *
   * Additional agent/tool lifecycle events may be forwarded by the
   * backend and should be treated as informational updates.
   *
   * Validation failures on params/body are returned as normal HTTP `400`
   * responses before the stream starts. Valid-shape requests that fail
   * conversation lookup or regenerate rules are reported as
   * `RUN_ERROR` events after stream initialization.
   */
  async regenerateAgentConversationMessage(
    request: operations.RegenerateAgentConversationMessageRequest,
    options?: RequestOptions,
  ): Promise<EventStream<models.AgentRegenerateSSEEvent>> {
    return unwrapAsync(agentsRegenerateAgentConversationMessage(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel an in-flight agent chat stream
   *
   * @remarks
   * Cooperatively stop a `POST /agents/{agentKey}/conversations/stream`
   * or `.../messages/stream` run that is still generating, using the
   * `runId` sent when that stream started.
   *
   * Same synchronous JSON ack contract as the assistant
   * `POST /conversations/{conversationId}/cancel` — both forward to the
   * same backend cancellation endpoint, since the run registry is keyed
   * by `runId` alone. `{ cancelled: false }` covers a `runId` that
   * already finished or was never registered.
   *
   * `runId` must belong to a run started on THIS `conversationId` — a
   * `runId` that exists but was registered under a different
   * conversation (even one owned by the same caller) is rejected with
   * `403`, same as a `runId` owned by a different user/org.
   */
  async cancelAgentConversationStream(
    request: operations.CancelAgentConversationStreamRequest,
    options?: RequestOptions,
  ): Promise<operations.CancelAgentConversationStreamResponse> {
    return unwrapAsync(agentsCancelAgentConversationStream(
      this,
      request,
      options,
    ));
  }

  /**
   * Submit feedback for an agent message
   *
   * @remarks
   * Append structured feedback to a bot-response message in an agent
   * conversation. Uses the same request body shape as
   * `updateMessageFeedback` (helpfulness, categories, comments). Feedback
   * can only be submitted on `bot_response` messages.
   */
  async updateAgentConversationMessageFeedback(
    request: operations.UpdateAgentConversationMessageFeedbackRequest,
    options?: RequestOptions,
  ): Promise<models.MessageFeedbackUpdateResponse> {
    return unwrapAsync(agentsUpdateAgentConversationMessageFeedback(
      this,
      request,
      options,
    ));
  }

  /**
   * Add message to agent conversation (non-streaming)
   *
   * @remarks
   * Ask a follow-up in an existing agent conversation and wait for the
   * complete answer. The JSON counterpart of
   * `POST /agents/{agentKey}/conversations/{conversationId}/messages/stream`.
   *
   * **How a turn runs**
   *
   * 1. The user's message is saved (in its own short transaction on a
   *    replica set).
   * 2. The AI backend runs the same agent-loop pipeline as the `/stream`
   *    route and returns only its final result. No transaction is held
   *    during this call, and the call is never retried.
   * 3. The answer, citations and status are saved exactly as the
   *    streaming route saves them, and the updated conversation is
   *    returned.
   *
   * Every failure after step 1 is persisted: the conversation ends with
   * status `Failed`, a `failReason`, and an `error` message, and the
   * response carries `X-Conversation-Id` so the caller can fetch it.
   * A 4xx from the AI backend (for example no model configured) keeps
   * its status and user-facing message; other failures return 500 with
   * a generic message.
   *
   * The response arrives only when the whole answer is ready, which can
   * take minutes for agent runs. Allow a generous client and proxy
   * timeout, or use the `/stream` variant for interactive clients.
   */
  async addAgentConversationMessage(
    request: operations.AddAgentConversationMessageRequest,
    options?: RequestOptions,
  ): Promise<operations.AddAgentConversationMessageResponse> {
    return unwrapAsync(agentsAddAgentConversationMessage(
      this,
      request,
      options,
    ));
  }

  /**
   * Archive an agent conversation
   *
   * @remarks
   * Marks the conversation as archived for the authenticated owner.
   */
  async archiveAgentConversation(
    request: operations.ArchiveAgentConversationRequest,
    options?: RequestOptions,
  ): Promise<models.AgentConversationArchiveResponse> {
    return unwrapAsync(agentsArchiveAgentConversation(
      this,
      request,
      options,
    ));
  }

  /**
   * Unarchive an agent conversation
   *
   * @remarks
   * Restores an archived agent conversation to the active list.
   */
  async unarchiveAgentConversation(
    request: operations.UnarchiveAgentConversationRequest,
    options?: RequestOptions,
  ): Promise<models.AgentConversationUnarchiveResponse> {
    return unwrapAsync(agentsUnarchiveAgentConversation(
      this,
      request,
      options,
    ));
  }

  /**
   * Update agent conversation title
   *
   * @remarks
   * Updates the display title for an agent conversation owned by the caller.
   *
   * The controller looks up the conversation by `_id`, `orgId`, `userId`,
   * `agentKey`, and `isDeleted: false`.
   *
   * The request body uses the shared title validator (`1..200` chars), and
   * the controller trims the incoming title before saving it. A whitespace-only
   * title can therefore still return HTTP 400 even if the raw string is
   * non-empty.
   */
  async updateAgentConversationTitle(
    request: operations.UpdateAgentConversationTitleRequest,
    options?: RequestOptions,
  ): Promise<models.AgentConversationTitleUpdateResponse> {
    return unwrapAsync(agentsUpdateAgentConversationTitle(
      this,
      request,
      options,
    ));
  }

  /**
   * Link or unlink an agent conversation to a project
   *
   * @remarks
   * Agent-conversation equivalent of
   * `PUT /conversations/{conversationId}/project`. Set
   * (`projectId: <id>`) or clear (`projectId: null`) the project this
   * agent conversation belongs to. Initiator-only; linking requires at
   * least viewer access to the target project.
   */
  async setAgentConversationProject(
    request: operations.SetAgentConversationProjectRequest,
    options?: RequestOptions,
  ): Promise<operations.SetAgentConversationProjectResponse> {
    return unwrapAsync(projectsSetAgentConversationProject(
      this,
      request,
      options,
    ));
  }

  /**
   * Override an agent conversation's project visibility
   *
   * @remarks
   * Agent-conversation equivalent of
   * `PATCH /conversations/{conversationId}/project-visibility`.
   * Initiator-only; requires the conversation to already be linked to a
   * project.
   */
  async setAgentConversationProjectVisibility(
    request: operations.SetAgentConversationProjectVisibilityRequest,
    options?: RequestOptions,
  ): Promise<operations.SetAgentConversationProjectVisibilityResponse> {
    return unwrapAsync(projectsSetAgentConversationProjectVisibility(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an agent conversation
   *
   * @remarks
   * Soft-deletes an agent conversation owned by the authenticated user.
   *
   * The controller scopes the lookup by `_id`, `orgId`, `userId`, and
   * `agentKey`. If no matching writable conversation is found, the route is
   * intentionally a no-op and still returns HTTP 200 with `conversation: null`.
   *
   * This makes the operation idempotent:
   *
   * - deleting a nonexistent conversation returns success with `null`
   * - deleting through a different `agentKey` returns success with `null`
   * - deleting an already deleted conversation returns success with `null`
   */
  async deleteAgentConversationById(
    request: operations.DeleteAgentConversationByIdRequest,
    options?: RequestOptions,
  ): Promise<models.AgentConversationDeleteResponse> {
    return unwrapAsync(agentsDeleteAgentConversationById(
      this,
      request,
      options,
    ));
  }

  /**
   * Get agent conversation by ID
   *
   * @remarks
   * Returns the conversation with paginated/sorted messages and filter metadata.
   *
   * **Message Pagination:**
   *
   * Messages are paginated newest-first: `page=1` returns the most recent
   * batch. Increment `page` to load older batches (used by the infinite-scroll
   * "load older messages" feature).
   *
   * - `page`: Page number (default: 1)
   * - `limit`: Messages per page (default: 20, max: 100)
   */
  async getAgentConversationById(
    request: operations.GetAgentConversationByIdRequest,
    options?: RequestOptions,
  ): Promise<models.AgentConversationDetailResponse> {
    return unwrapAsync(agentsGetAgentConversationById(
      this,
      request,
      options,
    ));
  }

  /**
   * List agent conversations
   *
   * @remarks
   * Paginated list of conversations for the agent (owned and shared-with-me),
   * excluding archived threads.
   */
  async listAgentConversations(
    request: operations.ListAgentConversationsRequest,
    options?: RequestOptions,
  ): Promise<models.AgentConversationListResponse> {
    return unwrapAsync(agentsListAgentConversations(
      this,
      request,
      options,
    ));
  }

  /**
   * Create agent conversation (non-streaming)
   *
   * @remarks
   * Start a conversation with an agent and wait for the complete answer.
   * The JSON counterpart of `POST /agents/{agentKey}/conversations/stream`.
   *
   * **How a turn runs**
   *
   * 1. The user's message is saved (in its own short transaction on a
   *    replica set).
   * 2. The AI backend runs the same agent-loop pipeline as the `/stream`
   *    route and returns only its final result. No transaction is held
   *    during this call, and the call is never retried.
   * 3. The answer, citations and status are saved exactly as the
   *    streaming route saves them, and the updated conversation is
   *    returned.
   *
   * Every failure after step 1 is persisted: the conversation ends with
   * status `Failed`, a `failReason`, and an `error` message, and the
   * response carries `X-Conversation-Id` so the caller can fetch it.
   * A 4xx from the AI backend (for example no model configured) keeps
   * its status and user-facing message; other failures return 500 with
   * a generic message.
   *
   * The response arrives only when the whole answer is ready, which can
   * take minutes for agent runs. Allow a generous client and proxy
   * timeout, or use the `/stream` variant for interactive clients.
   */
  async createAgentConversation(
    request: operations.CreateAgentConversationRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateAgentConversationResponse> {
    return unwrapAsync(agentsCreateAgentConversation(
      this,
      request,
      options,
    ));
  }
}
