/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationConfigurationGetAzureAdAuthConfig } from "../funcs/authentication-configuration-get-azure-ad-auth-config.js";
import { authenticationConfigurationGetGenericOAuthConfig } from "../funcs/authentication-configuration-get-generic-o-auth-config.js";
import { authenticationConfigurationGetGoogleAuthConfig } from "../funcs/authentication-configuration-get-google-auth-config.js";
import { authenticationConfigurationGetMicrosoftAuthConfig } from "../funcs/authentication-configuration-get-microsoft-auth-config.js";
import { authenticationConfigurationGetSsoAuthConfig } from "../funcs/authentication-configuration-get-sso-auth-config.js";
import { authenticationConfigurationSetAzureAdAuthConfig } from "../funcs/authentication-configuration-set-azure-ad-auth-config.js";
import { authenticationConfigurationSetGoogleAuthConfig } from "../funcs/authentication-configuration-set-google-auth-config.js";
import { authenticationConfigurationSetMicrosoftAuthConfig } from "../funcs/authentication-configuration-set-microsoft-auth-config.js";
import { authenticationConfigurationSetOAuthConfig } from "../funcs/authentication-configuration-set-o-auth-config.js";
import { authenticationConfigurationSetSsoAuthConfig } from "../funcs/authentication-configuration-set-sso-auth-config.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AuthenticationConfiguration extends ClientSDK {
  /**
   * Configure Azure AD authentication
   *
   * @remarks
   * Set up Azure Active Directory as an authentication provider for user login.
   */
  async setAzureAdAuthConfig(
    security: operations.SetAzureAdAuthConfigSecurity,
    request: models.AzureAdAuthConfig,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(authenticationConfigurationSetAzureAdAuthConfig(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get Azure AD configuration
   *
   * @remarks
   * Retrieve Azure AD authentication configuration.
   */
  async getAzureAdAuthConfig(
    security: operations.GetAzureAdAuthConfigSecurity,
    options?: RequestOptions,
  ): Promise<models.AzureAdAuthConfig> {
    return unwrapAsync(authenticationConfigurationGetAzureAdAuthConfig(
      this,
      security,
      options,
    ));
  }

  /**
   * Configure Microsoft authentication
   *
   * @remarks
   * Set up Microsoft account as an authentication provider.
   */
  async setMicrosoftAuthConfig(
    security: operations.SetMicrosoftAuthConfigSecurity,
    request: models.MicrosoftAuthConfig,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(authenticationConfigurationSetMicrosoftAuthConfig(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get Microsoft authentication configuration
   *
   * @remarks
   * Get Microsoft authentication configuration.
   */
  async getMicrosoftAuthConfig(
    security: operations.GetMicrosoftAuthConfigSecurity,
    options?: RequestOptions,
  ): Promise<models.MicrosoftAuthConfig> {
    return unwrapAsync(authenticationConfigurationGetMicrosoftAuthConfig(
      this,
      security,
      options,
    ));
  }

  /**
   * Configure Google authentication
   *
   * @remarks
   * Set up Google OAuth as an authentication provider.
   */
  async setGoogleAuthConfig(
    security: operations.SetGoogleAuthConfigSecurity,
    request: models.GoogleAuthConfig,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(authenticationConfigurationSetGoogleAuthConfig(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get Google authentication configuration
   *
   * @remarks
   * Get Google authentication configuration.
   */
  async getGoogleAuthConfig(
    security: operations.GetGoogleAuthConfigSecurity,
    options?: RequestOptions,
  ): Promise<models.GoogleAuthConfig> {
    return unwrapAsync(authenticationConfigurationGetGoogleAuthConfig(
      this,
      security,
      options,
    ));
  }

  /**
   * Configure SAML SSO authentication
   *
   * @remarks
   * Set up SAML 2.0 Single Sign-On with your identity provider (Okta, OneLogin, etc.).
   */
  async setSsoAuthConfig(
    security: operations.SetSsoAuthConfigSecurity,
    request: models.SSOAuthConfig,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(authenticationConfigurationSetSsoAuthConfig(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get SAML SSO configuration
   *
   * @remarks
   * Get SAML SSO configuration.
   */
  async getSsoAuthConfig(
    security: operations.GetSsoAuthConfigSecurity,
    options?: RequestOptions,
  ): Promise<models.SSOAuthConfig> {
    return unwrapAsync(authenticationConfigurationGetSsoAuthConfig(
      this,
      security,
      options,
    ));
  }

  /**
   * Configure generic OAuth provider
   *
   * @remarks
   * Set up a custom OAuth 2.0 authentication provider.
   */
  async setOAuthConfig(
    security: operations.SetOAuthConfigSecurity,
    request: models.GenericOAuthConfig,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(authenticationConfigurationSetOAuthConfig(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get generic OAuth configuration
   *
   * @remarks
   * Get generic OAuth configuration.
   */
  async getGenericOAuthConfig(
    security: operations.GetGenericOAuthConfigSecurity,
    options?: RequestOptions,
  ): Promise<models.GenericOAuthConfig> {
    return unwrapAsync(authenticationConfigurationGetGenericOAuthConfig(
      this,
      security,
      options,
    ));
  }
}
