/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectorOAuthGetOAuthAuthorizationUrl } from "../funcs/connector-o-auth-get-o-auth-authorization-url.js";
import { connectorOAuthGetTokenFromCode } from "../funcs/connector-o-auth-get-token-from-code.js";
import { connectorOAuthHandleOAuthCallback } from "../funcs/connector-o-auth-handle-o-auth-callback.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ConnectorOAuth extends ClientSDK {
  /**
   * Get OAuth authorization URL
   *
   * @remarks
   * Generate an OAuth authorization URL to start the OAuth flow.<br><br>
   * <b>Flow:</b><br>
   * <ol>
   * <li>Call this endpoint to get the authorization URL</li>
   * <li>Redirect user's browser to the URL</li>
   * <li>User authenticates with the provider</li>
   * <li>Provider redirects to callback with authorization code</li>
   * <li>Callback exchanges code for tokens automatically</li>
   * </ol>
   * <b>State Parameter:</b><br>
   * The response includes a <code>state</code> value that encodes the
   * connector ID. This is validated in the callback.
   */
  async getOAuthAuthorizationUrl(
    request: operations.GetOAuthAuthorizationUrlRequest,
    options?: RequestOptions,
  ): Promise<operations.GetOAuthAuthorizationUrlResponse> {
    return unwrapAsync(connectorOAuthGetOAuthAuthorizationUrl(
      this,
      request,
      options,
    ));
  }

  /**
   * OAuth callback handler
   *
   * @remarks
   * Handle the OAuth callback from the identity provider.<br><br>
   * <b>Note:</b><br>
   * This endpoint is called by the OAuth provider after user authentication.
   * The state parameter contains the encoded connector ID.<br><br>
   * <b>Success:</b><br>
   * On success, tokens are stored and the connector becomes authenticated.
   * User is redirected to the frontend success page.<br><br>
   * <b>Error:</b><br>
   * If the provider returns an error (e.g., user denied access),
   * user is redirected with error information.
   */
  async handleOAuthCallback(
    request?: operations.HandleOAuthCallbackRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.HandleOAuthCallbackResponse | undefined> {
    return unwrapAsync(connectorOAuthHandleOAuthCallback(
      this,
      request,
      options,
    ));
  }

  /**
   * Exchange Google authorization code for tokens
   *
   * @remarks
   * <b>⚠️ Deprecated:</b> Legacy Google Workspace token exchange endpoint. Use the generic
   * OAuth flow via <code>/connectors/{connectorId}/oauth/authorize</code> instead.<br><br>
   * <b>Overview:</b><br>
   * Exchanges a Google OAuth authorization code for access and refresh tokens,
   * stores the credentials, and enables the Google Workspace connector.<br><br>
   * <b>What Happens:</b><br>
   * <ol>
   * <li>Retrieves Google Workspace OAuth config (client ID/secret)</li>
   * <li>Exchanges the authorization code for tokens via Google's token endpoint</li>
   * <li>Verifies the ID token</li>
   * <li>Stores access and refresh tokens in configuration manager</li>
   * <li>Creates or enables the Google Workspace connector</li>
   * <li>Publishes an AppEnabledEvent for the sync service</li>
   * </ol>
   * <b>Admin Only:</b><br>
   * Requires organization admin privileges.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async getTokenFromCode(
    request: operations.GetTokenFromCodeRequest,
    options?: RequestOptions,
  ): Promise<operations.GetTokenFromCodeResponse> {
    return unwrapAsync(connectorOAuthGetTokenFromCode(
      this,
      request,
      options,
    ));
  }
}
