/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { conversationsAddMessageStream } from "../funcs/conversations-add-message-stream.js";
import { conversationsAddMessage } from "../funcs/conversations-add-message.js";
import { conversationsArchiveConversation } from "../funcs/conversations-archive-conversation.js";
import { conversationsCancelConversationStream } from "../funcs/conversations-cancel-conversation-stream.js";
import { conversationsCreateConversation } from "../funcs/conversations-create-conversation.js";
import { conversationsDeleteConversationById } from "../funcs/conversations-delete-conversation-by-id.js";
import { conversationsGetAllConversations } from "../funcs/conversations-get-all-conversations.js";
import { conversationsGetArchivedConversations } from "../funcs/conversations-get-archived-conversations.js";
import { conversationsGetConversationById } from "../funcs/conversations-get-conversation-by-id.js";
import { conversationsGetProjectConversations } from "../funcs/conversations-get-project-conversations.js";
import { conversationsRegenerateAnswer } from "../funcs/conversations-regenerate-answer.js";
import { conversationsSearchArchivedConversations } from "../funcs/conversations-search-archived-conversations.js";
import { conversationsSetConversationProjectVisibility } from "../funcs/conversations-set-conversation-project-visibility.js";
import { conversationsSetConversationProject } from "../funcs/conversations-set-conversation-project.js";
import { conversationsStreamChat } from "../funcs/conversations-stream-chat.js";
import { conversationsUnarchiveConversation } from "../funcs/conversations-unarchive-conversation.js";
import { conversationsUpdateConversationTitle } from "../funcs/conversations-update-conversation-title.js";
import { conversationsUpdateMessageFeedback } from "../funcs/conversations-update-message-feedback.js";
import { EventStream } from "../lib/event-streams.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Conversations extends ClientSDK {
  /**
   * Create conversation (non-streaming)
   *
   * @remarks
   * Start a new assistant conversation and wait for the complete answer.
   * The JSON counterpart of `POST /conversations/stream`, for API, SDK
   * and automation callers that do not consume SSE.
   *
   * **How a turn runs**
   *
   * 1. The user's message is saved (in its own short transaction on a
   *    replica set).
   * 2. The AI backend runs the same agent-loop pipeline as the `/stream`
   *    route and returns only its final result. No transaction is held
   *    during this call, and the call is never retried.
   * 3. The answer, citations and status are saved exactly as the
   *    streaming route saves them, and the updated conversation is
   *    returned.
   *
   * Every failure after step 1 is persisted: the conversation ends with
   * status `Failed`, a `failReason`, and an `error` message, and the
   * response carries `X-Conversation-Id` so the caller can fetch it.
   * A 4xx from the AI backend (for example no model configured) keeps
   * its status and user-facing message; other failures return 500 with
   * a generic message.
   *
   * The response arrives only when the whole answer is ready, which can
   * take minutes for agent runs. Allow a generous client and proxy
   * timeout, or use the `/stream` variant for interactive clients.
   *
   * **Modes**
   *
   * `chatMode: agent` (or `agent:<mode>`) runs the universal agent and
   * honours `tools` / `agentCapabilities`; `internal_search` and
   * `web_search` run the search assistant and ignore `tools`. Omitted,
   * it defaults to internal search.
   */
  async createConversation(
    request: models.CreateConversationRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateConversationResponse> {
    return unwrapAsync(conversationsCreateConversation(
      this,
      request,
      options,
    ));
  }

  /**
   * Create conversation with streaming response
   *
   * @remarks
   * Start a new conversation and stream the AI response over Server-Sent
   * Events (SSE). Behaves like `POST /conversations` but emits tokens,
   * tool activity, and status updates incrementally instead of returning
   * a single JSON response at the end.
   *
   * **Lifecycle**
   *
   * 1. The server validates `query`, persists an in-progress
   *    conversation, then opens the SSE stream with HTTP `200`.
   * 2. A `CUSTOM` event named `conversation_created` is emitted
   *    immediately with the new `conversationId` so the client can link
   *    the stream (sidebar, parallel tabs, deep links) without an extra
   *    request.
   * 3. AI-backend events stream through (token chunks, tool calls,
   *    status, etc.).
   * 4. On success a single root `RUN_FINISHED` event is emitted carrying
   *    the full persisted conversation in `result`.
   * 5. On failure a root `RUN_ERROR` event is emitted and the
   *    conversation is marked FAILED before the stream closes.
   *
   * **Event vocabulary**
   *
   * AG-UI is the sole wire protocol. See `ConversationStreamSSEEvent`
   * for the full event enum and payload guidance.
   *
   * Clients should ignore unknown event names rather than treating them
   * as errors.
   *
   * **Agent mode**
   *
   * When `chatMode` is `agent`,
   * the optional `tools` list restricts which tools the agent may
   * invoke for this turn. Outside agent modes the `tools` field is
   * ignored.
   */
  async streamChat(
    request: models.ConversationStreamRequest,
    options?: RequestOptions,
  ): Promise<EventStream<models.ConversationStreamSSEEvent>> {
    return unwrapAsync(conversationsStreamChat(
      this,
      request,
      options,
    ));
  }

  /**
   * List all conversations
   *
   * @remarks
   * Retrieve paginated conversations for the authenticated user.
   *
   * **Overview:**
   *
   * Use the optional `source` query parameter to choose which list to return:
   * `owned` — only conversations you own (`userId` matches the current user).
   * `shared` — conversations where you have recipient access
   * (`isShared` and your user appears in `sharedWith`), without the owner-only branch.
   * Defaults to `owned` when omitted. Each call returns one list; call twice if you need both.
   *
   * **Filtering:**
   *
   * - Only non-archived conversations are returned by default
   * - Use `/conversations/show/archives` for archived conversations
   *
   * **Sorting:**
   *
   * Conversations are sorted by last activity timestamp (most recent first) by default.
   */
  async getAllConversations(
    request?: operations.GetAllConversationsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetAllConversationsResponse> {
    return unwrapAsync(conversationsGetAllConversations(
      this,
      request,
      options,
    ));
  }

  /**
   * List archived conversations
   *
   * @remarks
   * Retrieve all archived conversations for the authenticated user.
   *
   * **Overview:**
   *
   * Archived conversations are hidden from the main list but preserved for reference.
   * This endpoint returns only conversations where `isArchived: true` and `archivedBy`
   * is set. Results include conversations the caller owns and those shared with them.
   *
   * **Filtering and sorting:**
   *
   * Results can be narrowed using `search`, `shared`, `startDate`, `endDate`, and
   * `conversationId`. Sorting is controlled by `sortBy` and `sortOrder`. Pagination
   * is controlled by `page` and `limit`.
   *
   * **Unarchiving:**
   *
   * Use `PATCH /conversations/{conversationId}/unarchive` to restore a conversation
   * to the active list.
   */
  async getArchivedConversations(
    request?: operations.GetArchivedConversationsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetArchivedConversationsResponse> {
    return unwrapAsync(conversationsGetArchivedConversations(
      this,
      request,
      options,
    ));
  }

  /**
   * Search archived conversations
   *
   * @remarks
   * Search across all archived conversations (assistant and agent) for the authenticated user.
   *
   * **Overview:**
   *
   * Performs a case-insensitive substring match against conversation titles and message content
   * across both assistant (`Conversation`) and agent (`AgentConversation`) archived collections.
   * Results are merged server-side and sorted by `lastActivityAt` descending.
   *
   * **Search parameter:**
   *
   * The `search` query parameter is required, must be a non-empty string, and is capped at
   * 1000 characters. Requests that omit it or exceed the cap return `400`.
   *
   * **Pagination:**
   *
   * Results are paginated using `page` and `limit`. The response includes a `pagination`
   * block with total counts and a `summary` block that breaks matches down by source.
   *
   * **Item shape:**
   *
   * Each item is a conversation list entry (no `messages` payload — that field is omitted
   * for performance) tagged with `source`, plus computed `isOwner`, `accessLevel`,
   * `archivedAt`, and `archivedBy`. `agentKey` is present only when `source` is `agent`.
   */
  async searchArchivedConversations(
    request: operations.SearchArchivedConversationsRequest,
    options?: RequestOptions,
  ): Promise<operations.SearchArchivedConversationsResponse> {
    return unwrapAsync(conversationsSearchArchivedConversations(
      this,
      request,
      options,
    ));
  }

  /**
   * Get conversation by ID
   *
   * @remarks
   * Retrieve a specific conversation with its full message history.
   *
   * **Overview:**
   *
   * Returns the complete conversation including all messages, citations,
   * feedback, and metadata. Messages can be paginated for long conversations.
   *
   * **Message Pagination:**
   *
   * For conversations with many messages, use pagination parameters:
   *
   * - `page`: Page number (default: 1)
   * - `limit`: Messages per page (default: 10)
   * - `sortBy`: Sort field (default: createdAt)
   * - `sortOrder`: 'asc' or 'desc' (default: desc)
   *
   * **Access Control:**
   *
   * Users can access conversations they own or that have been shared with them.
   */
  async getConversationById(
    request: operations.GetConversationByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetConversationByIdResponse> {
    return unwrapAsync(conversationsGetConversationById(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete conversation
   *
   * @remarks
   * Delete a conversation by its ID.
   *
   * **Overview:**
   *
   * Performs a soft delete by setting `isDeleted: true`. The conversation is
   * removed from listings but preserved in the database. All citations
   * referenced by messages in the conversation are also soft-deleted.
   *
   * **Permissions:**
   *
   * The conversation initiator can always delete. Users the conversation has
   * been shared with may delete it only when their `sharedWith.accessLevel`
   * is `write`.
   */
  async deleteConversationById(
    request: operations.DeleteConversationByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteConversationByIdResponse> {
    return unwrapAsync(conversationsDeleteConversationById(
      this,
      request,
      options,
    ));
  }

  /**
   * Add message (non-streaming)
   *
   * @remarks
   * Ask a follow-up in an existing assistant conversation and wait for
   * the complete answer. The JSON counterpart of
   * `POST /conversations/{conversationId}/messages/stream`. Earlier turns
   * are sent to the model as history; project context comes from the
   * conversation, never from the request.
   *
   * **How a turn runs**
   *
   * 1. The user's message is saved (in its own short transaction on a
   *    replica set).
   * 2. The AI backend runs the same agent-loop pipeline as the `/stream`
   *    route and returns only its final result. No transaction is held
   *    during this call, and the call is never retried.
   * 3. The answer, citations and status are saved exactly as the
   *    streaming route saves them, and the updated conversation is
   *    returned.
   *
   * Every failure after step 1 is persisted: the conversation ends with
   * status `Failed`, a `failReason`, and an `error` message, and the
   * response carries `X-Conversation-Id` so the caller can fetch it.
   * A 4xx from the AI backend (for example no model configured) keeps
   * its status and user-facing message; other failures return 500 with
   * a generic message.
   *
   * The response arrives only when the whole answer is ready, which can
   * take minutes for agent runs. Allow a generous client and proxy
   * timeout, or use the `/stream` variant for interactive clients.
   */
  async addMessage(
    request: operations.AddMessageRequest,
    options?: RequestOptions,
  ): Promise<operations.AddMessageResponse> {
    return unwrapAsync(conversationsAddMessage(
      this,
      request,
      options,
    ));
  }

  /**
   * Add message to a conversation with streaming response
   *
   * @remarks
   * Add a follow-up message to an existing conversation and stream the
   * assistant's response over Server-Sent Events.
   *
   * Functionally equivalent to `POST /conversations/{conversationId}/messages`
   * but the response is delivered as an SSE stream so clients can render
   * the answer incrementally.
   *
   * AG-UI is the sole wire protocol. The vocabulary is described by
   * `ConversationMessageStreamSSEEvent`; it is the same event set as
   * `/conversations/stream`, while the terminal result reflects an
   * existing conversation.
   */
  async addMessageStream(
    request: operations.AddMessageStreamRequest,
    options?: RequestOptions,
  ): Promise<EventStream<models.ConversationMessageStreamSSEEvent>> {
    return unwrapAsync(conversationsAddMessageStream(
      this,
      request,
      options,
    ));
  }

  /**
   * Update conversation title
   *
   * @remarks
   * Update the title of a conversation.
   *
   * **Overview:**
   *
   * Conversation titles are auto-generated from the first query by default.
   * Use this endpoint to set a custom, more descriptive title.
   *
   * **Title limits:**
   *
   * - Minimum: 1 character
   * - Maximum: 200 characters
   *
   * **Permissions:**
   *
   * The conversation must exist, belong to the calling user's organization,
   * be owned by the caller (matched on `userId`), and not be soft-deleted.
   */
  async updateConversationTitle(
    request: operations.UpdateConversationTitleRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateConversationTitleResponse> {
    return unwrapAsync(conversationsUpdateConversationTitle(
      this,
      request,
      options,
    ));
  }

  /**
   * Archive conversation
   *
   * @remarks
   * Archive a conversation to hide it from the main list.
   *
   * **Overview:**
   *
   * Archived conversations are preserved but hidden from the default conversation list.
   * Use archiving to clean up your workspace without permanently deleting conversations.
   *
   * **Access:**
   *
   * The caller must be the conversation's initiator, or be listed in `sharedWith`
   * with `accessLevel: write`. Already-archived conversations return `400`.
   *
   * **Retrieval:**
   *
   * View archived conversations using `GET /conversations/show/archives`.
   * Restore one with `PATCH /conversations/{conversationId}/unarchive`.
   */
  async archiveConversation(
    request: operations.ArchiveConversationRequest,
    options?: RequestOptions,
  ): Promise<operations.ArchiveConversationResponse> {
    return unwrapAsync(conversationsArchiveConversation(
      this,
      request,
      options,
    ));
  }

  /**
   * Unarchive conversation
   *
   * @remarks
   * Restore an archived conversation.
   *
   * - Path params: `conversationId`
   * - Query params: none
   * - Body: none
   */
  async unarchiveConversation(
    request: operations.UnarchiveConversationRequest,
    options?: RequestOptions,
  ): Promise<operations.UnarchiveConversationResponse> {
    return unwrapAsync(conversationsUnarchiveConversation(
      this,
      request,
      options,
    ));
  }

  /**
   * Regenerate AI response
   *
   * @remarks
   * Regenerate the AI response for a specific message and stream the new
   * answer over Server-Sent Events.
   *
   * **Overview:**
   *
   * If you're not satisfied with an AI response, use this endpoint to generate
   * a new answer. The original user query is re-processed and a new bot
   * response replaces the previous one in place.
   *
   * **Constraints:**
   *
   * - Only the *last* message of the conversation can be regenerated.
   * - The target message must be of type `bot_response`.
   *
   * **Use Cases:**
   *
   * - Response was incomplete or unclear
   * - Want to try a different AI model
   * - New documents have been indexed since original response
   *
   * **Model Override:**
   *
   * Specify `modelKey` to use a different model for regeneration.
   *
   * **Streaming:**
   *
   * The response is delivered as an AG-UI `text/event-stream` stream.
   * Routing still depends on `chatMode`: `internal_search` and
   * `web_search` use the assistant backend, while `agent` uses the
   * universal agent loop. See `SSEEvent` for the event vocabulary.
   */
  async regenerateAnswer(
    request: operations.RegenerateAnswerRequest,
    options?: RequestOptions,
  ): Promise<EventStream<models.SSEEvent>> {
    return unwrapAsync(conversationsRegenerateAnswer(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel an in-flight chat stream
   *
   * @remarks
   * Cooperatively stop a `POST /conversations/stream` or
   * `POST /conversations/{conversationId}/messages/stream` run that is
   * still generating, using the `runId` sent when that stream started.
   *
   * This is a synchronous JSON ack, not another SSE stream. The
   * cancelled run's own stream (if still connected) receives a terminal
   * frame with a `stopped` status and whatever partial answer had
   * already generated; nothing further is delivered here.
   *
   * `{ cancelled: false }` — not an error — covers a `runId` that
   * already finished or was never registered; the caller only needs to
   * know the stream is not running anymore, not why.
   *
   * `runId` must belong to a run started on THIS `conversationId` — a
   * `runId` that exists but was registered under a different
   * conversation (even one owned by the same caller) is rejected with
   * `403`, same as a `runId` owned by a different user/org.
   */
  async cancelConversationStream(
    request: operations.CancelConversationStreamRequest,
    options?: RequestOptions,
  ): Promise<operations.CancelConversationStreamResponse> {
    return unwrapAsync(conversationsCancelConversationStream(
      this,
      request,
      options,
    ));
  }

  /**
   * Submit feedback on AI response
   *
   * @remarks
   * Append a feedback entry to a bot-response message.
   *
   * **Overview**
   *
   * Feedback helps improve AI response quality over time. You can record an
   * overall helpfulness signal, issue categories, and free-text comments.
   * Each call appends a new entry to the message; previous entries are
   * preserved.
   *
   * **Feedback options**
   *
   * - `isHelpful` — overall thumbs up/down.
   * - `categories` — issue or positive categories from a fixed list.
   * - `comments` — free-text `positive` and `negative`.
   *
   * **Restrictions**
   *
   * Feedback can only be submitted on `bot_response` messages — user
   * queries and system messages are rejected with `400`.
   */
  async updateMessageFeedback(
    request: operations.UpdateMessageFeedbackRequest,
    options?: RequestOptions,
  ): Promise<models.MessageFeedbackUpdateResponse> {
    return unwrapAsync(conversationsUpdateMessageFeedback(
      this,
      request,
      options,
    ));
  }

  /**
   * Link or unlink a conversation to a project
   *
   * @remarks
   * Set (`projectId: <id>`) or clear (`projectId: null`) the project this
   * conversation belongs to. Initiator-only.
   *
   * **Access:**
   *
   * The caller must be the conversation's initiator. Linking to a
   * non-null `projectId` also requires at least viewer access to that
   * project (`404` if not visible to the caller — never `403`, to avoid
   * leaking project existence across an org boundary).
   *
   * **Visibility on link:**
   *
   * When linking, `projectVisibility` defaults from the project's
   * `chatSharing` setting (`members` → `project`, otherwise `private`)
   * unless the conversation was already `project`-visible, in which case
   * that is preserved. Use
   * `PATCH /conversations/{conversationId}/project-visibility` to
   * override it explicitly. Unlinking (`projectId: null`) always clears
   * both `projectId` and `projectVisibility`.
   */
  async setConversationProject(
    request: operations.SetConversationProjectRequest,
    options?: RequestOptions,
  ): Promise<operations.SetConversationProjectResponse> {
    return unwrapAsync(conversationsSetConversationProject(
      this,
      request,
      options,
    ));
  }

  /**
   * Override a conversation's project visibility
   *
   * @remarks
   * Explicitly set whether a project-linked conversation is visible to
   * other members of that project (`project`) or only to its owner
   * (`private`). Initiator-only. Requires the conversation to already be
   * linked to a project via
   * `PUT /conversations/{conversationId}/project`.
   */
  async setConversationProjectVisibility(
    request: operations.SetConversationProjectVisibilityRequest,
    options?: RequestOptions,
  ): Promise<operations.SetConversationProjectVisibilityResponse> {
    return unwrapAsync(conversationsSetConversationProjectVisibility(
      this,
      request,
      options,
    ));
  }

  /**
   * List a project's conversations
   *
   * @remarks
   * Requires viewer access to the project. Returns both chat and agent
   * sessions (`chatSessions`, discriminated by `sessionType`/`agentKey`)
   * that the caller may see: rows they own, plus rows with
   * `projectVisibility: project`. Access to the project is asserted
   * first, so a private conversation belonging to a *different* project
   * member never leaks through this endpoint.
   */
  async getProjectConversations(
    request: operations.GetProjectConversationsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetProjectConversationsResponse> {
    return unwrapAsync(conversationsGetProjectConversations(
      this,
      request,
      options,
    ));
  }
}
