/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { conversationsGetProjectConversations } from "../funcs/conversations-get-project-conversations.js";
import { conversationsSetConversationProjectVisibility } from "../funcs/conversations-set-conversation-project-visibility.js";
import { conversationsSetConversationProject } from "../funcs/conversations-set-conversation-project.js";
import { projectsArchiveProject } from "../funcs/projects-archive-project.js";
import { projectsCreateProject } from "../funcs/projects-create-project.js";
import { projectsDeleteProject } from "../funcs/projects-delete-project.js";
import { projectsEnsureProjectKnowledgeBase } from "../funcs/projects-ensure-project-knowledge-base.js";
import { projectsGetProjectById } from "../funcs/projects-get-project-by-id.js";
import { projectsListProjectMembers } from "../funcs/projects-list-project-members.js";
import { projectsListProjects } from "../funcs/projects-list-projects.js";
import { projectsPinProject } from "../funcs/projects-pin-project.js";
import { projectsRemoveProjectMember } from "../funcs/projects-remove-project-member.js";
import { projectsSetAgentConversationProjectVisibility } from "../funcs/projects-set-agent-conversation-project-visibility.js";
import { projectsSetAgentConversationProject } from "../funcs/projects-set-agent-conversation-project.js";
import { projectsUnarchiveProject } from "../funcs/projects-unarchive-project.js";
import { projectsUnpinProject } from "../funcs/projects-unpin-project.js";
import { projectsUpdateProject } from "../funcs/projects-update-project.js";
import { projectsUpsertProjectMembers } from "../funcs/projects-upsert-project-members.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Projects extends ClientSDK {
  /**
   * Link or unlink a conversation to a project
   *
   * @remarks
   * Set (`projectId: <id>`) or clear (`projectId: null`) the project this
   * conversation belongs to. Initiator-only.
   *
   * **Access:**
   *
   * The caller must be the conversation's initiator. Linking to a
   * non-null `projectId` also requires at least viewer access to that
   * project (`404` if not visible to the caller — never `403`, to avoid
   * leaking project existence across an org boundary).
   *
   * **Visibility on link:**
   *
   * When linking, `projectVisibility` defaults from the project's
   * `chatSharing` setting (`members` → `project`, otherwise `private`)
   * unless the conversation was already `project`-visible, in which case
   * that is preserved. Use
   * `PATCH /conversations/{conversationId}/project-visibility` to
   * override it explicitly. Unlinking (`projectId: null`) always clears
   * both `projectId` and `projectVisibility`.
   */
  async setConversationProject(
    request: operations.SetConversationProjectRequest,
    options?: RequestOptions,
  ): Promise<operations.SetConversationProjectResponse> {
    return unwrapAsync(conversationsSetConversationProject(
      this,
      request,
      options,
    ));
  }

  /**
   * Override a conversation's project visibility
   *
   * @remarks
   * Explicitly set whether a project-linked conversation is visible to
   * other members of that project (`project`) or only to its owner
   * (`private`). Initiator-only. Requires the conversation to already be
   * linked to a project via
   * `PUT /conversations/{conversationId}/project`.
   */
  async setConversationProjectVisibility(
    request: operations.SetConversationProjectVisibilityRequest,
    options?: RequestOptions,
  ): Promise<operations.SetConversationProjectVisibilityResponse> {
    return unwrapAsync(conversationsSetConversationProjectVisibility(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a project
   *
   * @remarks
   * Create a new project workspace owned by the caller.
   */
  async createProject(
    request: models.CreateProjectRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateProjectResponse> {
    return unwrapAsync(projectsCreateProject(
      this,
      request,
      options,
    ));
  }

  /**
   * List projects
   *
   * @remarks
   * Paginated, non-deleted projects visible to the caller, sorted pinned
   * first then by `lastActivityAt` descending.
   */
  async listProjects(
    request?: operations.ListProjectsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListProjectsResponse> {
    return unwrapAsync(projectsListProjects(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a project
   *
   * @remarks
   * Requires at least viewer access. Cross-org ids and ids the caller
   * cannot see both return `404` — never `403` — to avoid leaking
   * project existence across an org boundary.
   */
  async getProjectById(
    request: operations.GetProjectByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetProjectByIdResponse> {
    return unwrapAsync(projectsGetProjectById(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a project
   *
   * @remarks
   * Requires editor access. `visibility` and `chatSharing` are
   * owner-only fields — including either as a non-owner editor
   * returns `403`.
   */
  async updateProject(
    request: operations.UpdateProjectRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateProjectResponse> {
    return unwrapAsync(projectsUpdateProject(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a project
   *
   * @remarks
   * Owner-only soft delete. Unlinks every `chatSessions` row pointing at
   * this project (clearing `projectId`/`projectVisibility`) before
   * marking the project deleted, so no conversation is left pointing at
   * a deleted project; wrapped in a transaction when the deployment's
   * replica set supports it. Idempotent — deleting an already-deleted
   * project returns `200` without re-running the unlink step.
   */
  async deleteProject(
    request: operations.DeleteProjectRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteProjectResponse> {
    return unwrapAsync(projectsDeleteProject(
      this,
      request,
      options,
    ));
  }

  /**
   * Archive a project
   *
   * @remarks
   * Requires editor access. Archived projects are hidden from the
   * default sidebar but their conversations remain reachable directly.
   */
  async archiveProject(
    request: operations.ArchiveProjectRequest,
    options?: RequestOptions,
  ): Promise<operations.ArchiveProjectResponse> {
    return unwrapAsync(projectsArchiveProject(
      this,
      request,
      options,
    ));
  }

  /**
   * Unarchive a project
   */
  async unarchiveProject(
    request: operations.UnarchiveProjectRequest,
    options?: RequestOptions,
  ): Promise<operations.UnarchiveProjectResponse> {
    return unwrapAsync(projectsUnarchiveProject(
      this,
      request,
      options,
    ));
  }

  /**
   * Pin a project
   *
   * @remarks
   * Requires viewer access. Pin state is owner-scoped on the document in
   * V1 — pinning affects the project for every viewer, not just the
   * caller (per-user pins are deferred).
   */
  async pinProject(
    request: operations.PinProjectRequest,
    options?: RequestOptions,
  ): Promise<operations.PinProjectResponse> {
    return unwrapAsync(projectsPinProject(
      this,
      request,
      options,
    ));
  }

  /**
   * Unpin a project
   */
  async unpinProject(
    request: operations.UnpinProjectRequest,
    options?: RequestOptions,
  ): Promise<operations.UnpinProjectResponse> {
    return unwrapAsync(projectsUnpinProject(
      this,
      request,
      options,
    ));
  }

  /**
   * List a project's conversations
   *
   * @remarks
   * Requires viewer access to the project. Returns both chat and agent
   * sessions (`chatSessions`, discriminated by `sessionType`/`agentKey`)
   * that the caller may see: rows they own, plus rows with
   * `projectVisibility: project`. Access to the project is asserted
   * first, so a private conversation belonging to a *different* project
   * member never leaks through this endpoint.
   */
  async getProjectConversations(
    request: operations.GetProjectConversationsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetProjectConversationsResponse> {
    return unwrapAsync(conversationsGetProjectConversations(
      this,
      request,
      options,
    ));
  }

  /**
   * Ensure (create-if-absent) the project's hidden file Collection
   *
   * @remarks
   * Requires editor access. Lazily creates the project's own hidden
   * Knowledge Base (`isHidden: true` in Python `POST /api/v1/kb`) the
   * first time a caller needs to upload a file, and returns its id
   * either way. Race-safe: concurrent callers converge on one KB —
   * the losing request's KB is deleted. The hidden KB is excluded from
   * the Collections sidebar, Knowledge Hub, and unscoped search, but is
   * always included in this project's own chat scope
   * (`filters.kb`) and file uploads go through the normal
   * `POST /knowledgeBase/{kbId}/upload` SSE pipeline afterward.
   */
  async ensureProjectKnowledgeBase(
    request: operations.EnsureProjectKnowledgeBaseRequest,
    options?: RequestOptions,
  ): Promise<operations.EnsureProjectKnowledgeBaseResponse> {
    return unwrapAsync(projectsEnsureProjectKnowledgeBase(
      this,
      request,
      options,
    ));
  }

  /**
   * List project members
   *
   * @remarks
   * Requires viewer access.
   */
  async listProjectMembers(
    request: operations.ListProjectMembersRequest,
    options?: RequestOptions,
  ): Promise<operations.ListProjectMembersResponse> {
    return unwrapAsync(projectsListProjectMembers(
      this,
      request,
      options,
    ));
  }

  /**
   * Add or update project members
   *
   * @remarks
   * Owner-only. Each `principalId` is validated against this org's IAM
   * service the same way as
   * `POST /conversations/{conversationId}/share` — a `principalId` with
   * no matching user returns `400`. Upserts by `principalId`; the owner
   * is silently skipped if included.
   */
  async upsertProjectMembers(
    request: operations.UpsertProjectMembersRequest,
    options?: RequestOptions,
  ): Promise<operations.UpsertProjectMembersResponse> {
    return unwrapAsync(projectsUpsertProjectMembers(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a project member
   *
   * @remarks
   * Owner-only.
   */
  async removeProjectMember(
    request: operations.RemoveProjectMemberRequest,
    options?: RequestOptions,
  ): Promise<operations.RemoveProjectMemberResponse> {
    return unwrapAsync(projectsRemoveProjectMember(
      this,
      request,
      options,
    ));
  }

  /**
   * Link or unlink an agent conversation to a project
   *
   * @remarks
   * Agent-conversation equivalent of
   * `PUT /conversations/{conversationId}/project`. Set
   * (`projectId: <id>`) or clear (`projectId: null`) the project this
   * agent conversation belongs to. Initiator-only; linking requires at
   * least viewer access to the target project.
   */
  async setAgentConversationProject(
    request: operations.SetAgentConversationProjectRequest,
    options?: RequestOptions,
  ): Promise<operations.SetAgentConversationProjectResponse> {
    return unwrapAsync(projectsSetAgentConversationProject(
      this,
      request,
      options,
    ));
  }

  /**
   * Override an agent conversation's project visibility
   *
   * @remarks
   * Agent-conversation equivalent of
   * `PATCH /conversations/{conversationId}/project-visibility`.
   * Initiator-only; requires the conversation to already be linked to a
   * project.
   */
  async setAgentConversationProjectVisibility(
    request: operations.SetAgentConversationProjectVisibilityRequest,
    options?: RequestOptions,
  ): Promise<operations.SetAgentConversationProjectVisibilityResponse> {
    return unwrapAsync(projectsSetAgentConversationProjectVisibility(
      this,
      request,
      options,
    ));
  }
}
