/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userAccountAuthenticate } from "../funcs/user-account-authenticate.js";
import { userAccountInitAuth } from "../funcs/user-account-init-auth.js";
import { userAccountResetPasswordWithToken } from "../funcs/user-account-reset-password-with-token.js";
import { userAccountResetPassword } from "../funcs/user-account-reset-password.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class UserAccount extends ClientSDK {
  /**
   * Initialize authentication session
   *
   * @remarks
   * Start a server-side authentication session and discover which sign-in methods are
   * configured for the organization. This is the first step in the multi-step login flow.
   *
   * **Request body (optional)**
   *
   * - You may omit the body, send an empty JSON object `{}`, or send `{ "email": "..." }`.
   * - `email` in the body is optional and kept for legacy reasons; omitting it does not prevent
   *   initialization. The web client typically calls this endpoint without a body and sends
   *   `email` on `/authenticate` instead.
   * - When provided, `email` is stored on the session for correlation with subsequent steps.
   *
   * **Flow:**
   *
   * 1. Call this endpoint (optional JSON body as above).
   * 2. Receive a session token in the `x-session-token` response header.
   * 3. Send that token on subsequent `/authenticate` requests (`x-session-token` header).
   * 4. Use `allowedMethods` and `authProviders` from the response to render the login UI.
   *
   * **Session token**
   *
   * - Returned as header `x-session-token`.
   * - Required for `/authenticate` (and related steps) until it expires.
   *
   * **Multi-factor authentication**
   *
   * If the organization has MFA, complete multiple authentication steps; each step may
   * return the next step's allowed methods.
   */
  async initAuth(
    request?: models.InitAuthRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.InitAuthResponse> {
    return unwrapAsync(userAccountInitAuth(
      this,
      request,
      options,
    ));
  }

  /**
   * Authenticate user with credentials
   *
   * @remarks
   * Authenticate a user using the specified method and credentials.
   * Requires a valid session token from `/initAuth`.
   *
   * **Credential Formats by Method:**
   *
   * - `password`: `{ "credentials": { "password": "your-password" } }`
   * - `otp`: `{ "credentials": { "otp": "123456" } }` (6-digit code, valid for 10 minutes)
   * - `google`: `{ "credentials": "google-id-token-string" }`
   * - `microsoft`: `{ "credentials": { "accessToken": "...", "idToken": "..." } }`
   * - `azureAd`: `{ "credentials": { "accessToken": "...", "idToken": "..." } }`
   * - `oauth`: `{ "credentials": { "accessToken": "...", "idToken": "..." } }`
   * - `samlSso`: Handled via redirect flow (use `/saml/signIn` instead)
   *
   * **Multi-Step Response:**
   *
   * If organization uses MFA, successful authentication returns:
   * - `status: "success"` with `nextStep` and `allowedMethods` for next step
   *
   * **Fully Authenticated Response:**
   *
   * After completing all steps:
   * - `message: "Fully authenticated"` with `accessToken` (1hr) and `refreshToken` (7d)
   *
   * **Security:**
   *
   * - Account locks after 5 consecutive failed attempts
   * - CAPTCHA may be required if enabled (pass `cf-turnstile-response`)
   */
  async authenticate(
    request: operations.AuthenticateRequest,
    options?: RequestOptions,
  ): Promise<models.AuthenticateResponse> {
    return unwrapAsync(userAccountAuthenticate(
      this,
      request,
      options,
    ));
  }

  /**
   * Reset password with email token
   *
   * @remarks
   * Reset password using a token received via email from the forgot password flow.
   *
   * **Password Requirements:**
   *
   * - Minimum 8 characters
   * - At least 1 uppercase letter
   * - At least 1 lowercase letter
   * - At least 1 number
   * - At least 1 special character (#?!@$%^&*-)
   *
   * **Security Notes:**
   *
   * - Token is single-use and expires after a set time
   * - Response body contains a confirmation string in `data`
   */
  async resetPasswordWithToken(
    security: operations.ResetPasswordWithTokenSecurity,
    request: models.TokenPasswordResetRequest,
    options?: RequestOptions,
  ): Promise<models.DataStringResponse> {
    return unwrapAsync(userAccountResetPasswordWithToken(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Reset password
   *
   * @remarks
   * Reset the password for the currently authenticated user.
   *
   * **Overview:**
   *
   * Allows a logged-in user to change their password by providing the current password and a new password.
   */
  async resetPassword(
    request: operations.ResetPasswordRequest,
    options?: RequestOptions,
  ): Promise<models.AuthenticatedPasswordResetResponse> {
    return unwrapAsync(userAccountResetPassword(
      this,
      request,
      options,
    ));
  }
}
