/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type AdminCheckRequest = {
  id: string;
};

/**
 * User is an admin
 */
export type AdminCheckResponse = {
  message?: string | undefined;
};

/** @internal */
export type AdminCheckRequest$Outbound = {
  id: string;
};

/** @internal */
export const AdminCheckRequest$outboundSchema: z.ZodMiniType<
  AdminCheckRequest$Outbound,
  AdminCheckRequest
> = z.object({
  id: z.string(),
});

export function adminCheckRequestToJSON(
  adminCheckRequest: AdminCheckRequest,
): string {
  return JSON.stringify(
    AdminCheckRequest$outboundSchema.parse(adminCheckRequest),
  );
}

/** @internal */
export const AdminCheckResponse$inboundSchema: z.ZodMiniType<
  AdminCheckResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
});

export function adminCheckResponseFromJSON(
  jsonString: string,
): SafeParseResult<AdminCheckResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AdminCheckResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdminCheckResponse' from JSON`,
  );
}
