/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type AdminListPersonalAccessTokensRequest = {
  /**
   * Page number (defaults to `1` when omitted or empty)
   */
  page?: number | undefined;
  /**
   * Items per page (defaults to `100` when omitted or empty; max 100)
   */
  limit?: number | undefined;
};

/** @internal */
export type AdminListPersonalAccessTokensRequest$Outbound = {
  page: number;
  limit: number;
};

/** @internal */
export const AdminListPersonalAccessTokensRequest$outboundSchema: z.ZodMiniType<
  AdminListPersonalAccessTokensRequest$Outbound,
  AdminListPersonalAccessTokensRequest
> = z.object({
  page: z._default(z.int(), 1),
  limit: z._default(z.int(), 100),
});

export function adminListPersonalAccessTokensRequestToJSON(
  adminListPersonalAccessTokensRequest: AdminListPersonalAccessTokensRequest,
): string {
  return JSON.stringify(
    AdminListPersonalAccessTokensRequest$outboundSchema.parse(
      adminListPersonalAccessTokensRequest,
    ),
  );
}
