/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type CancelAgentConversationStreamRequestBody = {
  /**
   * The `runId` sent when the stream was started.
   */
  runId: string;
};

export type CancelAgentConversationStreamRequest = {
  /**
   * Stable key identifying the agent that owns this conversation.
   */
  agentKey: string;
  /**
   * ID of the agent conversation to cancel a run for.
   */
  conversationId: string;
  body: CancelAgentConversationStreamRequestBody;
};

/**
 * Cancellation requested, or the run had already finished.
 */
export type CancelAgentConversationStreamResponse = {
  cancelled?: boolean | undefined;
};

/** @internal */
export type CancelAgentConversationStreamRequestBody$Outbound = {
  runId: string;
};

/** @internal */
export const CancelAgentConversationStreamRequestBody$outboundSchema:
  z.ZodMiniType<
    CancelAgentConversationStreamRequestBody$Outbound,
    CancelAgentConversationStreamRequestBody
  > = z.object({
    runId: z.string(),
  });

export function cancelAgentConversationStreamRequestBodyToJSON(
  cancelAgentConversationStreamRequestBody:
    CancelAgentConversationStreamRequestBody,
): string {
  return JSON.stringify(
    CancelAgentConversationStreamRequestBody$outboundSchema.parse(
      cancelAgentConversationStreamRequestBody,
    ),
  );
}

/** @internal */
export type CancelAgentConversationStreamRequest$Outbound = {
  agentKey: string;
  conversationId: string;
  body: CancelAgentConversationStreamRequestBody$Outbound;
};

/** @internal */
export const CancelAgentConversationStreamRequest$outboundSchema: z.ZodMiniType<
  CancelAgentConversationStreamRequest$Outbound,
  CancelAgentConversationStreamRequest
> = z.object({
  agentKey: z.string(),
  conversationId: z.string(),
  body: z.lazy(() => CancelAgentConversationStreamRequestBody$outboundSchema),
});

export function cancelAgentConversationStreamRequestToJSON(
  cancelAgentConversationStreamRequest: CancelAgentConversationStreamRequest,
): string {
  return JSON.stringify(
    CancelAgentConversationStreamRequest$outboundSchema.parse(
      cancelAgentConversationStreamRequest,
    ),
  );
}

/** @internal */
export const CancelAgentConversationStreamResponse$inboundSchema: z.ZodMiniType<
  CancelAgentConversationStreamResponse,
  unknown
> = z.object({
  cancelled: types.optional(types.boolean()),
});

export function cancelAgentConversationStreamResponseFromJSON(
  jsonString: string,
): SafeParseResult<CancelAgentConversationStreamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CancelAgentConversationStreamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CancelAgentConversationStreamResponse' from JSON`,
  );
}
