/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Project created
 */
export type CreateProjectResponse = {
  /**
   * A workspace that groups related assistant and agent conversations
   *
   * @remarks
   * under a shared name, instructions, knowledge scope, tool
   * selection, and its own hidden Collection of uploaded files. See
   * the `Projects` tag description for the sharing model.
   */
  project: models.Project;
};

/** @internal */
export const CreateProjectResponse$inboundSchema: z.ZodMiniType<
  CreateProjectResponse,
  unknown
> = z.object({
  project: models.Project$inboundSchema,
});

export function createProjectResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateProjectResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateProjectResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateProjectResponse' from JSON`,
  );
}
