/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateConnectorInstanceSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2 | undefined;
};

/**
 * Instance created
 */
export type CreateConnectorInstanceResponse = {
  success?: boolean | undefined;
  /**
   * A configured connector instance. Represents an active or configured
   *
   * @remarks
   * connection to an external service.
   */
  connector?: models.ConnectorInstance | undefined;
};

/** @internal */
export type CreateConnectorInstanceSecurity$Outbound = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2$Outbound | undefined;
};

/** @internal */
export const CreateConnectorInstanceSecurity$outboundSchema: z.ZodMiniType<
  CreateConnectorInstanceSecurity$Outbound,
  CreateConnectorInstanceSecurity
> = z.object({
  bearerAuth: z.optional(z.string()),
  oauth2: z.optional(models.SchemeOauth2$outboundSchema),
});

export function createConnectorInstanceSecurityToJSON(
  createConnectorInstanceSecurity: CreateConnectorInstanceSecurity,
): string {
  return JSON.stringify(
    CreateConnectorInstanceSecurity$outboundSchema.parse(
      createConnectorInstanceSecurity,
    ),
  );
}

/** @internal */
export const CreateConnectorInstanceResponse$inboundSchema: z.ZodMiniType<
  CreateConnectorInstanceResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  connector: types.optional(models.ConnectorInstance$inboundSchema),
});

export function createConnectorInstanceResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateConnectorInstanceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateConnectorInstanceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateConnectorInstanceResponse' from JSON`,
  );
}
