/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteKnowledgeBaseRequest = {
  /**
   * Knowledge base ID (non-empty string)
   */
  kbId: string;
};

/** @internal */
export type DeleteKnowledgeBaseRequest$Outbound = {
  kbId: string;
};

/** @internal */
export const DeleteKnowledgeBaseRequest$outboundSchema: z.ZodMiniType<
  DeleteKnowledgeBaseRequest$Outbound,
  DeleteKnowledgeBaseRequest
> = z.object({
  kbId: z.string(),
});

export function deleteKnowledgeBaseRequestToJSON(
  deleteKnowledgeBaseRequest: DeleteKnowledgeBaseRequest,
): string {
  return JSON.stringify(
    DeleteKnowledgeBaseRequest$outboundSchema.parse(deleteKnowledgeBaseRequest),
  );
}
