/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteProjectRequest = {
  projectId: string;
};

/**
 * Project deleted (or already deleted)
 */
export type DeleteProjectResponse = {
  message?: string | undefined;
};

/** @internal */
export type DeleteProjectRequest$Outbound = {
  projectId: string;
};

/** @internal */
export const DeleteProjectRequest$outboundSchema: z.ZodMiniType<
  DeleteProjectRequest$Outbound,
  DeleteProjectRequest
> = z.object({
  projectId: z.string(),
});

export function deleteProjectRequestToJSON(
  deleteProjectRequest: DeleteProjectRequest,
): string {
  return JSON.stringify(
    DeleteProjectRequest$outboundSchema.parse(deleteProjectRequest),
  );
}

/** @internal */
export const DeleteProjectResponse$inboundSchema: z.ZodMiniType<
  DeleteProjectResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
});

export function deleteProjectResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteProjectResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteProjectResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteProjectResponse' from JSON`,
  );
}
