/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteAgentConversationChatAttachmentRequest = {
  /**
   * Agent key path parameter. Must be non-empty.
   */
  agentKey: string;
  /**
   * Attachment record id (from the upload response). Must be non-blank after trim.
   */
  recordId: string;
};

/** @internal */
export type DeleteAgentConversationChatAttachmentRequest$Outbound = {
  agentKey: string;
  recordId: string;
};

/** @internal */
export const DeleteAgentConversationChatAttachmentRequest$outboundSchema:
  z.ZodMiniType<
    DeleteAgentConversationChatAttachmentRequest$Outbound,
    DeleteAgentConversationChatAttachmentRequest
  > = z.object({
    agentKey: z.string(),
    recordId: z.string(),
  });

export function deleteAgentConversationChatAttachmentRequestToJSON(
  deleteAgentConversationChatAttachmentRequest:
    DeleteAgentConversationChatAttachmentRequest,
): string {
  return JSON.stringify(
    DeleteAgentConversationChatAttachmentRequest$outboundSchema.parse(
      deleteAgentConversationChatAttachmentRequest,
    ),
  );
}
