/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DocumentDiffCheckerRequest = {
  documentId: string;
};

/**
 * Modification status retrieved
 */
export type DocumentDiffCheckerResponse = {
  isModified?: boolean | undefined;
};

/** @internal */
export type DocumentDiffCheckerRequest$Outbound = {
  documentId: string;
};

/** @internal */
export const DocumentDiffCheckerRequest$outboundSchema: z.ZodMiniType<
  DocumentDiffCheckerRequest$Outbound,
  DocumentDiffCheckerRequest
> = z.object({
  documentId: z.string(),
});

export function documentDiffCheckerRequestToJSON(
  documentDiffCheckerRequest: DocumentDiffCheckerRequest,
): string {
  return JSON.stringify(
    DocumentDiffCheckerRequest$outboundSchema.parse(documentDiffCheckerRequest),
  );
}

/** @internal */
export const DocumentDiffCheckerResponse$inboundSchema: z.ZodMiniType<
  DocumentDiffCheckerResponse,
  unknown
> = z.object({
  isModified: types.optional(types.boolean()),
});

export function documentDiffCheckerResponseFromJSON(
  jsonString: string,
): SafeParseResult<DocumentDiffCheckerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DocumentDiffCheckerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentDiffCheckerResponse' from JSON`,
  );
}
