/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type GetKnowledgeBaseSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2 | undefined;
};

export type GetKnowledgeBaseRequest = {
  /**
   * Knowledge base ID
   */
  kbId: string;
};

/** @internal */
export type GetKnowledgeBaseSecurity$Outbound = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2$Outbound | undefined;
};

/** @internal */
export const GetKnowledgeBaseSecurity$outboundSchema: z.ZodMiniType<
  GetKnowledgeBaseSecurity$Outbound,
  GetKnowledgeBaseSecurity
> = z.object({
  bearerAuth: z.optional(z.string()),
  oauth2: z.optional(models.SchemeOauth2$outboundSchema),
});

export function getKnowledgeBaseSecurityToJSON(
  getKnowledgeBaseSecurity: GetKnowledgeBaseSecurity,
): string {
  return JSON.stringify(
    GetKnowledgeBaseSecurity$outboundSchema.parse(getKnowledgeBaseSecurity),
  );
}

/** @internal */
export type GetKnowledgeBaseRequest$Outbound = {
  kbId: string;
};

/** @internal */
export const GetKnowledgeBaseRequest$outboundSchema: z.ZodMiniType<
  GetKnowledgeBaseRequest$Outbound,
  GetKnowledgeBaseRequest
> = z.object({
  kbId: z.string(),
});

export function getKnowledgeBaseRequestToJSON(
  getKnowledgeBaseRequest: GetKnowledgeBaseRequest,
): string {
  return JSON.stringify(
    GetKnowledgeBaseRequest$outboundSchema.parse(getKnowledgeBaseRequest),
  );
}
