/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetCurrentOrganizationSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2 | undefined;
};

/**
 * Organization details retrieved successfully
 */
export type GetCurrentOrganizationResponse = {
  success?: boolean | undefined;
  data?: models.Organization | undefined;
};

/** @internal */
export type GetCurrentOrganizationSecurity$Outbound = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2$Outbound | undefined;
};

/** @internal */
export const GetCurrentOrganizationSecurity$outboundSchema: z.ZodMiniType<
  GetCurrentOrganizationSecurity$Outbound,
  GetCurrentOrganizationSecurity
> = z.object({
  bearerAuth: z.optional(z.string()),
  oauth2: z.optional(models.SchemeOauth2$outboundSchema),
});

export function getCurrentOrganizationSecurityToJSON(
  getCurrentOrganizationSecurity: GetCurrentOrganizationSecurity,
): string {
  return JSON.stringify(
    GetCurrentOrganizationSecurity$outboundSchema.parse(
      getCurrentOrganizationSecurity,
    ),
  );
}

/** @internal */
export const GetCurrentOrganizationResponse$inboundSchema: z.ZodMiniType<
  GetCurrentOrganizationResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(models.Organization$inboundSchema),
});

export function getCurrentOrganizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCurrentOrganizationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCurrentOrganizationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCurrentOrganizationResponse' from JSON`,
  );
}
