/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * User created teams retrieved successfully
 */
export type GetUserCreatedTeamsResponse = {
  success?: boolean | undefined;
  data?: Array<models.Team> | undefined;
};

/** @internal */
export const GetUserCreatedTeamsResponse$inboundSchema: z.ZodMiniType<
  GetUserCreatedTeamsResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(z.array(models.Team$inboundSchema)),
});

export function getUserCreatedTeamsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUserCreatedTeamsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserCreatedTeamsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserCreatedTeamsResponse' from JSON`,
  );
}
