/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * SharePoint credentials retrieved
 */
export type GetSharePointCredentialsResponse = {
  clientId: string;
  clientSecret: string;
  tenantId: string;
  sharepointDomain: string;
};

/** @internal */
export const GetSharePointCredentialsResponse$inboundSchema: z.ZodMiniType<
  GetSharePointCredentialsResponse,
  unknown
> = z.object({
  clientId: types.string(),
  clientSecret: types.string(),
  tenantId: types.string(),
  sharepointDomain: types.string(),
});

export function getSharePointCredentialsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSharePointCredentialsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSharePointCredentialsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSharePointCredentialsResponse' from JSON`,
  );
}
