/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type GetAgentTemplateSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2 | undefined;
};

export type GetAgentTemplateRequest = {
  /**
   * Template identifier
   */
  templateId: string;
};

/** @internal */
export type GetAgentTemplateSecurity$Outbound = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2$Outbound | undefined;
};

/** @internal */
export const GetAgentTemplateSecurity$outboundSchema: z.ZodMiniType<
  GetAgentTemplateSecurity$Outbound,
  GetAgentTemplateSecurity
> = z.object({
  bearerAuth: z.optional(z.string()),
  oauth2: z.optional(models.SchemeOauth2$outboundSchema),
});

export function getAgentTemplateSecurityToJSON(
  getAgentTemplateSecurity: GetAgentTemplateSecurity,
): string {
  return JSON.stringify(
    GetAgentTemplateSecurity$outboundSchema.parse(getAgentTemplateSecurity),
  );
}

/** @internal */
export type GetAgentTemplateRequest$Outbound = {
  templateId: string;
};

/** @internal */
export const GetAgentTemplateRequest$outboundSchema: z.ZodMiniType<
  GetAgentTemplateRequest$Outbound,
  GetAgentTemplateRequest
> = z.object({
  templateId: z.string(),
});

export function getAgentTemplateRequestToJSON(
  getAgentTemplateRequest: GetAgentTemplateRequest,
): string {
  return JSON.stringify(
    GetAgentTemplateRequest$outboundSchema.parse(getAgentTemplateRequest),
  );
}
