/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetToolsetInstanceRequest = {
  instanceId: string;
};

/** @internal */
export type GetToolsetInstanceRequest$Outbound = {
  instanceId: string;
};

/** @internal */
export const GetToolsetInstanceRequest$outboundSchema: z.ZodMiniType<
  GetToolsetInstanceRequest$Outbound,
  GetToolsetInstanceRequest
> = z.object({
  instanceId: z.string(),
});

export function getToolsetInstanceRequestToJSON(
  getToolsetInstanceRequest: GetToolsetInstanceRequest,
): string {
  return JSON.stringify(
    GetToolsetInstanceRequest$outboundSchema.parse(getToolsetInstanceRequest),
  );
}
