/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type GetFrontendPublicUrlSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2 | undefined;
};

/** @internal */
export type GetFrontendPublicUrlSecurity$Outbound = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2$Outbound | undefined;
};

/** @internal */
export const GetFrontendPublicUrlSecurity$outboundSchema: z.ZodMiniType<
  GetFrontendPublicUrlSecurity$Outbound,
  GetFrontendPublicUrlSecurity
> = z.object({
  bearerAuth: z.optional(z.string()),
  oauth2: z.optional(models.SchemeOauth2$outboundSchema),
});

export function getFrontendPublicUrlSecurityToJSON(
  getFrontendPublicUrlSecurity: GetFrontendPublicUrlSecurity,
): string {
  return JSON.stringify(
    GetFrontendPublicUrlSecurity$outboundSchema.parse(
      getFrontendPublicUrlSecurity,
    ),
  );
}
