/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type GetSMTPConfigSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2 | undefined;
};

/** @internal */
export type GetSMTPConfigSecurity$Outbound = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2$Outbound | undefined;
};

/** @internal */
export const GetSMTPConfigSecurity$outboundSchema: z.ZodMiniType<
  GetSMTPConfigSecurity$Outbound,
  GetSMTPConfigSecurity
> = z.object({
  bearerAuth: z.optional(z.string()),
  oauth2: z.optional(models.SchemeOauth2$outboundSchema),
});

export function getSMTPConfigSecurityToJSON(
  getSMTPConfigSecurity: GetSMTPConfigSecurity,
): string {
  return JSON.stringify(
    GetSMTPConfigSecurity$outboundSchema.parse(getSMTPConfigSecurity),
  );
}
