/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetAllUsersWithGroupsData = {};

/**
 * Users with group data retrieved successfully
 */
export type GetAllUsersWithGroupsResponse = {
  success?: boolean | undefined;
  data?: Array<GetAllUsersWithGroupsData> | undefined;
};

/** @internal */
export const GetAllUsersWithGroupsData$inboundSchema: z.ZodMiniType<
  GetAllUsersWithGroupsData,
  unknown
> = z.object({});

export function getAllUsersWithGroupsDataFromJSON(
  jsonString: string,
): SafeParseResult<GetAllUsersWithGroupsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllUsersWithGroupsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllUsersWithGroupsData' from JSON`,
  );
}

/** @internal */
export const GetAllUsersWithGroupsResponse$inboundSchema: z.ZodMiniType<
  GetAllUsersWithGroupsResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(
    z.array(z.lazy(() => GetAllUsersWithGroupsData$inboundSchema)),
  ),
});

export function getAllUsersWithGroupsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAllUsersWithGroupsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllUsersWithGroupsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllUsersWithGroupsResponse' from JSON`,
  );
}
