/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type GetArchivedConversationsSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2 | undefined;
};

/** @internal */
export type GetArchivedConversationsSecurity$Outbound = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2$Outbound | undefined;
};

/** @internal */
export const GetArchivedConversationsSecurity$outboundSchema: z.ZodMiniType<
  GetArchivedConversationsSecurity$Outbound,
  GetArchivedConversationsSecurity
> = z.object({
  bearerAuth: z.optional(z.string()),
  oauth2: z.optional(models.SchemeOauth2$outboundSchema),
});

export function getArchivedConversationsSecurityToJSON(
  getArchivedConversationsSecurity: GetArchivedConversationsSecurity,
): string {
  return JSON.stringify(
    GetArchivedConversationsSecurity$outboundSchema.parse(
      getArchivedConversationsSecurity,
    ),
  );
}
