/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const HandleMCPRequestServerList = [
  "https://{instance_url}",
] as const;

export const JsonrpcRequest = {
  TwoDot0: "2.0",
} as const;
export type JsonrpcRequest = ClosedEnum<typeof JsonrpcRequest>;

export type IdRequest = string | number;

export type Params = {};

/**
 * JSON-RPC 2.0 request object
 */
export type HandleMCPRequestRequest = {
  jsonrpc: JsonrpcRequest;
  id?: string | number | undefined;
  /**
   * MCP method (e.g. initialize, tools/list, tools/call)
   */
  method: string;
  params?: Params | undefined;
};

export const JsonrpcResponse = {
  TwoDot0: "2.0",
} as const;
export type JsonrpcResponse = ClosedEnum<typeof JsonrpcResponse>;

export type IdResponse = string | number;

export type Result = {};

export type ErrorT = {
  code?: number | undefined;
  message?: string | undefined;
};

/**
 * JSON-RPC 2.0 response
 */
export type HandleMCPRequestResponse = {
  jsonrpc?: JsonrpcResponse | undefined;
  id?: string | number | undefined;
  result?: Result | undefined;
  error?: ErrorT | undefined;
};

/** @internal */
export const JsonrpcRequest$outboundSchema: z.ZodMiniEnum<
  typeof JsonrpcRequest
> = z.enum(JsonrpcRequest);

/** @internal */
export type IdRequest$Outbound = string | number;

/** @internal */
export const IdRequest$outboundSchema: z.ZodMiniType<
  IdRequest$Outbound,
  IdRequest
> = smartUnion([z.string(), z.int()]);

export function idRequestToJSON(idRequest: IdRequest): string {
  return JSON.stringify(IdRequest$outboundSchema.parse(idRequest));
}

/** @internal */
export type Params$Outbound = {};

/** @internal */
export const Params$outboundSchema: z.ZodMiniType<Params$Outbound, Params> = z
  .object({});

export function paramsToJSON(params: Params): string {
  return JSON.stringify(Params$outboundSchema.parse(params));
}

/** @internal */
export type HandleMCPRequestRequest$Outbound = {
  jsonrpc: string;
  id?: string | number | undefined;
  method: string;
  params?: Params$Outbound | undefined;
};

/** @internal */
export const HandleMCPRequestRequest$outboundSchema: z.ZodMiniType<
  HandleMCPRequestRequest$Outbound,
  HandleMCPRequestRequest
> = z.object({
  jsonrpc: JsonrpcRequest$outboundSchema,
  id: z.optional(smartUnion([z.string(), z.int()])),
  method: z.string(),
  params: z.optional(z.lazy(() => Params$outboundSchema)),
});

export function handleMCPRequestRequestToJSON(
  handleMCPRequestRequest: HandleMCPRequestRequest,
): string {
  return JSON.stringify(
    HandleMCPRequestRequest$outboundSchema.parse(handleMCPRequestRequest),
  );
}

/** @internal */
export const JsonrpcResponse$inboundSchema: z.ZodMiniEnum<
  typeof JsonrpcResponse
> = z.enum(JsonrpcResponse);

/** @internal */
export const IdResponse$inboundSchema: z.ZodMiniType<IdResponse, unknown> =
  smartUnion([types.string(), types.number()]);

export function idResponseFromJSON(
  jsonString: string,
): SafeParseResult<IdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdResponse' from JSON`,
  );
}

/** @internal */
export const Result$inboundSchema: z.ZodMiniType<Result, unknown> = z.object(
  {},
);

export function resultFromJSON(
  jsonString: string,
): SafeParseResult<Result, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Result$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Result' from JSON`,
  );
}

/** @internal */
export const ErrorT$inboundSchema: z.ZodMiniType<ErrorT, unknown> = z.object({
  code: types.optional(types.number()),
  message: types.optional(types.string()),
});

export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}

/** @internal */
export const HandleMCPRequestResponse$inboundSchema: z.ZodMiniType<
  HandleMCPRequestResponse,
  unknown
> = z.object({
  jsonrpc: types.optional(JsonrpcResponse$inboundSchema),
  id: types.optional(smartUnion([types.string(), types.number()])),
  result: types.optional(z.lazy(() => Result$inboundSchema)),
  error: types.optional(z.lazy(() => ErrorT$inboundSchema)),
});

export function handleMCPRequestResponseFromJSON(
  jsonString: string,
): SafeParseResult<HandleMCPRequestResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HandleMCPRequestResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HandleMCPRequestResponse' from JSON`,
  );
}
