/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListProjectMembersRequest = {
  projectId: string;
};

/**
 * Project member list (excludes the implicit owner)
 */
export type ListProjectMembersResponse = {
  members?: Array<models.ProjectMember> | undefined;
};

/** @internal */
export type ListProjectMembersRequest$Outbound = {
  projectId: string;
};

/** @internal */
export const ListProjectMembersRequest$outboundSchema: z.ZodMiniType<
  ListProjectMembersRequest$Outbound,
  ListProjectMembersRequest
> = z.object({
  projectId: z.string(),
});

export function listProjectMembersRequestToJSON(
  listProjectMembersRequest: ListProjectMembersRequest,
): string {
  return JSON.stringify(
    ListProjectMembersRequest$outboundSchema.parse(listProjectMembersRequest),
  );
}

/** @internal */
export const ListProjectMembersResponse$inboundSchema: z.ZodMiniType<
  ListProjectMembersResponse,
  unknown
> = z.object({
  members: types.optional(z.array(models.ProjectMember$inboundSchema)),
});

export function listProjectMembersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListProjectMembersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProjectMembersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProjectMembersResponse' from JSON`,
  );
}
