/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListActiveConnectorsSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2 | undefined;
};

/**
 * Active connectors retrieved
 */
export type ListActiveConnectorsResponse = {
  success?: boolean | undefined;
  connectors?: Array<models.ConnectorInstance> | undefined;
};

/** @internal */
export type ListActiveConnectorsSecurity$Outbound = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2$Outbound | undefined;
};

/** @internal */
export const ListActiveConnectorsSecurity$outboundSchema: z.ZodMiniType<
  ListActiveConnectorsSecurity$Outbound,
  ListActiveConnectorsSecurity
> = z.object({
  bearerAuth: z.optional(z.string()),
  oauth2: z.optional(models.SchemeOauth2$outboundSchema),
});

export function listActiveConnectorsSecurityToJSON(
  listActiveConnectorsSecurity: ListActiveConnectorsSecurity,
): string {
  return JSON.stringify(
    ListActiveConnectorsSecurity$outboundSchema.parse(
      listActiveConnectorsSecurity,
    ),
  );
}

/** @internal */
export const ListActiveConnectorsResponse$inboundSchema: z.ZodMiniType<
  ListActiveConnectorsResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  connectors: types.optional(z.array(models.ConnectorInstance$inboundSchema)),
});

export function listActiveConnectorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListActiveConnectorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListActiveConnectorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListActiveConnectorsResponse' from JSON`,
  );
}
