/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type LookupRecordByIdentifierRequest = {
  /**
   * The reference(s) to resolve: a URL, an issue key such as `PA-1787`, or a bare external system ID. Repeat the parameter to batch: `?identifiers=PA-1787&identifiers=PA-1788`. Maximum 10.
   */
  identifiers: Array<string>;
  /**
   * Optional hint that prioritises resolution order, e.g. `JIRA`, `CONFLUENCE`, `DRIVE`, `SLACK`. Allowed values are the `ConnectorNameEnum` values. It cannot widen the search beyond the connectors the caller can already access. Useful on a retry when a lookup came back empty.
   */
  connectorName?: models.ConnectorNameEnum | undefined;
};

/** @internal */
export type LookupRecordByIdentifierRequest$Outbound = {
  identifiers: Array<string>;
  connectorName?: string | undefined;
};

/** @internal */
export const LookupRecordByIdentifierRequest$outboundSchema: z.ZodMiniType<
  LookupRecordByIdentifierRequest$Outbound,
  LookupRecordByIdentifierRequest
> = z.object({
  identifiers: z.array(z.string()),
  connectorName: z.optional(models.ConnectorNameEnum$outboundSchema),
});

export function lookupRecordByIdentifierRequestToJSON(
  lookupRecordByIdentifierRequest: LookupRecordByIdentifierRequest,
): string {
  return JSON.stringify(
    LookupRecordByIdentifierRequest$outboundSchema.parse(
      lookupRecordByIdentifierRequest,
    ),
  );
}
