/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type NavigateKnowledgeGraphRequest = {
  /**
   * The node to open. Take it from an `id` in a previous navigate or lookup response. Omit it entirely for the flat listing of everything reachable — the usual starting point. A URL or an issue key such as `PA-1787` also works: it is resolved to its record automatically.
   */
  nodeId?: string | undefined;
  /**
   * Page number, 1-indexed.
   */
  page?: number | undefined;
  /**
   * Children per page. The minimum is 50 — smaller values are rejected rather than silently raised.
   */
  limit?: number | undefined;
  /**
   * Levels of descendants to return in one call. Above 1, `rows` is a flat list of all descendants down to that level rather than only direct children, and each row carries its own `level`.
   */
  depth?: number | undefined;
  /**
   * Restrict children to these node types. Repeat the parameter for multiple types: `?nodeTypes=record&nodeTypes=folder`.
   */
  nodeTypes?: Array<string> | undefined;
  /**
   * Filter children by source creation time. ISO 8601 `YYYY-MM-DD`, or a full datetime that MUST carry a timezone offset — a naive datetime is rejected rather than assumed to be UTC.
   */
  createdAfter?: string | undefined;
  /**
   * Filter children by source creation time. `YYYY-MM-DD` is inclusive of the whole day.
   */
  createdBefore?: string | undefined;
  /**
   * Filter children by source modification time.
   */
  modifiedAfter?: string | undefined;
  /**
   * Filter children by source modification time.
   */
  modifiedBefore?: string | undefined;
};

/** @internal */
export type NavigateKnowledgeGraphRequest$Outbound = {
  nodeId?: string | undefined;
  page: number;
  limit: number;
  depth: number;
  nodeTypes?: Array<string> | undefined;
  createdAfter?: string | undefined;
  createdBefore?: string | undefined;
  modifiedAfter?: string | undefined;
  modifiedBefore?: string | undefined;
};

/** @internal */
export const NavigateKnowledgeGraphRequest$outboundSchema: z.ZodMiniType<
  NavigateKnowledgeGraphRequest$Outbound,
  NavigateKnowledgeGraphRequest
> = z.object({
  nodeId: z.optional(z.string()),
  page: z._default(z.int(), 1),
  limit: z._default(z.int(), 50),
  depth: z._default(z.int(), 1),
  nodeTypes: z.optional(z.array(z.string())),
  createdAfter: z.optional(z.string()),
  createdBefore: z.optional(z.string()),
  modifiedAfter: z.optional(z.string()),
  modifiedBefore: z.optional(z.string()),
});

export function navigateKnowledgeGraphRequestToJSON(
  navigateKnowledgeGraphRequest: NavigateKnowledgeGraphRequest,
): string {
  return JSON.stringify(
    NavigateKnowledgeGraphRequest$outboundSchema.parse(
      navigateKnowledgeGraphRequest,
    ),
  );
}
