/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type RegenerateAnswerRequest = {
  conversationId: string;
  /**
   * ID of the message to regenerate response for
   */
  messageId: string;
  /**
   * Request payload
   */
  body?: models.RegenerateRequest | undefined;
};

/** @internal */
export type RegenerateAnswerRequest$Outbound = {
  conversationId: string;
  messageId: string;
  body?: models.RegenerateRequest$Outbound | undefined;
};

/** @internal */
export const RegenerateAnswerRequest$outboundSchema: z.ZodMiniType<
  RegenerateAnswerRequest$Outbound,
  RegenerateAnswerRequest
> = z.object({
  conversationId: z.string(),
  messageId: z.string(),
  body: z.optional(models.RegenerateRequest$outboundSchema),
});

export function regenerateAnswerRequestToJSON(
  regenerateAnswerRequest: RegenerateAnswerRequest,
): string {
  return JSON.stringify(
    RegenerateAnswerRequest$outboundSchema.parse(regenerateAnswerRequest),
  );
}
