/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Request payload
 */
export type RemoveUserFromTeamRequestBody = {
  userId?: string | undefined;
};

export type RemoveUserFromTeamRequest = {
  teamId: string;
  /**
   * Request payload
   */
  body: RemoveUserFromTeamRequestBody;
};

/**
 * User removed from team successfully
 */
export type RemoveUserFromTeamResponse = {
  message?: string | undefined;
};

/** @internal */
export type RemoveUserFromTeamRequestBody$Outbound = {
  userId?: string | undefined;
};

/** @internal */
export const RemoveUserFromTeamRequestBody$outboundSchema: z.ZodMiniType<
  RemoveUserFromTeamRequestBody$Outbound,
  RemoveUserFromTeamRequestBody
> = z.object({
  userId: z.optional(z.string()),
});

export function removeUserFromTeamRequestBodyToJSON(
  removeUserFromTeamRequestBody: RemoveUserFromTeamRequestBody,
): string {
  return JSON.stringify(
    RemoveUserFromTeamRequestBody$outboundSchema.parse(
      removeUserFromTeamRequestBody,
    ),
  );
}

/** @internal */
export type RemoveUserFromTeamRequest$Outbound = {
  teamId: string;
  body: RemoveUserFromTeamRequestBody$Outbound;
};

/** @internal */
export const RemoveUserFromTeamRequest$outboundSchema: z.ZodMiniType<
  RemoveUserFromTeamRequest$Outbound,
  RemoveUserFromTeamRequest
> = z.object({
  teamId: z.string(),
  body: z.lazy(() => RemoveUserFromTeamRequestBody$outboundSchema),
});

export function removeUserFromTeamRequestToJSON(
  removeUserFromTeamRequest: RemoveUserFromTeamRequest,
): string {
  return JSON.stringify(
    RemoveUserFromTeamRequest$outboundSchema.parse(removeUserFromTeamRequest),
  );
}

/** @internal */
export const RemoveUserFromTeamResponse$inboundSchema: z.ZodMiniType<
  RemoveUserFromTeamResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
});

export function removeUserFromTeamResponseFromJSON(
  jsonString: string,
): SafeParseResult<RemoveUserFromTeamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveUserFromTeamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveUserFromTeamResponse' from JSON`,
  );
}
