/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * Request payload
 */
export type ResetPasswordRequest = {
  currentPassword: string;
  newPassword: string;
  /**
   * Cloudflare Turnstile CAPTCHA token (required when Turnstile is configured server-side)
   */
  cfTurnstileResponse?: string | undefined;
};

/** @internal */
export type ResetPasswordRequest$Outbound = {
  currentPassword: string;
  newPassword: string;
  "cf-turnstile-response"?: string | undefined;
};

/** @internal */
export const ResetPasswordRequest$outboundSchema: z.ZodMiniType<
  ResetPasswordRequest$Outbound,
  ResetPasswordRequest
> = z.pipe(
  z.object({
    currentPassword: z.string(),
    newPassword: z.string(),
    cfTurnstileResponse: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      cfTurnstileResponse: "cf-turnstile-response",
    });
  }),
);

export function resetPasswordRequestToJSON(
  resetPasswordRequest: ResetPasswordRequest,
): string {
  return JSON.stringify(
    ResetPasswordRequest$outboundSchema.parse(resetPasswordRequest),
  );
}
