/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Request payload
 */
export type ResetPasswordRequest = {
  currentPassword: string;
  newPassword: string;
};

/**
 * Password reset successfully
 */
export type ResetPasswordResponse = {
  message?: string | undefined;
};

/** @internal */
export type ResetPasswordRequest$Outbound = {
  currentPassword: string;
  newPassword: string;
};

/** @internal */
export const ResetPasswordRequest$outboundSchema: z.ZodMiniType<
  ResetPasswordRequest$Outbound,
  ResetPasswordRequest
> = z.object({
  currentPassword: z.string(),
  newPassword: z.string(),
});

export function resetPasswordRequestToJSON(
  resetPasswordRequest: ResetPasswordRequest,
): string {
  return JSON.stringify(
    ResetPasswordRequest$outboundSchema.parse(resetPasswordRequest),
  );
}

/** @internal */
export const ResetPasswordResponse$inboundSchema: z.ZodMiniType<
  ResetPasswordResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
});

export function resetPasswordResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResetPasswordResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResetPasswordResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResetPasswordResponse' from JSON`,
  );
}
