/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ResumeCrawlingJobRequest = {
  connector: string;
  connectorId: string;
};

/**
 * Crawling job resumed
 */
export type ResumeCrawlingJobResponse = {
  message?: string | undefined;
};

/** @internal */
export type ResumeCrawlingJobRequest$Outbound = {
  connector: string;
  connectorId: string;
};

/** @internal */
export const ResumeCrawlingJobRequest$outboundSchema: z.ZodMiniType<
  ResumeCrawlingJobRequest$Outbound,
  ResumeCrawlingJobRequest
> = z.object({
  connector: z.string(),
  connectorId: z.string(),
});

export function resumeCrawlingJobRequestToJSON(
  resumeCrawlingJobRequest: ResumeCrawlingJobRequest,
): string {
  return JSON.stringify(
    ResumeCrawlingJobRequest$outboundSchema.parse(resumeCrawlingJobRequest),
  );
}

/** @internal */
export const ResumeCrawlingJobResponse$inboundSchema: z.ZodMiniType<
  ResumeCrawlingJobResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
});

export function resumeCrawlingJobResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResumeCrawlingJobResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResumeCrawlingJobResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResumeCrawlingJobResponse' from JSON`,
  );
}
