/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type SetAzureAdAuthConfigSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2 | undefined;
};

/** @internal */
export type SetAzureAdAuthConfigSecurity$Outbound = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2$Outbound | undefined;
};

/** @internal */
export const SetAzureAdAuthConfigSecurity$outboundSchema: z.ZodMiniType<
  SetAzureAdAuthConfigSecurity$Outbound,
  SetAzureAdAuthConfigSecurity
> = z.object({
  bearerAuth: z.optional(z.string()),
  oauth2: z.optional(models.SchemeOauth2$outboundSchema),
});

export function setAzureAdAuthConfigSecurityToJSON(
  setAzureAdAuthConfigSecurity: SetAzureAdAuthConfigSecurity,
): string {
  return JSON.stringify(
    SetAzureAdAuthConfigSecurity$outboundSchema.parse(
      setAzureAdAuthConfigSecurity,
    ),
  );
}
