/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type SetMicrosoftAuthConfigSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2 | undefined;
};

/** @internal */
export type SetMicrosoftAuthConfigSecurity$Outbound = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2$Outbound | undefined;
};

/** @internal */
export const SetMicrosoftAuthConfigSecurity$outboundSchema: z.ZodMiniType<
  SetMicrosoftAuthConfigSecurity$Outbound,
  SetMicrosoftAuthConfigSecurity
> = z.object({
  bearerAuth: z.optional(z.string()),
  oauth2: z.optional(models.SchemeOauth2$outboundSchema),
});

export function setMicrosoftAuthConfigSecurityToJSON(
  setMicrosoftAuthConfigSecurity: SetMicrosoftAuthConfigSecurity,
): string {
  return JSON.stringify(
    SetMicrosoftAuthConfigSecurity$outboundSchema.parse(
      setMicrosoftAuthConfigSecurity,
    ),
  );
}
