/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Request payload
 */
export type SetUpAuthConfigRequest = {};

/**
 * Auth configuration set up successfully
 */
export type SetUpAuthConfigResponse = {
  message?: string | undefined;
};

/** @internal */
export type SetUpAuthConfigRequest$Outbound = {};

/** @internal */
export const SetUpAuthConfigRequest$outboundSchema: z.ZodMiniType<
  SetUpAuthConfigRequest$Outbound,
  SetUpAuthConfigRequest
> = z.object({});

export function setUpAuthConfigRequestToJSON(
  setUpAuthConfigRequest: SetUpAuthConfigRequest,
): string {
  return JSON.stringify(
    SetUpAuthConfigRequest$outboundSchema.parse(setUpAuthConfigRequest),
  );
}

/** @internal */
export const SetUpAuthConfigResponse$inboundSchema: z.ZodMiniType<
  SetUpAuthConfigResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
});

export function setUpAuthConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<SetUpAuthConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetUpAuthConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetUpAuthConfigResponse' from JSON`,
  );
}
