/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Request payload
 */
export type SetGoogleWorkspaceOauthConfigRequest = {};

/**
 * Google Workspace OAuth config saved
 */
export type SetGoogleWorkspaceOauthConfigResponse = {
  message?: string | undefined;
};

/** @internal */
export type SetGoogleWorkspaceOauthConfigRequest$Outbound = {};

/** @internal */
export const SetGoogleWorkspaceOauthConfigRequest$outboundSchema: z.ZodMiniType<
  SetGoogleWorkspaceOauthConfigRequest$Outbound,
  SetGoogleWorkspaceOauthConfigRequest
> = z.object({});

export function setGoogleWorkspaceOauthConfigRequestToJSON(
  setGoogleWorkspaceOauthConfigRequest: SetGoogleWorkspaceOauthConfigRequest,
): string {
  return JSON.stringify(
    SetGoogleWorkspaceOauthConfigRequest$outboundSchema.parse(
      setGoogleWorkspaceOauthConfigRequest,
    ),
  );
}

/** @internal */
export const SetGoogleWorkspaceOauthConfigResponse$inboundSchema: z.ZodMiniType<
  SetGoogleWorkspaceOauthConfigResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
});

export function setGoogleWorkspaceOauthConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<SetGoogleWorkspaceOauthConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SetGoogleWorkspaceOauthConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetGoogleWorkspaceOauthConfigResponse' from JSON`,
  );
}
