/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type SetCustomSystemPromptSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2 | undefined;
};

/** @internal */
export type SetCustomSystemPromptSecurity$Outbound = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2$Outbound | undefined;
};

/** @internal */
export const SetCustomSystemPromptSecurity$outboundSchema: z.ZodMiniType<
  SetCustomSystemPromptSecurity$Outbound,
  SetCustomSystemPromptSecurity
> = z.object({
  bearerAuth: z.optional(z.string()),
  oauth2: z.optional(models.SchemeOauth2$outboundSchema),
});

export function setCustomSystemPromptSecurityToJSON(
  setCustomSystemPromptSecurity: SetCustomSystemPromptSecurity,
): string {
  return JSON.stringify(
    SetCustomSystemPromptSecurity$outboundSchema.parse(
      setCustomSystemPromptSecurity,
    ),
  );
}
