/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type SetSsoAuthConfigSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2 | undefined;
};

/** @internal */
export type SetSsoAuthConfigSecurity$Outbound = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2$Outbound | undefined;
};

/** @internal */
export const SetSsoAuthConfigSecurity$outboundSchema: z.ZodMiniType<
  SetSsoAuthConfigSecurity$Outbound,
  SetSsoAuthConfigSecurity
> = z.object({
  bearerAuth: z.optional(z.string()),
  oauth2: z.optional(models.SchemeOauth2$outboundSchema),
});

export function setSsoAuthConfigSecurityToJSON(
  setSsoAuthConfigSecurity: SetSsoAuthConfigSecurity,
): string {
  return JSON.stringify(
    SetSsoAuthConfigSecurity$outboundSchema.parse(setSsoAuthConfigSecurity),
  );
}
