/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Request payload
 */
export type SetAtlassianOauthConfigRequest = {};

/**
 * Atlassian config saved
 */
export type SetAtlassianOauthConfigResponse = {
  message?: string | undefined;
};

/** @internal */
export type SetAtlassianOauthConfigRequest$Outbound = {};

/** @internal */
export const SetAtlassianOauthConfigRequest$outboundSchema: z.ZodMiniType<
  SetAtlassianOauthConfigRequest$Outbound,
  SetAtlassianOauthConfigRequest
> = z.object({});

export function setAtlassianOauthConfigRequestToJSON(
  setAtlassianOauthConfigRequest: SetAtlassianOauthConfigRequest,
): string {
  return JSON.stringify(
    SetAtlassianOauthConfigRequest$outboundSchema.parse(
      setAtlassianOauthConfigRequest,
    ),
  );
}

/** @internal */
export const SetAtlassianOauthConfigResponse$inboundSchema: z.ZodMiniType<
  SetAtlassianOauthConfigResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
});

export function setAtlassianOauthConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<SetAtlassianOauthConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetAtlassianOauthConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetAtlassianOauthConfigResponse' from JSON`,
  );
}
