/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type SetOAuthConfigSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2 | undefined;
};

/** @internal */
export type SetOAuthConfigSecurity$Outbound = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2$Outbound | undefined;
};

/** @internal */
export const SetOAuthConfigSecurity$outboundSchema: z.ZodMiniType<
  SetOAuthConfigSecurity$Outbound,
  SetOAuthConfigSecurity
> = z.object({
  bearerAuth: z.optional(z.string()),
  oauth2: z.optional(models.SchemeOauth2$outboundSchema),
});

export function setOAuthConfigSecurityToJSON(
  setOAuthConfigSecurity: SetOAuthConfigSecurity,
): string {
  return JSON.stringify(
    SetOAuthConfigSecurity$outboundSchema.parse(setOAuthConfigSecurity),
  );
}
