/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type ShareAgentSecurity = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2 | undefined;
};

export type ShareAgentRequest = {
  agentKey: string;
  /**
   * Request body for Share agent
   */
  body: models.ShareRequest;
};

/** @internal */
export type ShareAgentSecurity$Outbound = {
  bearerAuth?: string | undefined;
  oauth2?: models.SchemeOauth2$Outbound | undefined;
};

/** @internal */
export const ShareAgentSecurity$outboundSchema: z.ZodMiniType<
  ShareAgentSecurity$Outbound,
  ShareAgentSecurity
> = z.object({
  bearerAuth: z.optional(z.string()),
  oauth2: z.optional(models.SchemeOauth2$outboundSchema),
});

export function shareAgentSecurityToJSON(
  shareAgentSecurity: ShareAgentSecurity,
): string {
  return JSON.stringify(
    ShareAgentSecurity$outboundSchema.parse(shareAgentSecurity),
  );
}

/** @internal */
export type ShareAgentRequest$Outbound = {
  agentKey: string;
  body: models.ShareRequest$Outbound;
};

/** @internal */
export const ShareAgentRequest$outboundSchema: z.ZodMiniType<
  ShareAgentRequest$Outbound,
  ShareAgentRequest
> = z.object({
  agentKey: z.string(),
  body: models.ShareRequest$outboundSchema,
});

export function shareAgentRequestToJSON(
  shareAgentRequest: ShareAgentRequest,
): string {
  return JSON.stringify(
    ShareAgentRequest$outboundSchema.parse(shareAgentRequest),
  );
}
