/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type StreamAgentConversationRequest = {
  /**
   * Stable key identifying the agent that owns this conversation.
   */
  agentKey: string;
  /**
   * Initial turn payload for the new agent conversation stream.
   */
  body: models.AgentStreamCreateConversationRequest;
};

/** @internal */
export type StreamAgentConversationRequest$Outbound = {
  agentKey: string;
  body: models.AgentStreamCreateConversationRequest$Outbound;
};

/** @internal */
export const StreamAgentConversationRequest$outboundSchema: z.ZodMiniType<
  StreamAgentConversationRequest$Outbound,
  StreamAgentConversationRequest
> = z.object({
  agentKey: z.string(),
  body: models.AgentStreamCreateConversationRequest$outboundSchema,
});

export function streamAgentConversationRequestToJSON(
  streamAgentConversationRequest: StreamAgentConversationRequest,
): string {
  return JSON.stringify(
    StreamAgentConversationRequest$outboundSchema.parse(
      streamAgentConversationRequest,
    ),
  );
}
