/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Request payload
 */
export type UpdateTeamUsersPermissionsRequestBody = {};

export type UpdateTeamUsersPermissionsRequest = {
  teamId: string;
  /**
   * Request payload
   */
  body: UpdateTeamUsersPermissionsRequestBody;
};

/**
 * Permissions updated successfully
 */
export type UpdateTeamUsersPermissionsResponse = {
  message?: string | undefined;
};

/** @internal */
export type UpdateTeamUsersPermissionsRequestBody$Outbound = {};

/** @internal */
export const UpdateTeamUsersPermissionsRequestBody$outboundSchema:
  z.ZodMiniType<
    UpdateTeamUsersPermissionsRequestBody$Outbound,
    UpdateTeamUsersPermissionsRequestBody
  > = z.object({});

export function updateTeamUsersPermissionsRequestBodyToJSON(
  updateTeamUsersPermissionsRequestBody: UpdateTeamUsersPermissionsRequestBody,
): string {
  return JSON.stringify(
    UpdateTeamUsersPermissionsRequestBody$outboundSchema.parse(
      updateTeamUsersPermissionsRequestBody,
    ),
  );
}

/** @internal */
export type UpdateTeamUsersPermissionsRequest$Outbound = {
  teamId: string;
  body: UpdateTeamUsersPermissionsRequestBody$Outbound;
};

/** @internal */
export const UpdateTeamUsersPermissionsRequest$outboundSchema: z.ZodMiniType<
  UpdateTeamUsersPermissionsRequest$Outbound,
  UpdateTeamUsersPermissionsRequest
> = z.object({
  teamId: z.string(),
  body: z.lazy(() => UpdateTeamUsersPermissionsRequestBody$outboundSchema),
});

export function updateTeamUsersPermissionsRequestToJSON(
  updateTeamUsersPermissionsRequest: UpdateTeamUsersPermissionsRequest,
): string {
  return JSON.stringify(
    UpdateTeamUsersPermissionsRequest$outboundSchema.parse(
      updateTeamUsersPermissionsRequest,
    ),
  );
}

/** @internal */
export const UpdateTeamUsersPermissionsResponse$inboundSchema: z.ZodMiniType<
  UpdateTeamUsersPermissionsResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
});

export function updateTeamUsersPermissionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTeamUsersPermissionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateTeamUsersPermissionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTeamUsersPermissionsResponse' from JSON`,
  );
}
