/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Request payload
 */
export type UpdateEmailRequestBody = {
  email?: string | undefined;
};

export type UpdateEmailRequest = {
  id: string;
  /**
   * Request payload
   */
  body: UpdateEmailRequestBody;
};

/** @internal */
export type UpdateEmailRequestBody$Outbound = {
  email?: string | undefined;
};

/** @internal */
export const UpdateEmailRequestBody$outboundSchema: z.ZodMiniType<
  UpdateEmailRequestBody$Outbound,
  UpdateEmailRequestBody
> = z.object({
  email: z.optional(z.string()),
});

export function updateEmailRequestBodyToJSON(
  updateEmailRequestBody: UpdateEmailRequestBody,
): string {
  return JSON.stringify(
    UpdateEmailRequestBody$outboundSchema.parse(updateEmailRequestBody),
  );
}

/** @internal */
export type UpdateEmailRequest$Outbound = {
  id: string;
  body: UpdateEmailRequestBody$Outbound;
};

/** @internal */
export const UpdateEmailRequest$outboundSchema: z.ZodMiniType<
  UpdateEmailRequest$Outbound,
  UpdateEmailRequest
> = z.object({
  id: z.string(),
  body: z.lazy(() => UpdateEmailRequestBody$outboundSchema),
});

export function updateEmailRequestToJSON(
  updateEmailRequest: UpdateEmailRequest,
): string {
  return JSON.stringify(
    UpdateEmailRequest$outboundSchema.parse(updateEmailRequest),
  );
}
