/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateAgentRequest = {
  /**
   * Unique agent identifier
   */
  agentKey: string;
  /**
   * Partial agent configuration fields to update
   */
  body: models.AgentUpdateRequest;
};

/** @internal */
export type UpdateAgentRequest$Outbound = {
  agentKey: string;
  body: models.AgentUpdateRequest$Outbound;
};

/** @internal */
export const UpdateAgentRequest$outboundSchema: z.ZodMiniType<
  UpdateAgentRequest$Outbound,
  UpdateAgentRequest
> = z.object({
  agentKey: z.string(),
  body: models.AgentUpdateRequest$outboundSchema,
});

export function updateAgentRequestToJSON(
  updateAgentRequest: UpdateAgentRequest,
): string {
  return JSON.stringify(
    UpdateAgentRequest$outboundSchema.parse(updateAgentRequest),
  );
}
