/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

/**
 * Request payload
 */
export type UpdateAuthMethodRequest = {
  /**
   * Authentication steps to set for the organization (1-3 steps)
   */
  authMethod: Array<models.AuthStep>;
};

/** @internal */
export type UpdateAuthMethodRequest$Outbound = {
  authMethod: Array<models.AuthStep$Outbound>;
};

/** @internal */
export const UpdateAuthMethodRequest$outboundSchema: z.ZodMiniType<
  UpdateAuthMethodRequest$Outbound,
  UpdateAuthMethodRequest
> = z.object({
  authMethod: z.array(models.AuthStep$outboundSchema),
});

export function updateAuthMethodRequestToJSON(
  updateAuthMethodRequest: UpdateAuthMethodRequest,
): string {
  return JSON.stringify(
    UpdateAuthMethodRequest$outboundSchema.parse(updateAuthMethodRequest),
  );
}
