/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { blobLikeSchema } from "../../types/blobs.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type UploadNextVersionDocumentFile = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type UploadNextVersionDocumentRequestBody = {
  file?: UploadNextVersionDocumentFile | Blob | undefined;
};

export type UploadNextVersionDocumentRequest = {
  documentId: string;
  body: UploadNextVersionDocumentRequestBody;
};

/**
 * New version uploaded successfully
 */
export type UploadNextVersionDocumentResponse = {
  message?: string | undefined;
};

/** @internal */
export type UploadNextVersionDocumentFile$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const UploadNextVersionDocumentFile$outboundSchema: z.ZodMiniType<
  UploadNextVersionDocumentFile$Outbound,
  UploadNextVersionDocumentFile
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.custom<Blob>(x => x instanceof Blob),
    z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
    z.custom<Uint8Array>(x => x instanceof Uint8Array),
  ]),
});

export function uploadNextVersionDocumentFileToJSON(
  uploadNextVersionDocumentFile: UploadNextVersionDocumentFile,
): string {
  return JSON.stringify(
    UploadNextVersionDocumentFile$outboundSchema.parse(
      uploadNextVersionDocumentFile,
    ),
  );
}

/** @internal */
export type UploadNextVersionDocumentRequestBody$Outbound = {
  file?: UploadNextVersionDocumentFile$Outbound | Blob | undefined;
};

/** @internal */
export const UploadNextVersionDocumentRequestBody$outboundSchema: z.ZodMiniType<
  UploadNextVersionDocumentRequestBody$Outbound,
  UploadNextVersionDocumentRequestBody
> = z.object({
  file: z.optional(
    z.union([
      z.lazy(() => UploadNextVersionDocumentFile$outboundSchema),
      blobLikeSchema,
    ]),
  ),
});

export function uploadNextVersionDocumentRequestBodyToJSON(
  uploadNextVersionDocumentRequestBody: UploadNextVersionDocumentRequestBody,
): string {
  return JSON.stringify(
    UploadNextVersionDocumentRequestBody$outboundSchema.parse(
      uploadNextVersionDocumentRequestBody,
    ),
  );
}

/** @internal */
export type UploadNextVersionDocumentRequest$Outbound = {
  documentId: string;
  body: UploadNextVersionDocumentRequestBody$Outbound;
};

/** @internal */
export const UploadNextVersionDocumentRequest$outboundSchema: z.ZodMiniType<
  UploadNextVersionDocumentRequest$Outbound,
  UploadNextVersionDocumentRequest
> = z.object({
  documentId: z.string(),
  body: z.lazy(() => UploadNextVersionDocumentRequestBody$outboundSchema),
});

export function uploadNextVersionDocumentRequestToJSON(
  uploadNextVersionDocumentRequest: UploadNextVersionDocumentRequest,
): string {
  return JSON.stringify(
    UploadNextVersionDocumentRequest$outboundSchema.parse(
      uploadNextVersionDocumentRequest,
    ),
  );
}

/** @internal */
export const UploadNextVersionDocumentResponse$inboundSchema: z.ZodMiniType<
  UploadNextVersionDocumentResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
});

export function uploadNextVersionDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<UploadNextVersionDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadNextVersionDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadNextVersionDocumentResponse' from JSON`,
  );
}
