/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpsertProjectMembersRequest = {
  projectId: string;
  body: models.ProjectMembersUpsertRequest;
};

/**
 * Updated member list
 */
export type UpsertProjectMembersResponse = {
  members?: Array<models.ProjectMember> | undefined;
};

/** @internal */
export type UpsertProjectMembersRequest$Outbound = {
  projectId: string;
  body: models.ProjectMembersUpsertRequest$Outbound;
};

/** @internal */
export const UpsertProjectMembersRequest$outboundSchema: z.ZodMiniType<
  UpsertProjectMembersRequest$Outbound,
  UpsertProjectMembersRequest
> = z.object({
  projectId: z.string(),
  body: models.ProjectMembersUpsertRequest$outboundSchema,
});

export function upsertProjectMembersRequestToJSON(
  upsertProjectMembersRequest: UpsertProjectMembersRequest,
): string {
  return JSON.stringify(
    UpsertProjectMembersRequest$outboundSchema.parse(
      upsertProjectMembersRequest,
    ),
  );
}

/** @internal */
export const UpsertProjectMembersResponse$inboundSchema: z.ZodMiniType<
  UpsertProjectMembersResponse,
  unknown
> = z.object({
  members: types.optional(z.array(models.ProjectMember$inboundSchema)),
});

export function upsertProjectMembersResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpsertProjectMembersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpsertProjectMembersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpsertProjectMembersResponse' from JSON`,
  );
}
