/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { Conversation, Conversation$inboundSchema } from "./conversation.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type AddMessageResponseMeta = {
  /**
   * Request correlation id. Omitted when upstream middleware did
   *
   * @remarks
   * not set `req.context.requestId`.
   */
  requestId?: string | undefined;
  /**
   * Server timestamp when the response was sent.
   */
  timestamp: Date;
  /**
   * Total handler duration in milliseconds.
   */
  duration: number;
  /**
   * Same value as the top-level `recordsUsed`. Duplicated inside
   *
   * @remarks
   * `meta` for client convenience.
   */
  recordsUsed?: number | undefined;
};

/**
 * Envelope returned by `POST /conversations/{conversationId}/messages`.
 *
 * @remarks
 * Contains the updated conversation, the number of citation records used
 * to ground the AI response for this turn, and request metadata.
 */
export type AddMessageResponse = {
  /**
   * A conversation represents a chat session between a user and the AI.
   *
   * @remarks
   * Conversations maintain context across multiple messages and can be
   * shared, archived, and organized.
   */
  conversation: Conversation;
  /**
   * Number of citation records used to ground the AI response generated
   *
   * @remarks
   * for this turn.
   */
  recordsUsed: number;
  meta: AddMessageResponseMeta;
};

/** @internal */
export const AddMessageResponseMeta$inboundSchema: z.ZodMiniType<
  AddMessageResponseMeta,
  unknown
> = z.object({
  requestId: types.optional(types.string()),
  timestamp: types.date(),
  duration: types.number(),
  recordsUsed: types.optional(types.number()),
});

export function addMessageResponseMetaFromJSON(
  jsonString: string,
): SafeParseResult<AddMessageResponseMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddMessageResponseMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddMessageResponseMeta' from JSON`,
  );
}

/** @internal */
export const AddMessageResponse$inboundSchema: z.ZodMiniType<
  AddMessageResponse,
  unknown
> = z.object({
  conversation: Conversation$inboundSchema,
  recordsUsed: types.number(),
  meta: z.lazy(() => AddMessageResponseMeta$inboundSchema),
});

export function addMessageResponseFromJSON(
  jsonString: string,
): SafeParseResult<AddMessageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddMessageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddMessageResponse' from JSON`,
  );
}
