/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Address = {
  /**
   * Address line 1
   */
  addressLine1?: string | undefined;
  /**
   * City
   */
  city?: string | undefined;
  /**
   * State/Province
   */
  state?: string | undefined;
  /**
   * Postal/ZIP code
   */
  postCode?: string | undefined;
  /**
   * Country
   */
  country?: string | undefined;
};

/** @internal */
export const Address$inboundSchema: z.ZodMiniType<Address, unknown> = z.object({
  addressLine1: types.optional(types.string()),
  city: types.optional(types.string()),
  state: types.optional(types.string()),
  postCode: types.optional(types.string()),
  country: types.optional(types.string()),
});

export function addressFromJSON(
  jsonString: string,
): SafeParseResult<Address, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Address$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Address' from JSON`,
  );
}
