/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  AgentCreateKnowledge,
  AgentCreateKnowledge$Outbound,
  AgentCreateKnowledge$outboundSchema,
} from "./agent-create-knowledge.js";
import {
  AgentCreateModelEntryUnion,
  AgentCreateModelEntryUnion$Outbound,
  AgentCreateModelEntryUnion$outboundSchema,
} from "./agent-create-model-entry-union.js";
import {
  AgentCreateToolset,
  AgentCreateToolset$Outbound,
  AgentCreateToolset$outboundSchema,
} from "./agent-create-toolset.js";
import {
  AgentCreateWebSearchUnion,
  AgentCreateWebSearchUnion$Outbound,
  AgentCreateWebSearchUnion$outboundSchema,
} from "./agent-create-web-search-union.js";

export type AgentCreateRequest = {
  /**
   * Agent display name
   */
  name: string;
  /**
   * What the agent does
   */
  description?: string | undefined;
  /**
   * Initial greeting shown when conversation starts
   */
  startMessage?: string | undefined;
  /**
   * System instructions for the agent
   */
  systemPrompt?: string | undefined;
  /**
   * Additional agent execution instructions
   */
  instructions?: string | undefined;
  /**
   * Agent model configuration entries. The gateway requires at least one
   *
   * @remarks
   * object entry with `isReasoning: true`. String-only arrays are schema-valid
   * but rejected at runtime with HTTP 400.
   */
  models: Array<AgentCreateModelEntryUnion>;
  tags?: Array<string> | undefined;
  /**
   * Share agent with the organization
   */
  shareWithOrg?: boolean | undefined;
  /**
   * Create the agent as a service-account agent
   */
  isServiceAccount?: boolean | undefined;
  /**
   * Toolsets attached to the agent (instance-aware)
   */
  toolsets?: Array<AgentCreateToolset> | undefined;
  /**
   * Knowledge sources connected to the agent
   */
  knowledge?: Array<AgentCreateKnowledge> | undefined;
  /**
   * Accepted web-search attachment for `POST /agents/create`.
   *
   * @remarks
   * The gateway accepts either a provider string or an object with at least
   * a `provider` field.
   */
  webSearch?: AgentCreateWebSearchUnion | null | undefined;
};

/** @internal */
export type AgentCreateRequest$Outbound = {
  name: string;
  description?: string | undefined;
  startMessage?: string | undefined;
  systemPrompt?: string | undefined;
  instructions?: string | undefined;
  models: Array<AgentCreateModelEntryUnion$Outbound>;
  tags?: Array<string> | undefined;
  shareWithOrg: boolean;
  isServiceAccount: boolean;
  toolsets?: Array<AgentCreateToolset$Outbound> | undefined;
  knowledge?: Array<AgentCreateKnowledge$Outbound> | undefined;
  webSearch?: AgentCreateWebSearchUnion$Outbound | null | undefined;
};

/** @internal */
export const AgentCreateRequest$outboundSchema: z.ZodMiniType<
  AgentCreateRequest$Outbound,
  AgentCreateRequest
> = z.object({
  name: z.string(),
  description: z.optional(z.string()),
  startMessage: z.optional(z.string()),
  systemPrompt: z.optional(z.string()),
  instructions: z.optional(z.string()),
  models: z.array(AgentCreateModelEntryUnion$outboundSchema),
  tags: z.optional(z.array(z.string())),
  shareWithOrg: z._default(z.boolean(), false),
  isServiceAccount: z._default(z.boolean(), false),
  toolsets: z.optional(z.array(AgentCreateToolset$outboundSchema)),
  knowledge: z.optional(z.array(AgentCreateKnowledge$outboundSchema)),
  webSearch: z.optional(z.nullable(AgentCreateWebSearchUnion$outboundSchema)),
});

export function agentCreateRequestToJSON(
  agentCreateRequest: AgentCreateRequest,
): string {
  return JSON.stringify(
    AgentCreateRequest$outboundSchema.parse(agentCreateRequest),
  );
}
