/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const AgentRegenerateSSEEventEvent = {
  Connected: "connected",
  Status: "status",
  ToolCalls: "tool_calls",
  ToolCall: "tool_call",
  ToolSuccess: "tool_success",
  ToolError: "tool_error",
  ToolResult: "tool_result",
  ToolExecutionComplete: "tool_execution_complete",
  AnswerChunk: "answer_chunk",
  Restreaming: "restreaming",
  Metadata: "metadata",
  Complete: "complete",
  Error: "error",
} as const;
export type AgentRegenerateSSEEventEvent = OpenEnum<
  typeof AgentRegenerateSSEEventEvent
>;

/**
 * SSE event envelope for `POST /agents/{agentKey}/conversations/{conversationId}/message/{messageId}/regenerate`.
 *
 * @remarks
 *
 * Stable events:
 *
 * - `connected` confirms the stream is open.
 * - `complete` returns the updated conversation plus request metadata
 *   after the regenerated bot response is persisted.
 * - `error` returns a failure message. Conversation lookup failures,
 *   unauthorized conversation access, and regenerate rule failures such
 *   as "not the last message" are reported here after the stream starts.
 *
 * Other events are forwarded from the agent backend and should be
 * treated as informational updates.
 */
export type AgentRegenerateSSEEvent = {
  event?: AgentRegenerateSSEEventEvent | undefined;
  /**
   * JSON-encoded event payload. Shape depends on `event`.
   */
  data?: string | undefined;
};

/** @internal */
export const AgentRegenerateSSEEventEvent$inboundSchema: z.ZodMiniType<
  AgentRegenerateSSEEventEvent,
  unknown
> = openEnums.inboundSchema(AgentRegenerateSSEEventEvent);

/** @internal */
export const AgentRegenerateSSEEvent$inboundSchema: z.ZodMiniType<
  AgentRegenerateSSEEvent,
  unknown
> = z.object({
  event: types.optional(AgentRegenerateSSEEventEvent$inboundSchema),
  data: types.optional(types.string()),
});

export function agentRegenerateSSEEventFromJSON(
  jsonString: string,
): SafeParseResult<AgentRegenerateSSEEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentRegenerateSSEEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentRegenerateSSEEvent' from JSON`,
  );
}
