/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Request-scoped metadata returned by the archive route. `requestId` is
 *
 * @remarks
 * omitted when upstream middleware did not attach one.
 */
export type AgentConversationArchiveMeta = {
  requestId?: string | undefined;
  timestamp: Date;
  duration: number;
};

/** @internal */
export const AgentConversationArchiveMeta$inboundSchema: z.ZodMiniType<
  AgentConversationArchiveMeta,
  unknown
> = z.object({
  requestId: types.optional(types.string()),
  timestamp: types.date(),
  duration: types.number(),
});

export function agentConversationArchiveMetaFromJSON(
  jsonString: string,
): SafeParseResult<AgentConversationArchiveMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentConversationArchiveMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentConversationArchiveMeta' from JSON`,
  );
}
