/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AgentConversationDetailMessageCitation,
  AgentConversationDetailMessageCitation$inboundSchema,
} from "./agent-conversation-detail-message-citation.js";
import {
  AppliedFilters,
  AppliedFilters$inboundSchema,
} from "./applied-filters.js";
import {
  ChatAttachmentRef,
  ChatAttachmentRef$inboundSchema,
} from "./chat-attachment-ref.js";
import {
  ConversationModelInfo,
  ConversationModelInfo$inboundSchema,
} from "./conversation-model-info.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FollowUpQuestion,
  FollowUpQuestion$inboundSchema,
} from "./follow-up-question.js";
import {
  MessageFeedback,
  MessageFeedback$inboundSchema,
} from "./message-feedback.js";

export const AgentConversationDetailMessageMessageType = {
  UserQuery: "user_query",
  BotResponse: "bot_response",
  Error: "error",
  Feedback: "feedback",
  System: "system",
} as const;
export type AgentConversationDetailMessageMessageType = OpenEnum<
  typeof AgentConversationDetailMessageMessageType
>;

export const AgentConversationDetailMessageContentFormat = {
  Markdown: "MARKDOWN",
  Json: "JSON",
  Html: "HTML",
} as const;
export type AgentConversationDetailMessageContentFormat = OpenEnum<
  typeof AgentConversationDetailMessageContentFormat
>;

/**
 * AI confidence in the answer. Present only on `bot_response` messages,
 *
 * @remarks
 * and only when the model emitted a trailing confidence block.
 *
 * This field is now optional and nullable; it was previously always present and non-nullable. Treat a missing or `null` value as "no confidence reported" and guard before using it. Change effective in SDK v1.3.0 (v1.2.0 and earlier always populated it).
 */
export const Confidence = {
  VeryHigh: "Very High",
  High: "High",
  Medium: "Medium",
  Low: "Low",
  Unknown: "Unknown",
} as const;
/**
 * AI confidence in the answer. Present only on `bot_response` messages,
 *
 * @remarks
 * and only when the model emitted a trailing confidence block.
 *
 * This field is now optional and nullable; it was previously always present and non-nullable. Treat a missing or `null` value as "no confidence reported" and guard before using it. Change effective in SDK v1.3.0 (v1.2.0 and earlier always populated it).
 */
export type Confidence = OpenEnum<typeof Confidence>;

export type AgentConversationDetailMessageReferenceDatum = {
  /**
   * Display name shown to the user.
   */
  name?: string | undefined;
  /**
   * Technical identifier (numeric ID, UUID, etc.).
   */
  id?: string | undefined;
  /**
   * Item type (e.g. `project`, `issue`, `file`, `notebook`, `page`).
   */
  type?: string | undefined;
  /**
   * Source application (e.g. `jira`, `confluence`, `sharepoint`,
   *
   * @remarks
   * `slack`, `drive`, `gmail`).
   */
  app?: string | undefined;
  /**
   * URL to open the item in a browser.
   */
  webUrl?: string | undefined;
  /**
   * App-specific fields keyed by name (e.g. `key` for a Jira project,
   *
   * @remarks
   * `siteId` for a SharePoint document).
   */
  metadata?: { [k: string]: string } | undefined;
};

export type AgentConversationDetailMessageTool = {
  toolName?: string | undefined;
  toolResult?: any | undefined;
};

export type AgentConversationDetailMessageMetadata = {
  processingTimeMs?: number | undefined;
  modelVersion?: string | undefined;
  aiTransactionId?: string | undefined;
};

/**
 * Message shape returned by `GET /agents/{agentKey}/conversations/{conversationId}`.
 *
 * @remarks
 * The response spreads the stored message document and replaces
 * `citations` with populated citation objects.
 */
export type AgentConversationDetailMessage = {
  id?: string | undefined;
  messageType?: AgentConversationDetailMessageMessageType | undefined;
  content?: string | undefined;
  contentFormat?: AgentConversationDetailMessageContentFormat | undefined;
  citations?: Array<AgentConversationDetailMessageCitation> | undefined;
  /**
   * AI confidence in the answer. Present only on `bot_response` messages,
   *
   * @remarks
   * and only when the model emitted a trailing confidence block.
   *
   * This field is now optional and nullable; it was previously always present and non-nullable. Treat a missing or `null` value as "no confidence reported" and guard before using it. Change effective in SDK v1.3.0 (v1.2.0 and earlier always populated it).
   */
  confidence?: Confidence | null | undefined;
  followUpQuestions?: Array<FollowUpQuestion> | undefined;
  feedback?: Array<MessageFeedback> | undefined;
  /**
   * Reference identifiers surfaced from tool responses, used to scope
   *
   * @remarks
   * follow-up queries.
   */
  referenceData?:
    | Array<AgentConversationDetailMessageReferenceDatum>
    | undefined;
  /**
   * Files uploaded for this message turn (see
   *
   * @remarks
   * `POST /agents/{agentKey}/conversations/attachments/upload`).
   */
  attachments?: Array<ChatAttachmentRef> | undefined;
  /**
   * Tool call results invoked during this message turn.
   */
  tools?: Array<AgentConversationDetailMessageTool> | undefined;
  /**
   * AI model configuration recorded against a conversation or message.
   */
  modelInfo?: ConversationModelInfo | undefined;
  /**
   * Rich filter state selected by the user, used for display and persistence only.
   *
   * @remarks
   * This mirrors the active selection shown in the UI and is distinct from the
   * machine-readable `filters` field used for retrieval scoping.
   */
  appliedFilters?: AppliedFilters | undefined;
  metadata?: AgentConversationDetailMessageMetadata | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
};

/** @internal */
export const AgentConversationDetailMessageMessageType$inboundSchema:
  z.ZodMiniType<AgentConversationDetailMessageMessageType, unknown> = openEnums
    .inboundSchema(AgentConversationDetailMessageMessageType);

/** @internal */
export const AgentConversationDetailMessageContentFormat$inboundSchema:
  z.ZodMiniType<AgentConversationDetailMessageContentFormat, unknown> =
    openEnums.inboundSchema(AgentConversationDetailMessageContentFormat);

/** @internal */
export const Confidence$inboundSchema: z.ZodMiniType<Confidence, unknown> =
  openEnums.inboundSchema(Confidence);

/** @internal */
export const AgentConversationDetailMessageReferenceDatum$inboundSchema:
  z.ZodMiniType<AgentConversationDetailMessageReferenceDatum, unknown> = z
    .object({
      name: types.optional(types.string()),
      id: types.optional(types.string()),
      type: types.optional(types.string()),
      app: types.optional(types.string()),
      webUrl: types.optional(types.string()),
      metadata: types.optional(z.record(z.string(), types.string())),
    });

export function agentConversationDetailMessageReferenceDatumFromJSON(
  jsonString: string,
): SafeParseResult<
  AgentConversationDetailMessageReferenceDatum,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AgentConversationDetailMessageReferenceDatum$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AgentConversationDetailMessageReferenceDatum' from JSON`,
  );
}

/** @internal */
export const AgentConversationDetailMessageTool$inboundSchema: z.ZodMiniType<
  AgentConversationDetailMessageTool,
  unknown
> = z.object({
  toolName: types.optional(types.string()),
  toolResult: types.optional(z.any()),
});

export function agentConversationDetailMessageToolFromJSON(
  jsonString: string,
): SafeParseResult<AgentConversationDetailMessageTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AgentConversationDetailMessageTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentConversationDetailMessageTool' from JSON`,
  );
}

/** @internal */
export const AgentConversationDetailMessageMetadata$inboundSchema:
  z.ZodMiniType<AgentConversationDetailMessageMetadata, unknown> = z.object({
    processingTimeMs: types.optional(types.number()),
    modelVersion: types.optional(types.string()),
    aiTransactionId: types.optional(types.string()),
  });

export function agentConversationDetailMessageMetadataFromJSON(
  jsonString: string,
): SafeParseResult<AgentConversationDetailMessageMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AgentConversationDetailMessageMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentConversationDetailMessageMetadata' from JSON`,
  );
}

/** @internal */
export const AgentConversationDetailMessage$inboundSchema: z.ZodMiniType<
  AgentConversationDetailMessage,
  unknown
> = z.pipe(
  z.object({
    _id: types.optional(types.string()),
    messageType: types.optional(
      AgentConversationDetailMessageMessageType$inboundSchema,
    ),
    content: types.optional(types.string()),
    contentFormat: types.optional(
      AgentConversationDetailMessageContentFormat$inboundSchema,
    ),
    citations: types.optional(
      z.array(AgentConversationDetailMessageCitation$inboundSchema),
    ),
    confidence: z.optional(z.nullable(Confidence$inboundSchema)),
    followUpQuestions: types.optional(z.array(FollowUpQuestion$inboundSchema)),
    feedback: types.optional(z.array(MessageFeedback$inboundSchema)),
    referenceData: types.optional(z.array(z.lazy(() =>
      AgentConversationDetailMessageReferenceDatum$inboundSchema
    ))),
    attachments: types.optional(z.array(ChatAttachmentRef$inboundSchema)),
    tools: types.optional(z.array(z.lazy(() =>
      AgentConversationDetailMessageTool$inboundSchema
    ))),
    modelInfo: types.optional(ConversationModelInfo$inboundSchema),
    appliedFilters: types.optional(AppliedFilters$inboundSchema),
    metadata: types.optional(z.lazy(() =>
      AgentConversationDetailMessageMetadata$inboundSchema
    )),
    createdAt: types.optional(types.date()),
    updatedAt: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_id": "id",
    });
  }),
);

export function agentConversationDetailMessageFromJSON(
  jsonString: string,
): SafeParseResult<AgentConversationDetailMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentConversationDetailMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentConversationDetailMessage' from JSON`,
  );
}
