/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  StoredAgentConversation,
  StoredAgentConversation$inboundSchema,
} from "./stored-agent-conversation.js";

export const MessageEnum = {
  ConversationDeletedSuccessfully: "Conversation deleted successfully",
} as const;
export type MessageEnum = ClosedEnum<typeof MessageEnum>;

/**
 * Envelope returned by `DELETE /agents/{agentKey}/conversations/{conversationId}`.
 *
 * @remarks
 * When the conversation does not exist, belongs to a different agent, or
 * was already deleted, the API still returns HTTP 200 with
 * `conversation: null`.
 */
export type AgentConversationDeleteResponse = {
  message: MessageEnum;
  /**
   * Stored agent conversation document returned by non-list endpoints.
   *
   * @remarks
   */
  conversation: StoredAgentConversation;
};

/** @internal */
export const MessageEnum$inboundSchema: z.ZodMiniEnum<typeof MessageEnum> = z
  .enum(MessageEnum);

/** @internal */
export const AgentConversationDeleteResponse$inboundSchema: z.ZodMiniType<
  AgentConversationDeleteResponse,
  unknown
> = z.object({
  message: MessageEnum$inboundSchema,
  conversation: StoredAgentConversation$inboundSchema,
});

export function agentConversationDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<AgentConversationDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentConversationDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentConversationDeleteResponse' from JSON`,
  );
}
