/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Per-request agent capability toggles. Only meaningful when `chatMode`
 *
 * @remarks
 * selects an agent mode; ignored otherwise. Each field falls back to its
 * own `default` below when omitted — a missing flag is not uniformly
 * `true`. Omitting the whole object applies every default.
 */
export type AgentCapabilities = {
  /**
   * Whether the agent may search internal knowledge bases for this turn.
   */
  internalSearch?: boolean | undefined;
  /**
   * Whether the agent may perform web search for this turn.
   */
  webSearch?: boolean | undefined;
  /**
   * Whether the agent may use deeper, higher-latency retrieval for this turn.
   */
  deepSearch?: boolean | undefined;
};

/** @internal */
export type AgentCapabilities$Outbound = {
  internalSearch: boolean;
  webSearch: boolean;
  deepSearch: boolean;
};

/** @internal */
export const AgentCapabilities$outboundSchema: z.ZodMiniType<
  AgentCapabilities$Outbound,
  AgentCapabilities
> = z.object({
  internalSearch: z._default(z.boolean(), true),
  webSearch: z._default(z.boolean(), true),
  deepSearch: z._default(z.boolean(), false),
});

export function agentCapabilitiesToJSON(
  agentCapabilities: AgentCapabilities,
): string {
  return JSON.stringify(
    AgentCapabilities$outboundSchema.parse(agentCapabilities),
  );
}
