/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AgentCreateResponseKnowledge,
  AgentCreateResponseKnowledge$inboundSchema,
} from "./agent-create-response-knowledge.js";
import {
  AgentCreateResponseToolset,
  AgentCreateResponseToolset$inboundSchema,
} from "./agent-create-response-toolset.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type AgentCreateResponseAgentWebSearch = {
  provider?: string | undefined;
  providerKey?: string | undefined;
  providerLabel?: string | undefined;
};

export type AgentCreateResponseAgent = {
  key: string;
  name: string;
  description: string;
  startMessage: string;
  systemPrompt: string;
  instructions: string | null;
  models: Array<string>;
  tags: Array<string>;
  webSearch: AgentCreateResponseAgentWebSearch | null;
  isActive: boolean;
  isServiceAccount: boolean;
  createdBy: string;
  updatedBy: string | null;
  createdAtTimestamp: number;
  updatedAtTimestamp: number;
  isDeleted: boolean;
  toolsets: Array<AgentCreateResponseToolset>;
  knowledge: Array<AgentCreateResponseKnowledge>;
};

/** @internal */
export const AgentCreateResponseAgentWebSearch$inboundSchema: z.ZodMiniType<
  AgentCreateResponseAgentWebSearch,
  unknown
> = z.object({
  provider: types.optional(types.string()),
  providerKey: types.optional(types.string()),
  providerLabel: types.optional(types.string()),
});

export function agentCreateResponseAgentWebSearchFromJSON(
  jsonString: string,
): SafeParseResult<AgentCreateResponseAgentWebSearch, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentCreateResponseAgentWebSearch$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentCreateResponseAgentWebSearch' from JSON`,
  );
}

/** @internal */
export const AgentCreateResponseAgent$inboundSchema: z.ZodMiniType<
  AgentCreateResponseAgent,
  unknown
> = z.pipe(
  z.object({
    _key: types.string(),
    name: types.string(),
    description: types.string(),
    startMessage: types.string(),
    systemPrompt: types.string(),
    instructions: types.nullable(types.string()),
    models: z.array(types.string()),
    tags: z.array(types.string()),
    webSearch: types.nullable(
      z.lazy(() => AgentCreateResponseAgentWebSearch$inboundSchema),
    ),
    isActive: types.boolean(),
    isServiceAccount: types.boolean(),
    createdBy: types.string(),
    updatedBy: types.nullable(types.string()),
    createdAtTimestamp: types.number(),
    updatedAtTimestamp: types.number(),
    isDeleted: types.boolean(),
    toolsets: z.array(AgentCreateResponseToolset$inboundSchema),
    knowledge: z.array(AgentCreateResponseKnowledge$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_key": "key",
    });
  }),
);

export function agentCreateResponseAgentFromJSON(
  jsonString: string,
): SafeParseResult<AgentCreateResponseAgent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentCreateResponseAgent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentCreateResponseAgent' from JSON`,
  );
}
