/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type AgentCreateToolRef = {
  name: string;
  fullName?: string | undefined;
  description?: string | undefined;
};

/** @internal */
export type AgentCreateToolRef$Outbound = {
  name: string;
  fullName?: string | undefined;
  description?: string | undefined;
};

/** @internal */
export const AgentCreateToolRef$outboundSchema: z.ZodMiniType<
  AgentCreateToolRef$Outbound,
  AgentCreateToolRef
> = z.object({
  name: z.string(),
  fullName: z.optional(z.string()),
  description: z.optional(z.string()),
});

export function agentCreateToolRefToJSON(
  agentCreateToolRef: AgentCreateToolRef,
): string {
  return JSON.stringify(
    AgentCreateToolRef$outboundSchema.parse(agentCreateToolRef),
  );
}
