/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";
import {
  AppliedFilters,
  AppliedFilters$Outbound,
  AppliedFilters$outboundSchema,
} from "./applied-filters.js";
import {
  ChatAttachmentRef,
  ChatAttachmentRef$Outbound,
  ChatAttachmentRef$outboundSchema,
} from "./chat-attachment-ref.js";
import {
  Filters,
  Filters$Outbound,
  Filters$outboundSchema,
} from "./filters.js";

/**
 * Chat mode hint forwarded to the agent backend. Defaults to `auto`
 *
 * @remarks
 * in the upstream AI payload when omitted.
 * - `auto` lets the agent pick its default strategy.
 * - `quick` favors low-latency answers over depth.
 * - `verification` runs additional grounding/verification passes.
 * - `deep` performs deeper retrieval and reasoning.
 */
export const AgentAddMessageStreamRequestChatMode = {
  Auto: "auto",
  Quick: "quick",
  Verification: "verification",
  Deep: "deep",
} as const;
/**
 * Chat mode hint forwarded to the agent backend. Defaults to `auto`
 *
 * @remarks
 * in the upstream AI payload when omitted.
 * - `auto` lets the agent pick its default strategy.
 * - `quick` favors low-latency answers over depth.
 * - `verification` runs additional grounding/verification passes.
 * - `deep` performs deeper retrieval and reasoning.
 */
export type AgentAddMessageStreamRequestChatMode = ClosedEnum<
  typeof AgentAddMessageStreamRequestChatMode
>;

/**
 * Request body for `POST /agents/{agentKey}/conversations/{conversationId}/messages/stream`.
 *
 * @remarks
 * Only `query` is required; all other fields are optional overrides or
 * routing hints. Unknown fields are stripped during validation.
 */
export type AgentAddMessageStreamRequest = {
  /**
   * User follow-up prompt to append to the existing agent conversation.
   *
   * @remarks
   * Saved as a new `user_query` message before the upstream AI stream
   * starts.
   */
  query: string;
  /**
   * Optional retrieval scope (`apps` / `kb`) for this turn. Each id must
   *
   * @remarks
   * be a UUID or a `knowledgeBase_<orgId>` collection id. Omit to let
   * the agent use its stored defaults; send `{ "apps": [], "kb": [] }`
   * to force no knowledge sources for this turn.
   */
  filters?: Filters | undefined;
  /**
   * UI filter state persisted on the saved user message. Not used for
   *
   * @remarks
   * retrieval and not forwarded to the upstream agent backend.
   */
  appliedFilters?: AppliedFilters | undefined;
  /**
   * Uploaded attachments to ground this turn. Each entry references a
   *
   * @remarks
   * record id returned from the agent attachment upload endpoint.
   */
  attachments?: Array<ChatAttachmentRef> | undefined;
  /**
   * Chat mode hint forwarded to the agent backend. Defaults to `auto`
   *
   * @remarks
   * in the upstream AI payload when omitted.
   * - `auto` lets the agent pick its default strategy.
   * - `quick` favors low-latency answers over depth.
   * - `verification` runs additional grounding/verification passes.
   * - `deep` performs deeper retrieval and reasoning.
   */
  chatMode?: AgentAddMessageStreamRequestChatMode | undefined;
  /**
   * AI model configuration id override for this turn. Omit to use the
   *
   * @remarks
   * agent's default model.
   */
  modelKey?: string | undefined;
  /**
   * Provider model name (the underlying LLM identifier).
   */
  modelName?: string | undefined;
  /**
   * Friendly UI label for the selected model.
   */
  modelFriendlyName?: string | undefined;
  /**
   * Client IANA timezone, such as `America/New_York`. Helps the agent
   *
   * @remarks
   * resolve relative date references in the prompt.
   */
  timezone?: string | undefined;
  /**
   * Client time in ISO 8601 / RFC 3339 format (UTC `Z` or numeric
   *
   * @remarks
   * offset). Sent alongside `timezone` for time-aware answers.
   */
  currentTime?: Date | undefined;
  /**
   * Allowed tool ids for this turn, such as `jira.create_issue`. Omit
   *
   * @remarks
   * to let the agent use its default toolset; send `[]` to disable
   * tools for this turn.
   */
  tools?: Array<string> | undefined;
};

/** @internal */
export const AgentAddMessageStreamRequestChatMode$outboundSchema: z.ZodMiniEnum<
  typeof AgentAddMessageStreamRequestChatMode
> = z.enum(AgentAddMessageStreamRequestChatMode);

/** @internal */
export type AgentAddMessageStreamRequest$Outbound = {
  query: string;
  filters?: Filters$Outbound | undefined;
  appliedFilters?: AppliedFilters$Outbound | undefined;
  attachments?: Array<ChatAttachmentRef$Outbound> | undefined;
  chatMode?: string | undefined;
  modelKey?: string | undefined;
  modelName?: string | undefined;
  modelFriendlyName?: string | undefined;
  timezone?: string | undefined;
  currentTime?: string | undefined;
  tools?: Array<string> | undefined;
};

/** @internal */
export const AgentAddMessageStreamRequest$outboundSchema: z.ZodMiniType<
  AgentAddMessageStreamRequest$Outbound,
  AgentAddMessageStreamRequest
> = z.object({
  query: z.string(),
  filters: z.optional(Filters$outboundSchema),
  appliedFilters: z.optional(AppliedFilters$outboundSchema),
  attachments: z.optional(z.array(ChatAttachmentRef$outboundSchema)),
  chatMode: z.optional(AgentAddMessageStreamRequestChatMode$outboundSchema),
  modelKey: z.optional(z.string()),
  modelName: z.optional(z.string()),
  modelFriendlyName: z.optional(z.string()),
  timezone: z.optional(z.string()),
  currentTime: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  tools: z.optional(z.array(z.string())),
});

export function agentAddMessageStreamRequestToJSON(
  agentAddMessageStreamRequest: AgentAddMessageStreamRequest,
): string {
  return JSON.stringify(
    AgentAddMessageStreamRequest$outboundSchema.parse(
      agentAddMessageStreamRequest,
    ),
  );
}
