/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AgentConversationDetailAccess,
  AgentConversationDetailAccess$inboundSchema,
} from "./agent-conversation-detail-access.js";
import {
  AgentConversationDetailMessage,
  AgentConversationDetailMessage$inboundSchema,
} from "./agent-conversation-detail-message.js";
import {
  AgentConversationDetailPagination,
  AgentConversationDetailPagination$inboundSchema,
} from "./agent-conversation-detail-pagination.js";
import {
  ConversationModelInfo,
  ConversationModelInfo$inboundSchema,
} from "./conversation-model-info.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const AgentConversationDetailAccessLevel = {
  Read: "read",
  Write: "write",
} as const;
export type AgentConversationDetailAccessLevel = OpenEnum<
  typeof AgentConversationDetailAccessLevel
>;

export type AgentConversationDetailSharedWith = {
  userId?: string | undefined;
  accessLevel?: AgentConversationDetailAccessLevel | undefined;
};

export const AgentConversationDetailStatus = {
  None: "None",
  Inprogress: "Inprogress",
  Complete: "Complete",
  Failed: "Failed",
} as const;
export type AgentConversationDetailStatus = OpenEnum<
  typeof AgentConversationDetailStatus
>;

/**
 * Reduced conversation view returned by the by-id GET route. This is
 *
 * @remarks
 * not the raw `AgentConversation` document shape: fields like `agentKey`,
 * `userId`, `orgId`, `conversationSource`, and root-level `messages`
 * metadata outside the selected slice are omitted.
 */
export type AgentConversationDetail = {
  id: string;
  title?: string | undefined;
  initiator?: string | undefined;
  createdAt: Date;
  isShared: boolean;
  sharedWith: Array<AgentConversationDetailSharedWith>;
  status?: AgentConversationDetailStatus | undefined;
  failReason?: string | undefined;
  messages: Array<AgentConversationDetailMessage>;
  /**
   * AI model configuration recorded against a conversation or message.
   */
  modelInfo?: ConversationModelInfo | undefined;
  /**
   * Message pagination returned inside the `conversation` object. The
   *
   * @remarks
   * handler paginates backwards from the end of the stored message array,
   * then sorts the selected page in memory before serialization.
   */
  pagination: AgentConversationDetailPagination;
  access: AgentConversationDetailAccess;
};

/** @internal */
export const AgentConversationDetailAccessLevel$inboundSchema: z.ZodMiniType<
  AgentConversationDetailAccessLevel,
  unknown
> = openEnums.inboundSchema(AgentConversationDetailAccessLevel);

/** @internal */
export const AgentConversationDetailSharedWith$inboundSchema: z.ZodMiniType<
  AgentConversationDetailSharedWith,
  unknown
> = z.object({
  userId: types.optional(types.string()),
  accessLevel: types.optional(AgentConversationDetailAccessLevel$inboundSchema),
});

export function agentConversationDetailSharedWithFromJSON(
  jsonString: string,
): SafeParseResult<AgentConversationDetailSharedWith, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentConversationDetailSharedWith$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentConversationDetailSharedWith' from JSON`,
  );
}

/** @internal */
export const AgentConversationDetailStatus$inboundSchema: z.ZodMiniType<
  AgentConversationDetailStatus,
  unknown
> = openEnums.inboundSchema(AgentConversationDetailStatus);

/** @internal */
export const AgentConversationDetail$inboundSchema: z.ZodMiniType<
  AgentConversationDetail,
  unknown
> = z.object({
  id: types.string(),
  title: types.optional(types.string()),
  initiator: types.optional(types.string()),
  createdAt: types.date(),
  isShared: types.boolean(),
  sharedWith: z.array(
    z.lazy(() => AgentConversationDetailSharedWith$inboundSchema),
  ),
  status: types.optional(AgentConversationDetailStatus$inboundSchema),
  failReason: types.optional(types.string()),
  messages: z.array(AgentConversationDetailMessage$inboundSchema),
  modelInfo: types.optional(ConversationModelInfo$inboundSchema),
  pagination: AgentConversationDetailPagination$inboundSchema,
  access: AgentConversationDetailAccess$inboundSchema,
});

export function agentConversationDetailFromJSON(
  jsonString: string,
): SafeParseResult<AgentConversationDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentConversationDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentConversationDetail' from JSON`,
  );
}
