/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const AgentStreamSSEEventEvent = {
  RunStarted: "RUN_STARTED",
  RunFinished: "RUN_FINISHED",
  RunError: "RUN_ERROR",
  StepStarted: "STEP_STARTED",
  StepFinished: "STEP_FINISHED",
  TextMessageStart: "TEXT_MESSAGE_START",
  TextMessageContent: "TEXT_MESSAGE_CONTENT",
  TextMessageEnd: "TEXT_MESSAGE_END",
  ReasoningStart: "REASONING_START",
  ReasoningMessageStart: "REASONING_MESSAGE_START",
  ReasoningMessageContent: "REASONING_MESSAGE_CONTENT",
  ReasoningMessageEnd: "REASONING_MESSAGE_END",
  ReasoningEnd: "REASONING_END",
  ToolCallStart: "TOOL_CALL_START",
  ToolCallArgs: "TOOL_CALL_ARGS",
  ToolCallEnd: "TOOL_CALL_END",
  ToolCallResult: "TOOL_CALL_RESULT",
  StateDelta: "STATE_DELTA",
  StateSnapshot: "STATE_SNAPSHOT",
  Custom: "CUSTOM",
  Heartbeat: "HEARTBEAT",
} as const;
export type AgentStreamSSEEventEvent = OpenEnum<
  typeof AgentStreamSSEEventEvent
>;

/**
 * SSE event envelope for `POST /agents/{agentKey}/conversations/stream`.
 *
 * @remarks
 * AG-UI is the sole wire protocol.
 *
 * `event` carries the AG-UI type name and `data` is a JSON-encoded
 * object that includes a `"type"` field matching `event`, plus
 * type-specific fields. The public route requires `chatMode: quick`.
 * Forwarded lifecycle events may carry `runId`, `threadId`, and
 * `parentRunId`; gateway-generated root terminal events do not.
 *
 * Stable gateway-generated top-level outcomes are `RUN_FINISHED` as
 * `{ type, result }` and `RUN_ERROR` as `{ type, message, code? }`.
 * Clients should ignore unknown event names rather than treating them
 * as errors.
 */
export type AgentStreamSSEEvent = {
  event?: AgentStreamSSEEventEvent | undefined;
  /**
   * JSON-encoded event payload. The decoded JSON includes a `"type"`
   *
   * @remarks
   * field matching `event`, plus type-specific fields. Shape depends
   * on `event`.
   */
  data?: string | undefined;
};

/** @internal */
export const AgentStreamSSEEventEvent$inboundSchema: z.ZodMiniType<
  AgentStreamSSEEventEvent,
  unknown
> = openEnums.inboundSchema(AgentStreamSSEEventEvent);

/** @internal */
export const AgentStreamSSEEvent$inboundSchema: z.ZodMiniType<
  AgentStreamSSEEvent,
  unknown
> = z.object({
  event: types.optional(AgentStreamSSEEventEvent$inboundSchema),
  data: types.optional(types.string()),
});

export function agentStreamSSEEventFromJSON(
  jsonString: string,
): SafeParseResult<AgentStreamSSEEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentStreamSSEEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentStreamSSEEvent' from JSON`,
  );
}
