/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Archive counts and bounds for the current result page returned by
 *
 * @remarks
 * `GET /agents/{agentKey}/conversations/show/archives`.
 */
export type AgentArchivedConversationSummary = {
  /**
   * Total archived conversations matching the filter
   */
  totalArchived?: number | undefined;
  /**
   * Archive timestamp of the first item in the current page. Omitted when the page is empty.
   */
  oldestArchive?: Date | undefined;
  /**
   * Archive timestamp of the last item in the current page. Omitted when the page is empty.
   */
  newestArchive?: Date | undefined;
};

/** @internal */
export const AgentArchivedConversationSummary$inboundSchema: z.ZodMiniType<
  AgentArchivedConversationSummary,
  unknown
> = z.object({
  totalArchived: types.optional(types.number()),
  oldestArchive: types.optional(types.date()),
  newestArchive: types.optional(types.date()),
});

export function agentArchivedConversationSummaryFromJSON(
  jsonString: string,
): SafeParseResult<AgentArchivedConversationSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentArchivedConversationSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentArchivedConversationSummary' from JSON`,
  );
}
