/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  AgentCreateKnowledge,
  AgentCreateKnowledge$Outbound,
  AgentCreateKnowledge$outboundSchema,
} from "./agent-create-knowledge.js";
import {
  AgentCreateModelEntryUnion,
  AgentCreateModelEntryUnion$Outbound,
  AgentCreateModelEntryUnion$outboundSchema,
} from "./agent-create-model-entry-union.js";
import {
  AgentCreateToolset,
  AgentCreateToolset$Outbound,
  AgentCreateToolset$outboundSchema,
} from "./agent-create-toolset.js";
import {
  AgentCreateWebSearchUnion,
  AgentCreateWebSearchUnion$Outbound,
  AgentCreateWebSearchUnion$outboundSchema,
} from "./agent-create-web-search-union.js";

/**
 * Partial update payload for `PUT /agents/{agentKey}`.
 *
 * @remarks
 *
 * Every field is optional — only the fields present in the request body
 * are updated. When `models` is included, the gateway Zod middleware
 * (mirroring the Python backend) requires at least one model entry and
 * at least one object entry with `isReasoning: true`.
 */
export type AgentUpdateRequest = {
  /**
   * Agent display name
   */
  name?: string | undefined;
  /**
   * What the agent does
   */
  description?: string | undefined;
  /**
   * Initial greeting shown when conversation starts
   */
  startMessage?: string | undefined;
  /**
   * System instructions for the agent
   */
  systemPrompt?: string | undefined;
  /**
   * Additional agent execution instructions
   */
  instructions?: string | undefined;
  /**
   * Agent model configuration entries. When present, the Zod middleware
   *
   * @remarks
   * requires at least one object entry with `isReasoning: true`.
   * String-only arrays are schema-valid but rejected at runtime with HTTP 400.
   */
  models?: Array<AgentCreateModelEntryUnion> | undefined;
  tags?: Array<string> | undefined;
  /**
   * Share agent with the organization
   */
  shareWithOrg?: boolean | undefined;
  /**
   * Mark agent as a service account
   */
  isServiceAccount?: boolean | undefined;
  /**
   * Toolsets attached to the agent (instance-aware)
   */
  toolsets?: Array<AgentCreateToolset> | undefined;
  /**
   * Knowledge sources connected to the agent
   */
  knowledge?: Array<AgentCreateKnowledge> | undefined;
  /**
   * Accepted web-search attachment for `POST /agents/create`.
   *
   * @remarks
   * The gateway accepts either a provider string or an object with at least
   * a `provider` field.
   */
  webSearch?: AgentCreateWebSearchUnion | null | undefined;
};

/** @internal */
export type AgentUpdateRequest$Outbound = {
  name?: string | undefined;
  description?: string | undefined;
  startMessage?: string | undefined;
  systemPrompt?: string | undefined;
  instructions?: string | undefined;
  models?: Array<AgentCreateModelEntryUnion$Outbound> | undefined;
  tags?: Array<string> | undefined;
  shareWithOrg: boolean;
  isServiceAccount: boolean;
  toolsets?: Array<AgentCreateToolset$Outbound> | undefined;
  knowledge?: Array<AgentCreateKnowledge$Outbound> | undefined;
  webSearch?: AgentCreateWebSearchUnion$Outbound | null | undefined;
};

/** @internal */
export const AgentUpdateRequest$outboundSchema: z.ZodMiniType<
  AgentUpdateRequest$Outbound,
  AgentUpdateRequest
> = z.object({
  name: z.optional(z.string()),
  description: z.optional(z.string()),
  startMessage: z.optional(z.string()),
  systemPrompt: z.optional(z.string()),
  instructions: z.optional(z.string()),
  models: z.optional(z.array(AgentCreateModelEntryUnion$outboundSchema)),
  tags: z.optional(z.array(z.string())),
  shareWithOrg: z._default(z.boolean(), false),
  isServiceAccount: z._default(z.boolean(), false),
  toolsets: z.optional(z.array(AgentCreateToolset$outboundSchema)),
  knowledge: z.optional(z.array(AgentCreateKnowledge$outboundSchema)),
  webSearch: z.optional(z.nullable(AgentCreateWebSearchUnion$outboundSchema)),
});

export function agentUpdateRequestToJSON(
  agentUpdateRequest: AgentUpdateRequest,
): string {
  return JSON.stringify(
    AgentUpdateRequest$outboundSchema.parse(agentUpdateRequest),
  );
}
