/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  AgentConversationListItem,
  AgentConversationListItem$inboundSchema,
} from "./agent-conversation-list-item.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SemanticSearchHistoryPagination,
  SemanticSearchHistoryPagination$inboundSchema,
} from "./semantic-search-history-pagination.js";

/**
 * Archived conversations for a single agent, sliced to the first page
 *
 * @remarks
 * of the per-agent archive query (limit 5, sorted newest first).
 */
export type AgentArchivedConversationGroup = {
  /**
   * Agent identifier the conversations belong to.
   */
  agentKey: string;
  conversations: Array<AgentConversationListItem>;
  /**
   * Pagination block emitted by `buildPaginationMetadata` (utils.ts:417).
   *
   * @remarks
   * `totalPages` is `Math.ceil(totalCount / limit)`, so an empty result
   * has `totalPages: 0`, not `1`.
   */
  pagination: SemanticSearchHistoryPagination;
};

/** @internal */
export const AgentArchivedConversationGroup$inboundSchema: z.ZodMiniType<
  AgentArchivedConversationGroup,
  unknown
> = z.object({
  agentKey: types.string(),
  conversations: z.array(AgentConversationListItem$inboundSchema),
  pagination: SemanticSearchHistoryPagination$inboundSchema,
});

export function agentArchivedConversationGroupFromJSON(
  jsonString: string,
): SafeParseResult<AgentArchivedConversationGroup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentArchivedConversationGroup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentArchivedConversationGroup' from JSON`,
  );
}
