/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * A single filter node selected by the user (used for display/persistence of active filters)
 */
export type AppliedFilterNode = {
  /**
   * Unique identifier of the filter node
   */
  id?: string | undefined;
  /**
   * Display name of the filter node
   */
  name?: string | undefined;
  /**
   * Type of the node (e.g. app, kb)
   */
  nodeType?: string | undefined;
  /**
   * Connector identifier associated with this node
   */
  connector?: string | undefined;
};

/** @internal */
export const AppliedFilterNode$inboundSchema: z.ZodMiniType<
  AppliedFilterNode,
  unknown
> = z.object({
  id: types.optional(types.string()),
  name: types.optional(types.string()),
  nodeType: types.optional(types.string()),
  connector: types.optional(types.string()),
});
/** @internal */
export type AppliedFilterNode$Outbound = {
  id?: string | undefined;
  name?: string | undefined;
  nodeType?: string | undefined;
  connector?: string | undefined;
};

/** @internal */
export const AppliedFilterNode$outboundSchema: z.ZodMiniType<
  AppliedFilterNode$Outbound,
  AppliedFilterNode
> = z.object({
  id: z.optional(z.string()),
  name: z.optional(z.string()),
  nodeType: z.optional(z.string()),
  connector: z.optional(z.string()),
});

export function appliedFilterNodeToJSON(
  appliedFilterNode: AppliedFilterNode,
): string {
  return JSON.stringify(
    AppliedFilterNode$outboundSchema.parse(appliedFilterNode),
  );
}
export function appliedFilterNodeFromJSON(
  jsonString: string,
): SafeParseResult<AppliedFilterNode, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppliedFilterNode$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppliedFilterNode' from JSON`,
  );
}
