/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ApplicationJsonErrorResponseError = {
  /**
   * Machine-readable code (e.g. `HTTP_UNAUTHORIZED`, `HTTP_FORBIDDEN`).
   */
  code: string;
  message: string;
  /**
   * Optional; may appear in non-production for some errors.
   */
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const ApplicationJsonErrorResponseError$inboundSchema: z.ZodMiniType<
  ApplicationJsonErrorResponseError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  metadata: types.optional(z.record(z.string(), z.any())),
});

export function applicationJsonErrorResponseErrorFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationJsonErrorResponseError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationJsonErrorResponseError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationJsonErrorResponseError' from JSON`,
  );
}
