/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Public generic OAuth provider settings returned to clients
 */
export type AuthProviderOAuthPublicConfig = {
  /**
   * Custom OAuth provider display name
   */
  providerName: string;
  /**
   * OAuth client ID
   */
  clientId: string;
  /**
   * OAuth token endpoint URL
   */
  tokenEndpoint: string;
  /**
   * OAuth authorization URL
   */
  authorizationUrl: string;
  /**
   * Client secret (omitted when stripped for public responses)
   */
  clientSecret?: string | undefined;
  /**
   * UserInfo endpoint URL
   */
  userInfoEndpoint?: string | undefined;
  /**
   * Default OAuth scopes
   */
  scope?: string | undefined;
  /**
   * Whether just-in-time user provisioning is enabled for this provider
   */
  enableJit?: boolean | undefined;
};

/** @internal */
export const AuthProviderOAuthPublicConfig$inboundSchema: z.ZodMiniType<
  AuthProviderOAuthPublicConfig,
  unknown
> = z.object({
  providerName: types.string(),
  clientId: types.string(),
  tokenEndpoint: types.string(),
  authorizationUrl: types.string(),
  clientSecret: types.optional(types.string()),
  userInfoEndpoint: types.optional(types.string()),
  scope: types.optional(types.string()),
  enableJit: types.optional(types.boolean()),
});

export function authProviderOAuthPublicConfigFromJSON(
  jsonString: string,
): SafeParseResult<AuthProviderOAuthPublicConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthProviderOAuthPublicConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthProviderOAuthPublicConfig' from JSON`,
  );
}
