/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Type of authentication method:
 *
 * @remarks
 * - `password`: Email/password authentication
 * - `otp`: One-time password via email (6-digit, expires in 10 minutes)
 * - `google`: Google OAuth 2.0
 * - `microsoft`: Microsoft OAuth 2.0
 * - `azureAd`: Azure Active Directory
 * - `samlSso`: SAML 2.0 Single Sign-On
 * - `oauth`: Generic OAuth 2.0 provider
 */
export const Type = {
  SamlSso: "samlSso",
  Otp: "otp",
  Password: "password",
  Google: "google",
  Microsoft: "microsoft",
  AzureAd: "azureAd",
  Oauth: "oauth",
} as const;
/**
 * Type of authentication method:
 *
 * @remarks
 * - `password`: Email/password authentication
 * - `otp`: One-time password via email (6-digit, expires in 10 minutes)
 * - `google`: Google OAuth 2.0
 * - `microsoft`: Microsoft OAuth 2.0
 * - `azureAd`: Azure Active Directory
 * - `samlSso`: SAML 2.0 Single Sign-On
 * - `oauth`: Generic OAuth 2.0 provider
 */
export type Type = OpenEnum<typeof Type>;

/**
 * Authentication method configuration
 */
export type AuthMethod = {
  /**
   * Type of authentication method:
   *
   * @remarks
   * - `password`: Email/password authentication
   * - `otp`: One-time password via email (6-digit, expires in 10 minutes)
   * - `google`: Google OAuth 2.0
   * - `microsoft`: Microsoft OAuth 2.0
   * - `azureAd`: Azure Active Directory
   * - `samlSso`: SAML 2.0 Single Sign-On
   * - `oauth`: Generic OAuth 2.0 provider
   */
  type: Type;
};

/** @internal */
export const Type$inboundSchema: z.ZodMiniType<Type, unknown> = openEnums
  .inboundSchema(Type);
/** @internal */
export const Type$outboundSchema: z.ZodMiniType<string, Type> = openEnums
  .outboundSchema(Type);

/** @internal */
export const AuthMethod$inboundSchema: z.ZodMiniType<AuthMethod, unknown> = z
  .object({
    type: Type$inboundSchema,
  });
/** @internal */
export type AuthMethod$Outbound = {
  type: string;
};

/** @internal */
export const AuthMethod$outboundSchema: z.ZodMiniType<
  AuthMethod$Outbound,
  AuthMethod
> = z.object({
  type: Type$outboundSchema,
});

export function authMethodToJSON(authMethod: AuthMethod): string {
  return JSON.stringify(AuthMethod$outboundSchema.parse(authMethod));
}
export function authMethodFromJSON(
  jsonString: string,
): SafeParseResult<AuthMethod, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthMethod$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthMethod' from JSON`,
  );
}
