/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Concrete attachment metadata returned by `POST /conversations/attachments/upload`
 *
 * @remarks
 * (or the equivalent agent route).
 */
export type ChatAttachmentUploadRef = {
  /**
   * Server-assigned attachment record id.
   */
  recordId: string;
  /**
   * Original filename stored for the attachment.
   */
  recordName: string;
  /**
   * MIME type of the uploaded file.
   */
  mimeType: string;
  /**
   * File extension derived by the backend.
   */
  extension: string;
  /**
   * Synthetic record id used by the graph layer.
   */
  virtualRecordId: string;
  /**
   * Optional backend-reported processing mode for the attachment.
   */
  ocrMode?: string | undefined;
};

/** @internal */
export const ChatAttachmentUploadRef$inboundSchema: z.ZodMiniType<
  ChatAttachmentUploadRef,
  unknown
> = z.object({
  recordId: types.string(),
  recordName: types.string(),
  mimeType: types.string(),
  extension: types.string(),
  virtualRecordId: types.string(),
  ocrMode: types.optional(types.string()),
});

export function chatAttachmentUploadRefFromJSON(
  jsonString: string,
): SafeParseResult<ChatAttachmentUploadRef, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatAttachmentUploadRef$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatAttachmentUploadRef' from JSON`,
  );
}
