/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ConversationTitleUpdateRequest = {
  /**
   * New title for the conversation
   */
  title: string;
};

/** @internal */
export type ConversationTitleUpdateRequest$Outbound = {
  title: string;
};

/** @internal */
export const ConversationTitleUpdateRequest$outboundSchema: z.ZodMiniType<
  ConversationTitleUpdateRequest$Outbound,
  ConversationTitleUpdateRequest
> = z.object({
  title: z.string(),
});

export function conversationTitleUpdateRequestToJSON(
  conversationTitleUpdateRequest: ConversationTitleUpdateRequest,
): string {
  return JSON.stringify(
    ConversationTitleUpdateRequest$outboundSchema.parse(
      conversationTitleUpdateRequest,
    ),
  );
}
