/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ConversationListItemStatus = {
  None: "None",
  Inprogress: "Inprogress",
  Complete: "Complete",
  Failed: "Failed",
} as const;
export type ConversationListItemStatus = OpenEnum<
  typeof ConversationListItemStatus
>;

export type ModelInfo = {
  modelKey?: string | undefined;
  modelName?: string | undefined;
  modelFriendlyName?: string | undefined;
  modelProvider?: string | undefined;
  chatMode?: string | undefined;
};

export const SharedWithAccessLevel = {
  Read: "read",
  Write: "write",
} as const;
export type SharedWithAccessLevel = OpenEnum<typeof SharedWithAccessLevel>;

export type SharedWith = {
  userId?: string | undefined;
  accessLevel?: SharedWithAccessLevel | undefined;
};

export type ConversationError = {
  message?: string | undefined;
  errorType?: string | undefined;
  timestamp?: Date | undefined;
  messageId?: string | undefined;
  stack?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

export const ConversationListItemAccessLevel = {
  Read: "read",
  Write: "write",
} as const;
export type ConversationListItemAccessLevel = OpenEnum<
  typeof ConversationListItemAccessLevel
>;

/**
 * Conversation summary returned by list endpoints. Identical to
 *
 * @remarks
 * `Conversation` but omits `messages` to keep list payloads small.
 * Fetch a single conversation to retrieve its messages.
 */
export type ConversationListItem = {
  id?: string | undefined;
  userId?: string | undefined;
  orgId?: string | undefined;
  title?: string | undefined;
  initiator?: string | undefined;
  status?: ConversationListItemStatus | undefined;
  failReason?: string | undefined;
  modelInfo?: ModelInfo | undefined;
  isShared?: boolean | undefined;
  shareLink?: string | undefined;
  sharedWith?: Array<SharedWith> | undefined;
  isArchived?: boolean | undefined;
  /**
   * User ID of the last user who archived this row, or `null` after
   *
   * @remarks
   * unarchive cleared the archive state. Absent on rows that have
   * never been archived.
   */
  archivedBy?: string | null | undefined;
  isDeleted?: boolean | undefined;
  deletedBy?: string | undefined;
  conversationErrors?: Array<ConversationError> | undefined;
  metadata?: { [k: string]: any } | undefined;
  lastActivityAt?: number | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  isOwner?: boolean | undefined;
  accessLevel?: ConversationListItemAccessLevel | undefined;
};

/** @internal */
export const ConversationListItemStatus$inboundSchema: z.ZodMiniType<
  ConversationListItemStatus,
  unknown
> = openEnums.inboundSchema(ConversationListItemStatus);

/** @internal */
export const ModelInfo$inboundSchema: z.ZodMiniType<ModelInfo, unknown> = z
  .object({
    modelKey: types.optional(types.string()),
    modelName: types.optional(types.string()),
    modelFriendlyName: types.optional(types.string()),
    modelProvider: types.optional(types.string()),
    chatMode: types.optional(types.string()),
  });

export function modelInfoFromJSON(
  jsonString: string,
): SafeParseResult<ModelInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelInfo' from JSON`,
  );
}

/** @internal */
export const SharedWithAccessLevel$inboundSchema: z.ZodMiniType<
  SharedWithAccessLevel,
  unknown
> = openEnums.inboundSchema(SharedWithAccessLevel);

/** @internal */
export const SharedWith$inboundSchema: z.ZodMiniType<SharedWith, unknown> = z
  .object({
    userId: types.optional(types.string()),
    accessLevel: types.optional(SharedWithAccessLevel$inboundSchema),
  });

export function sharedWithFromJSON(
  jsonString: string,
): SafeParseResult<SharedWith, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SharedWith$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SharedWith' from JSON`,
  );
}

/** @internal */
export const ConversationError$inboundSchema: z.ZodMiniType<
  ConversationError,
  unknown
> = z.object({
  message: types.optional(types.string()),
  errorType: types.optional(types.string()),
  timestamp: types.optional(types.date()),
  messageId: types.optional(types.string()),
  stack: types.optional(types.string()),
  metadata: types.optional(z.record(z.string(), z.any())),
});

export function conversationErrorFromJSON(
  jsonString: string,
): SafeParseResult<ConversationError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversationError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversationError' from JSON`,
  );
}

/** @internal */
export const ConversationListItemAccessLevel$inboundSchema: z.ZodMiniType<
  ConversationListItemAccessLevel,
  unknown
> = openEnums.inboundSchema(ConversationListItemAccessLevel);

/** @internal */
export const ConversationListItem$inboundSchema: z.ZodMiniType<
  ConversationListItem,
  unknown
> = z.pipe(
  z.object({
    _id: types.optional(types.string()),
    userId: types.optional(types.string()),
    orgId: types.optional(types.string()),
    title: types.optional(types.string()),
    initiator: types.optional(types.string()),
    status: types.optional(ConversationListItemStatus$inboundSchema),
    failReason: types.optional(types.string()),
    modelInfo: types.optional(z.lazy(() => ModelInfo$inboundSchema)),
    isShared: types.optional(types.boolean()),
    shareLink: types.optional(types.string()),
    sharedWith: types.optional(z.array(z.lazy(() => SharedWith$inboundSchema))),
    isArchived: types.optional(types.boolean()),
    archivedBy: z.optional(z.nullable(types.string())),
    isDeleted: types.optional(types.boolean()),
    deletedBy: types.optional(types.string()),
    conversationErrors: types.optional(
      z.array(z.lazy(() => ConversationError$inboundSchema)),
    ),
    metadata: types.optional(z.record(z.string(), z.any())),
    lastActivityAt: types.optional(types.number()),
    createdAt: types.optional(types.date()),
    updatedAt: types.optional(types.date()),
    isOwner: types.optional(types.boolean()),
    accessLevel: types.optional(ConversationListItemAccessLevel$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_id": "id",
    });
  }),
);

export function conversationListItemFromJSON(
  jsonString: string,
): SafeParseResult<ConversationListItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversationListItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversationListItem' from JSON`,
  );
}
