/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ConversationSharedBy,
  ConversationSharedBy$inboundSchema,
} from "./conversation-shared-by.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Message, Message$inboundSchema } from "./message.js";

/**
 * Current status of the conversation:
 *
 * @remarks
 * - `None` — no activity yet
 * - `Inprogress` — AI is processing
 * - `Complete` — response ready
 * - `Failed` — error occurred
 * - `Stopped` — cancelled, or the client disconnected mid-answer;
 *   the last message keeps the partial answer
 */
export const ConversationStatus = {
  None: "None",
  Inprogress: "Inprogress",
  Complete: "Complete",
  Failed: "Failed",
  Stopped: "Stopped",
} as const;
/**
 * Current status of the conversation:
 *
 * @remarks
 * - `None` — no activity yet
 * - `Inprogress` — AI is processing
 * - `Complete` — response ready
 * - `Failed` — error occurred
 * - `Stopped` — cancelled, or the client disconnected mid-answer;
 *   the last message keeps the partial answer
 */
export type ConversationStatus = OpenEnum<typeof ConversationStatus>;

/**
 * AI model configuration used
 */
export type ConversationModelInfo1 = {
  modelKey?: string | undefined;
  modelName?: string | undefined;
  /**
   * Friendly display name of the selected model
   */
  modelFriendlyName?: string | undefined;
  modelProvider?: string | undefined;
  chatMode?: string | undefined;
};

export const ConversationSharedWithAccessLevel = {
  Read: "read",
  Write: "write",
} as const;
export type ConversationSharedWithAccessLevel = OpenEnum<
  typeof ConversationSharedWithAccessLevel
>;

export type ConversationSharedWith = {
  userId?: string | undefined;
  accessLevel?: ConversationSharedWithAccessLevel | undefined;
};

export type ConversationConversationError = {
  message: string;
  errorType?: string | undefined;
  timestamp?: Date | undefined;
  messageId?: string | undefined;
  stack?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/**
 * Computed per request. The requester's effective access level:
 *
 * @remarks
 * their entry in `sharedWith`, or `read` by default.
 */
export const ConversationAccessLevel = {
  Read: "read",
  Write: "write",
} as const;
/**
 * Computed per request. The requester's effective access level:
 *
 * @remarks
 * their entry in `sharedWith`, or `read` by default.
 */
export type ConversationAccessLevel = OpenEnum<typeof ConversationAccessLevel>;

/**
 * Only meaningful when `projectId` is set. `private` (default)
 *
 * @remarks
 * keeps the conversation visible to its owner only; `project`
 * exposes it to every member of the linked project. See
 * `PATCH /conversations/{conversationId}/project-visibility`.
 */
export const ConversationProjectVisibility = {
  Private: "private",
  Project: "project",
} as const;
/**
 * Only meaningful when `projectId` is set. `private` (default)
 *
 * @remarks
 * keeps the conversation visible to its owner only; `project`
 * exposes it to every member of the linked project. See
 * `PATCH /conversations/{conversationId}/project-visibility`.
 */
export type ConversationProjectVisibility = OpenEnum<
  typeof ConversationProjectVisibility
>;

/**
 * A conversation represents a chat session between a user and the AI.
 *
 * @remarks
 * Conversations maintain context across multiple messages and can be
 * shared, archived, and organized.
 */
export type Conversation = {
  /**
   * Unique conversation identifier
   */
  id?: string | undefined;
  /**
   * ID of the user who owns this conversation
   */
  userId?: string | undefined;
  /**
   * Organization this conversation belongs to
   */
  orgId?: string | undefined;
  /**
   * Conversation title, auto-generated from first query
   *
   * @remarks
   * or manually updated
   */
  title?: string | undefined;
  /**
   * User who started the conversation
   */
  initiator?: string | undefined;
  /**
   * All messages in this conversation
   */
  messages?: Array<Message> | undefined;
  /**
   * Current status of the conversation:
   *
   * @remarks
   * - `None` — no activity yet
   * - `Inprogress` — AI is processing
   * - `Complete` — response ready
   * - `Failed` — error occurred
   * - `Stopped` — cancelled, or the client disconnected mid-answer;
   *   the last message keeps the partial answer
   */
  status?: ConversationStatus | undefined;
  /**
   * Error description, populated only when `status` is `Failed`.
   */
  failReason?: string | undefined;
  /**
   * AI model configuration used
   */
  modelInfo?: ConversationModelInfo1 | undefined;
  /**
   * Whether this conversation is shared with others
   */
  isShared: boolean;
  /**
   * Shareable link if conversation is shared
   */
  shareLink?: string | undefined;
  /**
   * Users this conversation is shared with
   */
  sharedWith?: Array<ConversationSharedWith> | undefined;
  /**
   * Whether this conversation is archived
   */
  isArchived: boolean;
  /**
   * User ID of the last user who archived this row, or `null` after
   *
   * @remarks
   * unarchive cleared the archive state. Absent on rows that have
   * never been archived.
   */
  archivedBy?: string | null | undefined;
  /**
   * Whether this conversation has been soft-deleted.
   */
  isDeleted: boolean;
  /**
   * User who soft-deleted this conversation.
   */
  deletedBy?: string | undefined;
  /**
   * Errors recorded against this conversation (e.g. failed message generations).
   */
  conversationErrors?: Array<ConversationConversationError> | undefined;
  /**
   * Free-form metadata attached to the conversation.
   */
  metadata?: { [k: string]: any } | undefined;
  /**
   * Unix timestamp of last activity
   */
  lastActivityAt?: number | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  /**
   * Computed per request. `true` when the requesting user is the
   *
   * @remarks
   * conversation's `initiator`.
   */
  isOwner?: boolean | undefined;
  /**
   * Computed per request. The requester's effective access level:
   *
   * @remarks
   * their entry in `sharedWith`, or `read` by default.
   */
  accessLevel?: ConversationAccessLevel | undefined;
  /**
   * The project this conversation is linked to, if any. Set via
   *
   * @remarks
   * `PUT /conversations/{conversationId}/project` or at creation
   * time; absent on conversations that were never linked.
   */
  projectId?: string | null | undefined;
  /**
   * Only meaningful when `projectId` is set. `private` (default)
   *
   * @remarks
   * keeps the conversation visible to its owner only; `project`
   * exposes it to every member of the linked project. See
   * `PATCH /conversations/{conversationId}/project-visibility`.
   */
  projectVisibility?: ConversationProjectVisibility | null | undefined;
  /**
   * Present on conversations the caller received via share. Identifies the
   *
   * @remarks
   * conversation initiator (the only user who can share a chat).
   */
  sharedBy?: ConversationSharedBy | undefined;
};

/** @internal */
export const ConversationStatus$inboundSchema: z.ZodMiniType<
  ConversationStatus,
  unknown
> = openEnums.inboundSchema(ConversationStatus);

/** @internal */
export const ConversationModelInfo1$inboundSchema: z.ZodMiniType<
  ConversationModelInfo1,
  unknown
> = z.object({
  modelKey: types.optional(types.string()),
  modelName: types.optional(types.string()),
  modelFriendlyName: types.optional(types.string()),
  modelProvider: types.optional(types.string()),
  chatMode: types.optional(types.string()),
});

export function conversationModelInfo1FromJSON(
  jsonString: string,
): SafeParseResult<ConversationModelInfo1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversationModelInfo1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversationModelInfo1' from JSON`,
  );
}

/** @internal */
export const ConversationSharedWithAccessLevel$inboundSchema: z.ZodMiniType<
  ConversationSharedWithAccessLevel,
  unknown
> = openEnums.inboundSchema(ConversationSharedWithAccessLevel);

/** @internal */
export const ConversationSharedWith$inboundSchema: z.ZodMiniType<
  ConversationSharedWith,
  unknown
> = z.object({
  userId: types.optional(types.string()),
  accessLevel: types.optional(ConversationSharedWithAccessLevel$inboundSchema),
});

export function conversationSharedWithFromJSON(
  jsonString: string,
): SafeParseResult<ConversationSharedWith, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversationSharedWith$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversationSharedWith' from JSON`,
  );
}

/** @internal */
export const ConversationConversationError$inboundSchema: z.ZodMiniType<
  ConversationConversationError,
  unknown
> = z.object({
  message: types.string(),
  errorType: types.optional(types.string()),
  timestamp: types.optional(types.date()),
  messageId: types.optional(types.string()),
  stack: types.optional(types.string()),
  metadata: types.optional(z.record(z.string(), z.any())),
});

export function conversationConversationErrorFromJSON(
  jsonString: string,
): SafeParseResult<ConversationConversationError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversationConversationError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversationConversationError' from JSON`,
  );
}

/** @internal */
export const ConversationAccessLevel$inboundSchema: z.ZodMiniType<
  ConversationAccessLevel,
  unknown
> = openEnums.inboundSchema(ConversationAccessLevel);

/** @internal */
export const ConversationProjectVisibility$inboundSchema: z.ZodMiniType<
  ConversationProjectVisibility,
  unknown
> = openEnums.inboundSchema(ConversationProjectVisibility);

/** @internal */
export const Conversation$inboundSchema: z.ZodMiniType<Conversation, unknown> =
  z.pipe(
    z.object({
      _id: types.optional(types.string()),
      userId: types.optional(types.string()),
      orgId: types.optional(types.string()),
      title: types.optional(types.string()),
      initiator: types.optional(types.string()),
      messages: types.optional(z.array(Message$inboundSchema)),
      status: types.optional(ConversationStatus$inboundSchema),
      failReason: types.optional(types.string()),
      modelInfo: types.optional(
        z.lazy(() => ConversationModelInfo1$inboundSchema),
      ),
      isShared: z._default(types.boolean(), false),
      shareLink: types.optional(types.string()),
      sharedWith: types.optional(
        z.array(z.lazy(() => ConversationSharedWith$inboundSchema)),
      ),
      isArchived: z._default(types.boolean(), false),
      archivedBy: z.optional(z.nullable(types.string())),
      isDeleted: z._default(types.boolean(), false),
      deletedBy: types.optional(types.string()),
      conversationErrors: types.optional(
        z.array(z.lazy(() => ConversationConversationError$inboundSchema)),
      ),
      metadata: types.optional(z.record(z.string(), z.any())),
      lastActivityAt: types.optional(types.number()),
      createdAt: types.optional(types.date()),
      updatedAt: types.optional(types.date()),
      isOwner: types.optional(types.boolean()),
      accessLevel: types.optional(ConversationAccessLevel$inboundSchema),
      projectId: z.optional(z.nullable(types.string())),
      projectVisibility: z.optional(
        z.nullable(ConversationProjectVisibility$inboundSchema),
      ),
      sharedBy: types.optional(ConversationSharedBy$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        "_id": "id",
      });
    }),
  );

export function conversationFromJSON(
  jsonString: string,
): SafeParseResult<Conversation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Conversation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Conversation' from JSON`,
  );
}
