/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const CreateOAuthAppRequestAllowedGrantType = {
  AuthorizationCode: "authorization_code",
  ClientCredentials: "client_credentials",
  RefreshToken: "refresh_token",
} as const;
export type CreateOAuthAppRequestAllowedGrantType = ClosedEnum<
  typeof CreateOAuthAppRequestAllowedGrantType
>;

/**
 * Request to create a new OAuth app (`createAppSchema` in `oauth.validators.ts`).
 *
 * @remarks
 *
 * **Required:** `name`, `allowedScopes`. **Optional:** `description`, `redirectUris`, `allowedGrantTypes`,
 * `homepageUrl`, `privacyPolicyUrl`, `termsOfServiceUrl`, `isConfidential`, `accessTokenLifetime`, `refreshTokenLifetime`.
 *
 * **Redirect rule (Zod refine):** If the effective grant list includes `authorization_code`
 * (including when `allowedGrantTypes` is omitted — defaults to `authorization_code` + `refresh_token`),
 * at least one redirect URI is required. If grants exclude `authorization_code`, `redirectUris` may be omitted.
 */
export type CreateOAuthAppRequest = {
  /**
   * App name (displayed to users during authorization)
   */
  name: string;
  /**
   * App description
   */
  description?: string | undefined;
  /**
   * Allowed redirect URIs (max 10). Required when an effective grant list includes `authorization_code`
   *
   * @remarks
   * (including the default when `allowedGrantTypes` is omitted).
   */
  redirectUris?: Array<string> | undefined;
  /**
   * Allowed grant types. Defaults to `["authorization_code", "refresh_token"]` if omitted (applied by the service, not Zod).
   *
   * @remarks
   */
  allowedGrantTypes?: Array<CreateOAuthAppRequestAllowedGrantType> | undefined;
  /**
   * Scopes the app can request (non-empty)
   */
  allowedScopes: Array<string>;
  /**
   * App homepage URL (shown during authorization)
   */
  homepageUrl?: string | undefined;
  /**
   * Privacy policy URL
   */
  privacyPolicyUrl?: string | undefined;
  /**
   * Terms of service URL
   */
  termsOfServiceUrl?: string | undefined;
  /**
   * Whether the app can securely store secrets.
   *
   * @remarks
   * - `true`: Server-side app (secret required for token requests)
   * - `false`: Browser/mobile app (must use PKCE)
   */
  isConfidential?: boolean | undefined;
  /**
   * Access token lifetime in seconds (300–86400)
   */
  accessTokenLifetime?: number | undefined;
  /**
   * Refresh token lifetime in seconds (3600–31536000)
   */
  refreshTokenLifetime?: number | undefined;
};

/** @internal */
export const CreateOAuthAppRequestAllowedGrantType$outboundSchema:
  z.ZodMiniEnum<typeof CreateOAuthAppRequestAllowedGrantType> = z.enum(
    CreateOAuthAppRequestAllowedGrantType,
  );

/** @internal */
export type CreateOAuthAppRequest$Outbound = {
  name: string;
  description?: string | undefined;
  redirectUris?: Array<string> | undefined;
  allowedGrantTypes?: Array<string> | undefined;
  allowedScopes: Array<string>;
  homepageUrl?: string | undefined;
  privacyPolicyUrl?: string | undefined;
  termsOfServiceUrl?: string | undefined;
  isConfidential: boolean;
  accessTokenLifetime: number;
  refreshTokenLifetime: number;
};

/** @internal */
export const CreateOAuthAppRequest$outboundSchema: z.ZodMiniType<
  CreateOAuthAppRequest$Outbound,
  CreateOAuthAppRequest
> = z.object({
  name: z.string(),
  description: z.optional(z.string()),
  redirectUris: z.optional(z.array(z.string())),
  allowedGrantTypes: z.optional(
    z.array(CreateOAuthAppRequestAllowedGrantType$outboundSchema),
  ),
  allowedScopes: z.array(z.string()),
  homepageUrl: z.optional(z.string()),
  privacyPolicyUrl: z.optional(z.string()),
  termsOfServiceUrl: z.optional(z.string()),
  isConfidential: z._default(z.boolean(), true),
  accessTokenLifetime: z._default(z.int(), 3600),
  refreshTokenLifetime: z._default(z.int(), 2592000),
});

export function createOAuthAppRequestToJSON(
  createOAuthAppRequest: CreateOAuthAppRequest,
): string {
  return JSON.stringify(
    CreateOAuthAppRequest$outboundSchema.parse(createOAuthAppRequest),
  );
}
