/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  ProjectAppliedFilters,
  ProjectAppliedFilters$Outbound,
  ProjectAppliedFilters$outboundSchema,
} from "./project-applied-filters.js";
import {
  ProjectKnowledgeScope,
  ProjectKnowledgeScope$Outbound,
  ProjectKnowledgeScope$outboundSchema,
} from "./project-knowledge-scope.js";

export type CreateProjectRequest = {
  name: string;
  description?: string | undefined;
  icon?: string | undefined;
  color?: string | undefined;
  instructions?: string | undefined;
  /**
   * Retrieval scope (app connector / knowledge-base ids) inherited by
   *
   * @remarks
   * every conversation in the project when the request itself carries no
   * `filters`. Same id shapes as `Filters`.
   */
  knowledgeScope?: ProjectKnowledgeScope | undefined;
  /**
   * Display-friendly mirror of `knowledgeScope`, for rendering scope chips without a round trip.
   */
  appliedFilters?: ProjectAppliedFilters | undefined;
  tools?: Array<string> | undefined;
};

/** @internal */
export type CreateProjectRequest$Outbound = {
  name: string;
  description?: string | undefined;
  icon?: string | undefined;
  color?: string | undefined;
  instructions?: string | undefined;
  knowledgeScope?: ProjectKnowledgeScope$Outbound | undefined;
  appliedFilters?: ProjectAppliedFilters$Outbound | undefined;
  tools?: Array<string> | undefined;
};

/** @internal */
export const CreateProjectRequest$outboundSchema: z.ZodMiniType<
  CreateProjectRequest$Outbound,
  CreateProjectRequest
> = z.object({
  name: z.string(),
  description: z.optional(z.string()),
  icon: z.optional(z.string()),
  color: z.optional(z.string()),
  instructions: z.optional(z.string()),
  knowledgeScope: z.optional(ProjectKnowledgeScope$outboundSchema),
  appliedFilters: z.optional(ProjectAppliedFilters$outboundSchema),
  tools: z.optional(z.array(z.string())),
});

export function createProjectRequestToJSON(
  createProjectRequest: CreateProjectRequest,
): string {
  return JSON.stringify(
    CreateProjectRequest$outboundSchema.parse(createProjectRequest),
  );
}
