/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  OAuthAppWithSecret,
  OAuthAppWithSecret$inboundSchema,
} from "./o-auth-app-with-secret.js";

/**
 * Response body for `POST /oauth-clients` (`oauth.app.controller.ts` `createApp`).
 *
 * @remarks
 * The new app (including one-time `clientSecret`) is nested under `app`.
 */
export type CreateOAuthAppResponse = {
  message: string;
  app: OAuthAppWithSecret;
};

/** @internal */
export const CreateOAuthAppResponse$inboundSchema: z.ZodMiniType<
  CreateOAuthAppResponse,
  unknown
> = z.object({
  message: types.string(),
  app: OAuthAppWithSecret$inboundSchema,
});

export function createOAuthAppResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateOAuthAppResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateOAuthAppResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateOAuthAppResponse' from JSON`,
  );
}
