/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ErrorResponseError = {
  /**
   * Machine-readable error code. For application errors it takes the form `HTTP_<VARIANT>`
   *
   * @remarks
   * For unhandled runtime errors (e.g. database unavailable) it is `INTERNAL_ERROR`.
   */
  code: string;
  /**
   * Human-readable description of the error
   */
  message: string;
  /**
   * Additional context (only present in development environments)
   */
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const ErrorResponseError$inboundSchema: z.ZodMiniType<
  ErrorResponseError,
  unknown
> = z.object({
  code: types.string(),
  message: types.string(),
  metadata: types.optional(z.record(z.string(), z.any())),
});

export function errorResponseErrorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorResponseError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorResponseError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorResponseError' from JSON`,
  );
}
