/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * App connector instance ids and knowledge-base / record-group ids that narrow retrieval
 *
 * @remarks
 * for a turn. For **org assistant** chat streams, send explicit `apps` / `kb` lists.
 * For **agent** chat streams, send explicit id lists, or **omit** `filters` (and `tools`)
 * to let the service use the agent’s stored knowledge and tool configuration. Sending
 * `{ "apps": [], "kb": [] }` on an agent stream means **no** knowledge sources for that
 * turn (it is not “full org default”).
 */
export type Filters = {
  /**
   * Connector instance ids to scope retrieval for this turn. Each element
   *
   * @remarks
   * must be a valid UUID (connector app id, KB app id, record-group id, etc.).
   * Gateway validation matches Zod `appOrKbIdSchema`.
   */
  apps?: Array<string> | undefined;
  /**
   * Knowledge-base app ids to scope retrieval for this turn.
   *
   * @remarks
   * Each element must be a valid UUID.
   */
  kb?: Array<string> | undefined;
};

/** @internal */
export type Filters$Outbound = {
  apps?: Array<string> | undefined;
  kb?: Array<string> | undefined;
};

/** @internal */
export const Filters$outboundSchema: z.ZodMiniType<Filters$Outbound, Filters> =
  z.object({
    apps: z.optional(z.array(z.string())),
    kb: z.optional(z.array(z.string())),
  });

export function filtersToJSON(filters: Filters): string {
  return JSON.stringify(Filters$outboundSchema.parse(filters));
}
