/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * A single filter option for knowledge hub filters.
 */
export type FilterOption = {
  /**
   * Filter ID value to send in requests.
   */
  id: string;
  /**
   * Display label for the filter.
   */
  label: string;
  /**
   * Additional type information (currently unused, may be null).
   */
  type?: string | null | undefined;
  /**
   * Connector type/name. Set only for entries in the `connectors` list.
   */
  connectorType?: string | null | undefined;
};

/** @internal */
export const FilterOption$inboundSchema: z.ZodMiniType<FilterOption, unknown> =
  z.object({
    id: types.string(),
    label: types.string(),
    type: z.optional(z.nullable(types.string())),
    connectorType: z.optional(z.nullable(types.string())),
  });

export function filterOptionFromJSON(
  jsonString: string,
): SafeParseResult<FilterOption, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FilterOption$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FilterOption' from JSON`,
  );
}
