/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Response returned by PUT /knowledgeBase/{kbId}/folder/{folderId} (updateFolder).
 */
export type FolderUpdateResponseSchema = {
  success: boolean;
  message: string;
};

/** @internal */
export const FolderUpdateResponseSchema$inboundSchema: z.ZodMiniType<
  FolderUpdateResponseSchema,
  unknown
> = z.object({
  success: types.boolean(),
  message: types.string(),
});

export function folderUpdateResponseSchemaFromJSON(
  jsonString: string,
): SafeParseResult<FolderUpdateResponseSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FolderUpdateResponseSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FolderUpdateResponseSchema' from JSON`,
  );
}
