/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ConnectorNameEnum,
  ConnectorNameEnum$inboundSchema,
} from "./connector-name-enum.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  RecordTypeEnum,
  RecordTypeEnum$inboundSchema,
} from "./record-type-enum.js";

export type GetRecordByIdResponseSchemaFileRecord = {
  id: string;
  orgId: string;
  name: string;
  extension: string;
  mimeType: string;
  sizeInBytes: number;
  isFile: boolean;
  webUrl: string;
  path?: string | null | undefined;
  localFsRelativePath?: string | null | undefined;
};

export type GetRecordByIdResponseSchemaMailRecord = {};

export type TicketRecord = {};

export type GetRecordByIdResponseSchemaRecord = {
  id: string;
  orgId: string;
  recordName: string;
  externalRecordId: string;
  externalRootGroupId?: string | null | undefined;
  externalGroupId?: string | null | undefined;
  connectorId: string;
  /**
   * Name of the source connector. Mirrors the values of the backend
   *
   * @remarks
   * `Connectors` enum (`backend/python/app/config/constants/arangodb.py`);
   * records store the enum value (e.g. Google Drive is `DRIVE`,
   * SharePoint Online is `SHAREPOINT ONLINE`), not the enum member name.
   */
  connectorName: ConnectorNameEnum;
  /**
   * Type of content. Mirrors the backend `RecordType` enum
   *
   * @remarks
   * (`backend/python/app/models/entities.py`); connector-sourced records
   * may use any of the connector-specific types below.
   * - FILE: Uploaded or synced documents (PDF, DOCX, etc.)
   * - DRIVE: Drive/folder container (Google Drive, OneDrive, etc.)
   * - WEBPAGE: Web pages crawled or bookmarked
   * - DATABASE: Database object (e.g. Notion database)
   * - DATASOURCE: Data source object
   * - MESSAGE: Chat/messaging content (Slack, Teams)
   * - MAIL: Email messages (Gmail, Outlook)
   * - GROUP_MAIL: Group/shared mailbox email messages
   * - TICKET: Support/issue tickets (Jira, ServiceNow)
   * - COMMENT: Comments from collaboration tools
   * - INLINE_COMMENT: Inline comments anchored to content (e.g. Confluence)
   * - CONFLUENCE_PAGE: Confluence page
   * - CONFLUENCE_BLOGPOST: Confluence blog post
   * - SHAREPOINT_PAGE: SharePoint page
   * - SHAREPOINT_LIST: SharePoint list
   * - SHAREPOINT_LIST_ITEM: SharePoint list item
   * - SHAREPOINT_DOCUMENT_LIBRARY: SharePoint document library
   * - LINK: Web link / bookmark
   * - PROJECT: Project entity (e.g. Jira project)
   * - PULL_REQUEST: Source-control pull request
   * - MEETING: Meeting record (e.g. Zoom)
   * - PRODUCT: Product entity (CRM)
   * - DEAL: Deal/opportunity entity (CRM)
   * - CASE: Case entity (CRM/support)
   * - TASK: Task entity
   * - ARTIFACT: Generated/derived artifact
   * - CODE_FILE: Source-code file
   * - SQL_TABLE: SQL table object
   * - SQL_VIEW: SQL view object
   * - OTHERS: Miscellaneous content types
   */
  recordType: RecordTypeEnum;
  origin: string;
  version: number;
  isLatestVersion: boolean;
  createdAtTimestamp: number;
  updatedAtTimestamp: number;
  sourceCreatedAtTimestamp: number;
  sourceLastModifiedTimestamp: number;
  lastSyncTimestamp: number;
  lastIndexTimestamp?: number | undefined;
  lastExtractionTimestamp?: number | undefined;
  indexingStatus: string;
  extractionStatus: string;
  isDeleted: boolean;
  isArchived: boolean;
  isDirty: boolean;
  isVLMOcrProcessed: boolean;
  mimeType: string;
  sizeInBytes: number;
  md5Checksum?: string | undefined;
  virtualRecordId?: string | undefined;
  webUrl: string;
  fileRecord: GetRecordByIdResponseSchemaFileRecord | null;
  mailRecord: GetRecordByIdResponseSchemaMailRecord | null;
  ticketRecord: TicketRecord | null;
};

export type GetRecordByIdResponseSchemaKnowledgeBase = {
  id: string;
  name: string;
  orgId: string;
};

export type GetRecordByIdResponseSchemaFolder = {
  id: string;
  name: string;
};

export type Language = {
  id: string;
  name: string;
};

export type Topic = {
  id: string;
  name: string;
};

export type Subcategories1 = {
  id: string;
  name: string;
};

export type Subcategories2 = {
  id: string;
  name: string;
};

export type Subcategories3 = {
  id: string;
  name: string;
};

export type Department = {
  id: string;
  name: string;
};

export type GetRecordByIdResponseSchemaCategory = {
  id: string;
  name: string;
};

export type GetRecordByIdResponseSchemaMetadata = {
  languages: Array<Language>;
  topics: Array<Topic>;
  subcategories1: Array<Subcategories1>;
  subcategories2: Array<Subcategories2>;
  subcategories3: Array<Subcategories3>;
  departments: Array<Department>;
  categories: Array<GetRecordByIdResponseSchemaCategory>;
};

export const Relationship = {
  Owner: "OWNER",
  Writer: "WRITER",
  Reader: "READER",
} as const;
export type Relationship = OpenEnum<typeof Relationship>;

export type GetRecordByIdResponseSchemaPermission = {
  id: string;
  name: string;
  type: string;
  relationship: Relationship;
  accessType: string;
};

/**
 * Response returned by GET /knowledgeBase/record/{recordId}.
 */
export type GetRecordByIdResponseSchema = {
  record: GetRecordByIdResponseSchemaRecord;
  knowledgeBase: GetRecordByIdResponseSchemaKnowledgeBase | null;
  folder: GetRecordByIdResponseSchemaFolder | null;
  metadata: GetRecordByIdResponseSchemaMetadata;
  permissions: Array<GetRecordByIdResponseSchemaPermission>;
};

/** @internal */
export const GetRecordByIdResponseSchemaFileRecord$inboundSchema: z.ZodMiniType<
  GetRecordByIdResponseSchemaFileRecord,
  unknown
> = z.object({
  id: types.string(),
  orgId: types.string(),
  name: types.string(),
  extension: types.string(),
  mimeType: types.string(),
  sizeInBytes: types.number(),
  isFile: types.boolean(),
  webUrl: types.string(),
  path: z.optional(z.nullable(types.string())),
  localFsRelativePath: z.optional(z.nullable(types.string())),
});

export function getRecordByIdResponseSchemaFileRecordFromJSON(
  jsonString: string,
): SafeParseResult<GetRecordByIdResponseSchemaFileRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetRecordByIdResponseSchemaFileRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRecordByIdResponseSchemaFileRecord' from JSON`,
  );
}

/** @internal */
export const GetRecordByIdResponseSchemaMailRecord$inboundSchema: z.ZodMiniType<
  GetRecordByIdResponseSchemaMailRecord,
  unknown
> = z.object({});

export function getRecordByIdResponseSchemaMailRecordFromJSON(
  jsonString: string,
): SafeParseResult<GetRecordByIdResponseSchemaMailRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetRecordByIdResponseSchemaMailRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRecordByIdResponseSchemaMailRecord' from JSON`,
  );
}

/** @internal */
export const TicketRecord$inboundSchema: z.ZodMiniType<TicketRecord, unknown> =
  z.object({});

export function ticketRecordFromJSON(
  jsonString: string,
): SafeParseResult<TicketRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TicketRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TicketRecord' from JSON`,
  );
}

/** @internal */
export const GetRecordByIdResponseSchemaRecord$inboundSchema: z.ZodMiniType<
  GetRecordByIdResponseSchemaRecord,
  unknown
> = z.object({
  id: types.string(),
  orgId: types.string(),
  recordName: types.string(),
  externalRecordId: types.string(),
  externalRootGroupId: z.optional(z.nullable(types.string())),
  externalGroupId: z.optional(z.nullable(types.string())),
  connectorId: types.string(),
  connectorName: ConnectorNameEnum$inboundSchema,
  recordType: RecordTypeEnum$inboundSchema,
  origin: types.string(),
  version: types.number(),
  isLatestVersion: types.boolean(),
  createdAtTimestamp: types.number(),
  updatedAtTimestamp: types.number(),
  sourceCreatedAtTimestamp: types.number(),
  sourceLastModifiedTimestamp: types.number(),
  lastSyncTimestamp: types.number(),
  lastIndexTimestamp: types.optional(types.number()),
  lastExtractionTimestamp: types.optional(types.number()),
  indexingStatus: types.string(),
  extractionStatus: types.string(),
  isDeleted: types.boolean(),
  isArchived: types.boolean(),
  isDirty: types.boolean(),
  isVLMOcrProcessed: types.boolean(),
  mimeType: types.string(),
  sizeInBytes: types.number(),
  md5Checksum: types.optional(types.string()),
  virtualRecordId: types.optional(types.string()),
  webUrl: types.string(),
  fileRecord: types.nullable(
    z.lazy(() => GetRecordByIdResponseSchemaFileRecord$inboundSchema),
  ),
  mailRecord: types.nullable(
    z.lazy(() => GetRecordByIdResponseSchemaMailRecord$inboundSchema),
  ),
  ticketRecord: types.nullable(z.lazy(() => TicketRecord$inboundSchema)),
});

export function getRecordByIdResponseSchemaRecordFromJSON(
  jsonString: string,
): SafeParseResult<GetRecordByIdResponseSchemaRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRecordByIdResponseSchemaRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRecordByIdResponseSchemaRecord' from JSON`,
  );
}

/** @internal */
export const GetRecordByIdResponseSchemaKnowledgeBase$inboundSchema:
  z.ZodMiniType<GetRecordByIdResponseSchemaKnowledgeBase, unknown> = z.object({
    id: types.string(),
    name: types.string(),
    orgId: types.string(),
  });

export function getRecordByIdResponseSchemaKnowledgeBaseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetRecordByIdResponseSchemaKnowledgeBase,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetRecordByIdResponseSchemaKnowledgeBase$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetRecordByIdResponseSchemaKnowledgeBase' from JSON`,
  );
}

/** @internal */
export const GetRecordByIdResponseSchemaFolder$inboundSchema: z.ZodMiniType<
  GetRecordByIdResponseSchemaFolder,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
});

export function getRecordByIdResponseSchemaFolderFromJSON(
  jsonString: string,
): SafeParseResult<GetRecordByIdResponseSchemaFolder, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRecordByIdResponseSchemaFolder$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRecordByIdResponseSchemaFolder' from JSON`,
  );
}

/** @internal */
export const Language$inboundSchema: z.ZodMiniType<Language, unknown> = z
  .object({
    id: types.string(),
    name: types.string(),
  });

export function languageFromJSON(
  jsonString: string,
): SafeParseResult<Language, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Language$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Language' from JSON`,
  );
}

/** @internal */
export const Topic$inboundSchema: z.ZodMiniType<Topic, unknown> = z.object({
  id: types.string(),
  name: types.string(),
});

export function topicFromJSON(
  jsonString: string,
): SafeParseResult<Topic, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Topic$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Topic' from JSON`,
  );
}

/** @internal */
export const Subcategories1$inboundSchema: z.ZodMiniType<
  Subcategories1,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
});

export function subcategories1FromJSON(
  jsonString: string,
): SafeParseResult<Subcategories1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Subcategories1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Subcategories1' from JSON`,
  );
}

/** @internal */
export const Subcategories2$inboundSchema: z.ZodMiniType<
  Subcategories2,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
});

export function subcategories2FromJSON(
  jsonString: string,
): SafeParseResult<Subcategories2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Subcategories2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Subcategories2' from JSON`,
  );
}

/** @internal */
export const Subcategories3$inboundSchema: z.ZodMiniType<
  Subcategories3,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
});

export function subcategories3FromJSON(
  jsonString: string,
): SafeParseResult<Subcategories3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Subcategories3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Subcategories3' from JSON`,
  );
}

/** @internal */
export const Department$inboundSchema: z.ZodMiniType<Department, unknown> = z
  .object({
    id: types.string(),
    name: types.string(),
  });

export function departmentFromJSON(
  jsonString: string,
): SafeParseResult<Department, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Department$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Department' from JSON`,
  );
}

/** @internal */
export const GetRecordByIdResponseSchemaCategory$inboundSchema: z.ZodMiniType<
  GetRecordByIdResponseSchemaCategory,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
});

export function getRecordByIdResponseSchemaCategoryFromJSON(
  jsonString: string,
): SafeParseResult<GetRecordByIdResponseSchemaCategory, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetRecordByIdResponseSchemaCategory$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRecordByIdResponseSchemaCategory' from JSON`,
  );
}

/** @internal */
export const GetRecordByIdResponseSchemaMetadata$inboundSchema: z.ZodMiniType<
  GetRecordByIdResponseSchemaMetadata,
  unknown
> = z.object({
  languages: z.array(z.lazy(() => Language$inboundSchema)),
  topics: z.array(z.lazy(() => Topic$inboundSchema)),
  subcategories1: z.array(z.lazy(() => Subcategories1$inboundSchema)),
  subcategories2: z.array(z.lazy(() => Subcategories2$inboundSchema)),
  subcategories3: z.array(z.lazy(() => Subcategories3$inboundSchema)),
  departments: z.array(z.lazy(() => Department$inboundSchema)),
  categories: z.array(
    z.lazy(() => GetRecordByIdResponseSchemaCategory$inboundSchema),
  ),
});

export function getRecordByIdResponseSchemaMetadataFromJSON(
  jsonString: string,
): SafeParseResult<GetRecordByIdResponseSchemaMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetRecordByIdResponseSchemaMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRecordByIdResponseSchemaMetadata' from JSON`,
  );
}

/** @internal */
export const Relationship$inboundSchema: z.ZodMiniType<Relationship, unknown> =
  openEnums.inboundSchema(Relationship);

/** @internal */
export const GetRecordByIdResponseSchemaPermission$inboundSchema: z.ZodMiniType<
  GetRecordByIdResponseSchemaPermission,
  unknown
> = z.object({
  id: types.string(),
  name: types.string(),
  type: types.string(),
  relationship: Relationship$inboundSchema,
  accessType: types.string(),
});

export function getRecordByIdResponseSchemaPermissionFromJSON(
  jsonString: string,
): SafeParseResult<GetRecordByIdResponseSchemaPermission, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetRecordByIdResponseSchemaPermission$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRecordByIdResponseSchemaPermission' from JSON`,
  );
}

/** @internal */
export const GetRecordByIdResponseSchema$inboundSchema: z.ZodMiniType<
  GetRecordByIdResponseSchema,
  unknown
> = z.object({
  record: z.lazy(() => GetRecordByIdResponseSchemaRecord$inboundSchema),
  knowledgeBase: types.nullable(
    z.lazy(() => GetRecordByIdResponseSchemaKnowledgeBase$inboundSchema),
  ),
  folder: types.nullable(
    z.lazy(() => GetRecordByIdResponseSchemaFolder$inboundSchema),
  ),
  metadata: z.lazy(() => GetRecordByIdResponseSchemaMetadata$inboundSchema),
  permissions: z.array(
    z.lazy(() => GetRecordByIdResponseSchemaPermission$inboundSchema),
  ),
});

export function getRecordByIdResponseSchemaFromJSON(
  jsonString: string,
): SafeParseResult<GetRecordByIdResponseSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRecordByIdResponseSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRecordByIdResponseSchema' from JSON`,
  );
}
