/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const GetAllKnowledgeBaseResponseSchemaUserRole = {
  Owner: "OWNER",
  Writer: "WRITER",
  Reader: "READER",
} as const;
export type GetAllKnowledgeBaseResponseSchemaUserRole = OpenEnum<
  typeof GetAllKnowledgeBaseResponseSchemaUserRole
>;

export type GetAllKnowledgeBaseResponseSchemaFolder = {
  id: string;
  name: string;
  createdAtTimestamp?: number | undefined;
  path?: string | undefined;
};

export type GetAllKnowledgeBaseResponseSchemaKnowledgeBase = {
  id: string;
  name: string;
  connectorId: string | null;
  createdAtTimestamp: number;
  updatedAtTimestamp: number;
  createdBy: string;
  userRole: GetAllKnowledgeBaseResponseSchemaUserRole;
  folders: Array<GetAllKnowledgeBaseResponseSchemaFolder>;
};

export type GetAllKnowledgeBaseResponseSchemaPagination = {
  page: number;
  limit: number;
  totalCount: number;
  totalPages: number;
  hasNext: boolean;
  hasPrev: boolean;
};

export const AppliedPermission = {
  Owner: "OWNER",
  Writer: "WRITER",
  Reader: "READER",
} as const;
export type AppliedPermission = OpenEnum<typeof AppliedPermission>;

export const SortBy = {
  Name: "name",
  CreatedAtTimestamp: "createdAtTimestamp",
  UpdatedAtTimestamp: "updatedAtTimestamp",
  UserRole: "userRole",
} as const;
export type SortBy = OpenEnum<typeof SortBy>;

export const AppliedSortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type AppliedSortOrder = OpenEnum<typeof AppliedSortOrder>;

/**
 * Active filters. Empty `{}` when defaults. Keys use snake_case for sort
 *
 * @remarks
 * fields (backend convention in kb_service.py).
 */
export type GetAllKnowledgeBaseResponseSchemaApplied = {
  search?: string | undefined;
  permissions?: Array<AppliedPermission> | undefined;
  sortBy?: SortBy | undefined;
  sortOrder?: AppliedSortOrder | undefined;
};

export const AvailablePermission = {
  Owner: "OWNER",
  Writer: "WRITER",
  Reader: "READER",
} as const;
export type AvailablePermission = OpenEnum<typeof AvailablePermission>;

export const SortField = {
  Name: "name",
  CreatedAtTimestamp: "createdAtTimestamp",
  UpdatedAtTimestamp: "updatedAtTimestamp",
  UserRole: "userRole",
} as const;
export type SortField = OpenEnum<typeof SortField>;

export const AvailableSortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type AvailableSortOrder = OpenEnum<typeof AvailableSortOrder>;

export type GetAllKnowledgeBaseResponseSchemaAvailable = {
  permissions: Array<AvailablePermission>;
  sortFields: Array<SortField>;
  sortOrders: Array<AvailableSortOrder>;
};

export type GetAllKnowledgeBaseResponseSchemaFilters = {
  /**
   * Active filters. Empty `{}` when defaults. Keys use snake_case for sort
   *
   * @remarks
   * fields (backend convention in kb_service.py).
   */
  applied: GetAllKnowledgeBaseResponseSchemaApplied;
  available: GetAllKnowledgeBaseResponseSchemaAvailable;
};

/**
 * Response returned by GET /knowledgeBase (listKnowledgeBases).
 */
export type GetAllKnowledgeBaseResponseSchema = {
  knowledgeBases: Array<GetAllKnowledgeBaseResponseSchemaKnowledgeBase>;
  pagination: GetAllKnowledgeBaseResponseSchemaPagination;
  filters: GetAllKnowledgeBaseResponseSchemaFilters;
};

/** @internal */
export const GetAllKnowledgeBaseResponseSchemaUserRole$inboundSchema:
  z.ZodMiniType<GetAllKnowledgeBaseResponseSchemaUserRole, unknown> = openEnums
    .inboundSchema(GetAllKnowledgeBaseResponseSchemaUserRole);

/** @internal */
export const GetAllKnowledgeBaseResponseSchemaFolder$inboundSchema:
  z.ZodMiniType<GetAllKnowledgeBaseResponseSchemaFolder, unknown> = z.object({
    id: types.string(),
    name: types.string(),
    createdAtTimestamp: types.optional(types.number()),
    path: types.optional(types.string()),
  });

export function getAllKnowledgeBaseResponseSchemaFolderFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAllKnowledgeBaseResponseSchemaFolder,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllKnowledgeBaseResponseSchemaFolder$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAllKnowledgeBaseResponseSchemaFolder' from JSON`,
  );
}

/** @internal */
export const GetAllKnowledgeBaseResponseSchemaKnowledgeBase$inboundSchema:
  z.ZodMiniType<GetAllKnowledgeBaseResponseSchemaKnowledgeBase, unknown> = z
    .object({
      id: types.string(),
      name: types.string(),
      connectorId: types.nullable(types.string()),
      createdAtTimestamp: types.number(),
      updatedAtTimestamp: types.number(),
      createdBy: types.string(),
      userRole: GetAllKnowledgeBaseResponseSchemaUserRole$inboundSchema,
      folders: z.array(
        z.lazy(() => GetAllKnowledgeBaseResponseSchemaFolder$inboundSchema),
      ),
    });

export function getAllKnowledgeBaseResponseSchemaKnowledgeBaseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAllKnowledgeBaseResponseSchemaKnowledgeBase,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllKnowledgeBaseResponseSchemaKnowledgeBase$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAllKnowledgeBaseResponseSchemaKnowledgeBase' from JSON`,
  );
}

/** @internal */
export const GetAllKnowledgeBaseResponseSchemaPagination$inboundSchema:
  z.ZodMiniType<GetAllKnowledgeBaseResponseSchemaPagination, unknown> = z
    .object({
      page: types.number(),
      limit: types.number(),
      totalCount: types.number(),
      totalPages: types.number(),
      hasNext: types.boolean(),
      hasPrev: types.boolean(),
    });

export function getAllKnowledgeBaseResponseSchemaPaginationFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAllKnowledgeBaseResponseSchemaPagination,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllKnowledgeBaseResponseSchemaPagination$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAllKnowledgeBaseResponseSchemaPagination' from JSON`,
  );
}

/** @internal */
export const AppliedPermission$inboundSchema: z.ZodMiniType<
  AppliedPermission,
  unknown
> = openEnums.inboundSchema(AppliedPermission);

/** @internal */
export const SortBy$inboundSchema: z.ZodMiniType<SortBy, unknown> = openEnums
  .inboundSchema(SortBy);

/** @internal */
export const AppliedSortOrder$inboundSchema: z.ZodMiniType<
  AppliedSortOrder,
  unknown
> = openEnums.inboundSchema(AppliedSortOrder);

/** @internal */
export const GetAllKnowledgeBaseResponseSchemaApplied$inboundSchema:
  z.ZodMiniType<GetAllKnowledgeBaseResponseSchemaApplied, unknown> = z.pipe(
    z.object({
      search: types.optional(types.string()),
      permissions: types.optional(z.array(AppliedPermission$inboundSchema)),
      sort_by: types.optional(SortBy$inboundSchema),
      sort_order: types.optional(AppliedSortOrder$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        "sort_by": "sortBy",
        "sort_order": "sortOrder",
      });
    }),
  );

export function getAllKnowledgeBaseResponseSchemaAppliedFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAllKnowledgeBaseResponseSchemaApplied,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllKnowledgeBaseResponseSchemaApplied$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAllKnowledgeBaseResponseSchemaApplied' from JSON`,
  );
}

/** @internal */
export const AvailablePermission$inboundSchema: z.ZodMiniType<
  AvailablePermission,
  unknown
> = openEnums.inboundSchema(AvailablePermission);

/** @internal */
export const SortField$inboundSchema: z.ZodMiniType<SortField, unknown> =
  openEnums.inboundSchema(SortField);

/** @internal */
export const AvailableSortOrder$inboundSchema: z.ZodMiniType<
  AvailableSortOrder,
  unknown
> = openEnums.inboundSchema(AvailableSortOrder);

/** @internal */
export const GetAllKnowledgeBaseResponseSchemaAvailable$inboundSchema:
  z.ZodMiniType<GetAllKnowledgeBaseResponseSchemaAvailable, unknown> = z.object(
    {
      permissions: z.array(AvailablePermission$inboundSchema),
      sortFields: z.array(SortField$inboundSchema),
      sortOrders: z.array(AvailableSortOrder$inboundSchema),
    },
  );

export function getAllKnowledgeBaseResponseSchemaAvailableFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAllKnowledgeBaseResponseSchemaAvailable,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllKnowledgeBaseResponseSchemaAvailable$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAllKnowledgeBaseResponseSchemaAvailable' from JSON`,
  );
}

/** @internal */
export const GetAllKnowledgeBaseResponseSchemaFilters$inboundSchema:
  z.ZodMiniType<GetAllKnowledgeBaseResponseSchemaFilters, unknown> = z.object({
    applied: z.lazy(() =>
      GetAllKnowledgeBaseResponseSchemaApplied$inboundSchema
    ),
    available: z.lazy(() =>
      GetAllKnowledgeBaseResponseSchemaAvailable$inboundSchema
    ),
  });

export function getAllKnowledgeBaseResponseSchemaFiltersFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAllKnowledgeBaseResponseSchemaFilters,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAllKnowledgeBaseResponseSchemaFilters$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAllKnowledgeBaseResponseSchemaFilters' from JSON`,
  );
}

/** @internal */
export const GetAllKnowledgeBaseResponseSchema$inboundSchema: z.ZodMiniType<
  GetAllKnowledgeBaseResponseSchema,
  unknown
> = z.object({
  knowledgeBases: z.array(
    z.lazy(() => GetAllKnowledgeBaseResponseSchemaKnowledgeBase$inboundSchema),
  ),
  pagination: z.lazy(() =>
    GetAllKnowledgeBaseResponseSchemaPagination$inboundSchema
  ),
  filters: z.lazy(() => GetAllKnowledgeBaseResponseSchemaFilters$inboundSchema),
});

export function getAllKnowledgeBaseResponseSchemaFromJSON(
  jsonString: string,
): SafeParseResult<GetAllKnowledgeBaseResponseSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAllKnowledgeBaseResponseSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAllKnowledgeBaseResponseSchema' from JSON`,
  );
}
