/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Indexing status used to filter which records are included in a scoped
 *
 * @remarks
 * reindex (record or record-group). Omit `statusFilters` to reindex all
 * descendants regardless of status.
 */
export const IndexingStatusFilter = {
  NotStarted: "NOT_STARTED",
  Queued: "QUEUED",
  InProgress: "IN_PROGRESS",
  Completed: "COMPLETED",
  Failed: "FAILED",
  FileTypeNotSupported: "FILE_TYPE_NOT_SUPPORTED",
  AutoIndexOff: "AUTO_INDEX_OFF",
  Empty: "EMPTY",
} as const;
/**
 * Indexing status used to filter which records are included in a scoped
 *
 * @remarks
 * reindex (record or record-group). Omit `statusFilters` to reindex all
 * descendants regardless of status.
 */
export type IndexingStatusFilter = ClosedEnum<typeof IndexingStatusFilter>;

/** @internal */
export const IndexingStatusFilter$outboundSchema: z.ZodMiniEnum<
  typeof IndexingStatusFilter
> = z.enum(IndexingStatusFilter);
