/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Request body for PUT /knowledgeBase/{kbId}/record/{recordId}/move (moveRecord).
 */
export type KnowledgeBaseMoveRecordRequestBody = {
  /**
   * Target folder ID, or null to move the record to the knowledge base root
   */
  newParentId: string | null;
};

/** @internal */
export type KnowledgeBaseMoveRecordRequestBody$Outbound = {
  newParentId: string | null;
};

/** @internal */
export const KnowledgeBaseMoveRecordRequestBody$outboundSchema: z.ZodMiniType<
  KnowledgeBaseMoveRecordRequestBody$Outbound,
  KnowledgeBaseMoveRecordRequestBody
> = z.object({
  newParentId: z.nullable(z.string()),
});

export function knowledgeBaseMoveRecordRequestBodyToJSON(
  knowledgeBaseMoveRecordRequestBody: KnowledgeBaseMoveRecordRequestBody,
): string {
  return JSON.stringify(
    KnowledgeBaseMoveRecordRequestBody$outboundSchema.parse(
      knowledgeBaseMoveRecordRequestBody,
    ),
  );
}
