/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { PatListItem, PatListItem$inboundSchema } from "./pat-list-item.js";

/**
 * Response body for `GET /personal-access-tokens` (`listTokens`) — the
 *
 * @remarks
 * caller's own active tokens, capped at 100 most-recent server-side.
 * Unlike the admin list, this is a flat array with no pagination
 * envelope and no owner fields (it's implicitly scoped to the caller).
 */
export type ListPatResponse = {
  tokens: Array<PatListItem>;
};

/** @internal */
export const ListPatResponse$inboundSchema: z.ZodMiniType<
  ListPatResponse,
  unknown
> = z.object({
  tokens: z.array(PatListItem$inboundSchema),
});

export function listPatResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPatResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPatResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPatResponse' from JSON`,
  );
}
