/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const MessagePartType = {
  Text: "text",
  Reasoning: "reasoning",
  ToolCall: "tool_call",
  SubAgent: "sub_agent",
} as const;
export type MessagePartType = OpenEnum<typeof MessagePartType>;

export const MessagePartStatus = {
  Running: "running",
  Completed: "completed",
  Failed: "failed",
  Blocked: "blocked",
} as const;
export type MessagePartStatus = OpenEnum<typeof MessagePartStatus>;

/**
 * One entry in the ordered agent-activity transcript for a message turn.
 *
 * @remarks
 * Every field beyond `type` is optional and depends on the part kind, and
 * `sub_agent` nests this same shape recursively under `parts`.
 *
 * Tool results here are always a bounded preview, never the full payload —
 * `artifactId` points at the complete result.
 */
export type MessagePart = {
  type?: MessagePartType | undefined;
  content?: string | undefined;
  toolCallId?: string | undefined;
  toolName?: string | undefined;
  displayName?: string | undefined;
  args?: string | undefined;
  /**
   * Human-readable summary of `args`, computed server-side.
   */
  argsSummary?: string | undefined;
  status?: MessagePartStatus | undefined;
  resultPreview?: string | undefined;
  /**
   * Human-readable summary of the tool result, computed server-side from
   *
   * @remarks
   * the full untruncated output.
   */
  resultSummary?: string | undefined;
  /**
   * Blob-backed artifact id for the full tool result.
   */
  artifactId?: string | undefined;
  runId?: string | undefined;
  roleName?: string | undefined;
  /**
   * Set on the single root-level `text` part carrying the answer. Every
   *
   * @remarks
   * other root `text` part is an abandoned preamble turn. Never set on
   * child parts nested under a `sub_agent`.
   */
  isFinal?: boolean | undefined;
  /**
   * Nested transcript of a `sub_agent` part.
   */
  parts?: Array<MessagePart> | undefined;
};

/** @internal */
export const MessagePartType$inboundSchema: z.ZodMiniType<
  MessagePartType,
  unknown
> = openEnums.inboundSchema(MessagePartType);

/** @internal */
export const MessagePartStatus$inboundSchema: z.ZodMiniType<
  MessagePartStatus,
  unknown
> = openEnums.inboundSchema(MessagePartStatus);

/** @internal */
export const MessagePart$inboundSchema: z.ZodMiniType<MessagePart, unknown> = z
  .object({
    type: types.optional(MessagePartType$inboundSchema),
    content: types.optional(types.string()),
    toolCallId: types.optional(types.string()),
    toolName: types.optional(types.string()),
    displayName: types.optional(types.string()),
    args: types.optional(types.string()),
    argsSummary: types.optional(types.string()),
    status: types.optional(MessagePartStatus$inboundSchema),
    resultPreview: types.optional(types.string()),
    resultSummary: types.optional(types.string()),
    artifactId: types.optional(types.string()),
    runId: types.optional(types.string()),
    roleName: types.optional(types.string()),
    isFinal: types.optional(types.boolean()),
    parts: types.optional(z.array(z.lazy(() => MessagePart$inboundSchema))),
  });

export function messagePartFromJSON(
  jsonString: string,
): SafeParseResult<MessagePart, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessagePart$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessagePart' from JSON`,
  );
}
