/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  MessageFeedbackAppendMetrics,
  MessageFeedbackAppendMetrics$inboundSchema,
} from "./message-feedback-append-metrics.js";

export const MessageFeedbackAppendEntryCategory = {
  IncorrectInformation: "incorrect_information",
  MissingInformation: "missing_information",
  IrrelevantInformation: "irrelevant_information",
  UnclearExplanation: "unclear_explanation",
  PoorCitations: "poor_citations",
  ExcellentAnswer: "excellent_answer",
  HelpfulCitations: "helpful_citations",
  WellExplained: "well_explained",
  Other: "other",
} as const;
export type MessageFeedbackAppendEntryCategory = OpenEnum<
  typeof MessageFeedbackAppendEntryCategory
>;

/**
 * Echoed free-text comments from the request.
 */
export type MessageFeedbackAppendEntryComments = {
  positive?: string | undefined;
  negative?: string | undefined;
};

/**
 * The feedback entry just appended to the message. Echoes the fields
 *
 * @remarks
 * supplied in the request plus server-stamped `feedbackProvider`,
 * `timestamp`, and `metrics`.
 */
export type MessageFeedbackAppendEntry = {
  /**
   * Echoed from the request when supplied.
   */
  isHelpful?: boolean | undefined;
  /**
   * Echoed categories from the request.
   */
  categories?: Array<MessageFeedbackAppendEntryCategory> | undefined;
  /**
   * Echoed free-text comments from the request.
   */
  comments?: MessageFeedbackAppendEntryComments | undefined;
  /**
   * User who submitted the feedback. Always present.
   */
  feedbackProvider: string;
  /**
   * Submission time as epoch milliseconds (not an ISO 8601 datetime).
   *
   * @remarks
   * Always present.
   */
  timestamp: number;
  /**
   * Telemetry recorded server-side alongside the feedback. Always present
   *
   * @remarks
   * on append responses.
   */
  metrics: MessageFeedbackAppendMetrics;
};

/** @internal */
export const MessageFeedbackAppendEntryCategory$inboundSchema: z.ZodMiniType<
  MessageFeedbackAppendEntryCategory,
  unknown
> = openEnums.inboundSchema(MessageFeedbackAppendEntryCategory);

/** @internal */
export const MessageFeedbackAppendEntryComments$inboundSchema: z.ZodMiniType<
  MessageFeedbackAppendEntryComments,
  unknown
> = z.object({
  positive: types.optional(types.string()),
  negative: types.optional(types.string()),
});

export function messageFeedbackAppendEntryCommentsFromJSON(
  jsonString: string,
): SafeParseResult<MessageFeedbackAppendEntryComments, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MessageFeedbackAppendEntryComments$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageFeedbackAppendEntryComments' from JSON`,
  );
}

/** @internal */
export const MessageFeedbackAppendEntry$inboundSchema: z.ZodMiniType<
  MessageFeedbackAppendEntry,
  unknown
> = z.object({
  isHelpful: types.optional(types.boolean()),
  categories: types.optional(
    z.array(MessageFeedbackAppendEntryCategory$inboundSchema),
  ),
  comments: types.optional(
    z.lazy(() => MessageFeedbackAppendEntryComments$inboundSchema),
  ),
  feedbackProvider: types.string(),
  timestamp: types.number(),
  metrics: MessageFeedbackAppendMetrics$inboundSchema,
});

export function messageFeedbackAppendEntryFromJSON(
  jsonString: string,
): SafeParseResult<MessageFeedbackAppendEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageFeedbackAppendEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageFeedbackAppendEntry' from JSON`,
  );
}
