/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Ratings = {
  /**
   * How accurate was the information (1-5)
   */
  accuracy?: number | undefined;
  /**
   * How relevant was the response (1-5)
   */
  relevance?: number | undefined;
  /**
   * How complete was the answer (1-5)
   */
  completeness?: number | undefined;
  /**
   * How clear was the explanation (1-5)
   */
  clarity?: number | undefined;
};

export const Category = {
  IncorrectInformation: "incorrect_information",
  MissingInformation: "missing_information",
  IrrelevantInformation: "irrelevant_information",
  UnclearExplanation: "unclear_explanation",
  PoorCitations: "poor_citations",
  ExcellentAnswer: "excellent_answer",
  HelpfulCitations: "helpful_citations",
  WellExplained: "well_explained",
  Other: "other",
} as const;
export type Category = OpenEnum<typeof Category>;

export type Comments = {
  /**
   * What was good about the response
   */
  positive?: string | undefined;
  /**
   * What could be improved
   */
  negative?: string | undefined;
  /**
   * Specific suggestions for improvement
   */
  suggestions?: string | undefined;
};

export type CitationFeedback = {
  /**
   * Auto-generated sub-document identifier
   */
  id?: string | undefined;
  citationId?: string | undefined;
  isRelevant?: boolean | undefined;
  relevanceScore?: number | undefined;
  comment?: string | undefined;
};

/**
 * Origin of the feedback. Always present in responses (server applies the default `user`).
 */
export const Source = {
  User: "user",
  System: "system",
  Admin: "admin",
  Auto: "auto",
} as const;
/**
 * Origin of the feedback. Always present in responses (server applies the default `user`).
 */
export type Source = OpenEnum<typeof Source>;

export type Revision = {
  /**
   * Auto-generated sub-document identifier
   */
  id?: string | undefined;
  /**
   * Names of feedback fields modified in this revision
   */
  updatedFields?: Array<string> | undefined;
  /**
   * Map of previously-set values for the fields named in `updatedFields`,
   *
   * @remarks
   * keyed by field name. Stored as a Mongoose Map of Mixed values.
   */
  previousValues?: { [k: string]: any } | undefined;
  updatedBy?: string | undefined;
  /**
   * Time the revision was recorded, as epoch milliseconds.
   */
  updatedAt?: number | undefined;
};

/**
 * Optional telemetry captured alongside the feedback
 */
export type Metrics = {
  /**
   * Time from response delivery to feedback submission
   */
  timeToFeedback?: number | undefined;
  /**
   * Total time the user spent reviewing the response
   */
  userInteractionTime?: number | undefined;
  feedbackSessionId?: string | undefined;
  userAgent?: string | undefined;
  platform?: string | undefined;
};

/**
 * Comprehensive feedback on an AI response. Feedback helps improve
 *
 * @remarks
 * the AI's performance and response quality over time.
 */
export type MessageFeedback = {
  /**
   * Overall helpfulness rating
   */
  isHelpful?: boolean | undefined;
  ratings?: Ratings | undefined;
  /**
   * Categories of issues or positive attributes identified
   */
  categories?: Array<Category> | undefined;
  comments?: Comments | undefined;
  /**
   * Feedback on individual citations
   */
  citationFeedback?: Array<CitationFeedback> | undefined;
  /**
   * Were the suggested follow-up questions helpful
   */
  followUpQuestionsHelpful?: boolean | undefined;
  /**
   * Follow-up questions that were suggested but not used by the user
   */
  unusedFollowUpQuestions?: Array<string> | undefined;
  /**
   * Origin of the feedback. Always present in responses (server applies the default `user`).
   */
  source: Source;
  /**
   * User who submitted the feedback
   */
  feedbackProvider?: string | undefined;
  /**
   * Time the feedback was created, stored as a Number (epoch milliseconds)
   *
   * @remarks
   * with a server-side default of `Date.now`, so always present in responses.
   * Not an ISO 8601 datetime.
   */
  timestamp?: number | undefined;
  /**
   * Audit trail of edits to this feedback entry
   */
  revisions?: Array<Revision> | undefined;
  /**
   * Optional telemetry captured alongside the feedback
   */
  metrics?: Metrics | undefined;
};

/** @internal */
export const Ratings$inboundSchema: z.ZodMiniType<Ratings, unknown> = z.object({
  accuracy: types.optional(types.number()),
  relevance: types.optional(types.number()),
  completeness: types.optional(types.number()),
  clarity: types.optional(types.number()),
});

export function ratingsFromJSON(
  jsonString: string,
): SafeParseResult<Ratings, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ratings$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ratings' from JSON`,
  );
}

/** @internal */
export const Category$inboundSchema: z.ZodMiniType<Category, unknown> =
  openEnums.inboundSchema(Category);

/** @internal */
export const Comments$inboundSchema: z.ZodMiniType<Comments, unknown> = z
  .object({
    positive: types.optional(types.string()),
    negative: types.optional(types.string()),
    suggestions: types.optional(types.string()),
  });

export function commentsFromJSON(
  jsonString: string,
): SafeParseResult<Comments, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Comments$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Comments' from JSON`,
  );
}

/** @internal */
export const CitationFeedback$inboundSchema: z.ZodMiniType<
  CitationFeedback,
  unknown
> = z.pipe(
  z.object({
    _id: types.optional(types.string()),
    citationId: types.optional(types.string()),
    isRelevant: types.optional(types.boolean()),
    relevanceScore: types.optional(types.number()),
    comment: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_id": "id",
    });
  }),
);

export function citationFeedbackFromJSON(
  jsonString: string,
): SafeParseResult<CitationFeedback, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CitationFeedback$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CitationFeedback' from JSON`,
  );
}

/** @internal */
export const Source$inboundSchema: z.ZodMiniType<Source, unknown> = openEnums
  .inboundSchema(Source);

/** @internal */
export const Revision$inboundSchema: z.ZodMiniType<Revision, unknown> = z.pipe(
  z.object({
    _id: types.optional(types.string()),
    updatedFields: types.optional(z.array(types.string())),
    previousValues: types.optional(z.record(z.string(), z.any())),
    updatedBy: types.optional(types.string()),
    updatedAt: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_id": "id",
    });
  }),
);

export function revisionFromJSON(
  jsonString: string,
): SafeParseResult<Revision, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Revision$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Revision' from JSON`,
  );
}

/** @internal */
export const Metrics$inboundSchema: z.ZodMiniType<Metrics, unknown> = z.object({
  timeToFeedback: types.optional(types.number()),
  userInteractionTime: types.optional(types.number()),
  feedbackSessionId: types.optional(types.string()),
  userAgent: types.optional(types.string()),
  platform: types.optional(types.string()),
});

export function metricsFromJSON(
  jsonString: string,
): SafeParseResult<Metrics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Metrics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Metrics' from JSON`,
  );
}

/** @internal */
export const MessageFeedback$inboundSchema: z.ZodMiniType<
  MessageFeedback,
  unknown
> = z.object({
  isHelpful: types.optional(types.boolean()),
  ratings: types.optional(z.lazy(() => Ratings$inboundSchema)),
  categories: types.optional(z.array(Category$inboundSchema)),
  comments: types.optional(z.lazy(() => Comments$inboundSchema)),
  citationFeedback: types.optional(
    z.array(z.lazy(() => CitationFeedback$inboundSchema)),
  ),
  followUpQuestionsHelpful: types.optional(types.boolean()),
  unusedFollowUpQuestions: types.optional(z.array(types.string())),
  source: z._default(Source$inboundSchema, "user"),
  feedbackProvider: types.optional(types.string()),
  timestamp: types.optional(types.number()),
  revisions: types.optional(z.array(z.lazy(() => Revision$inboundSchema))),
  metrics: types.optional(z.lazy(() => Metrics$inboundSchema)),
});

export function messageFeedbackFromJSON(
  jsonString: string,
): SafeParseResult<MessageFeedback, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageFeedback$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageFeedback' from JSON`,
  );
}
