/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  KnowledgeGraphNodeRefSchema,
  KnowledgeGraphNodeRefSchema$inboundSchema,
} from "./knowledge-graph-node-ref-schema.js";
import {
  KnowledgeGraphNodeRowSchema,
  KnowledgeGraphNodeRowSchema$inboundSchema,
} from "./knowledge-graph-node-row-schema.js";

/**
 * The node that was opened. Null at the root listing.
 */
export type NavigateKnowledgeGraphResponseSchemaCurrent = {
  /**
   * Node identifier. Pass it back as `nodeId` to open this node. When `is_record` is true it is also the Record ID accepted by GET /connectors/record/{recordId}/content.
   */
  id: string;
  name: string;
  /**
   * One of `app`, `recordGroup`, `folder`, `record`.
   */
  nodeType: string;
  /**
   * e.g. `TICKET`, `CONFLUENCE_PAGE`, `PROJECT`, `COLLECTION`.
   */
  subType: string | null;
  /**
   * True for record and folder nodes — the nodes whose content can be read via GET /connectors/record/{recordId}/content.
   */
  isRecord: boolean;
};

/**
 * Pagination envelope for a navigate listing.
 */
export type NavigateKnowledgeGraphResponseSchemaPagination = {
  page: number;
  limit: number;
  /**
   * Total children of the current node, ignoring pagination.
   */
  total: number;
  hasNext: boolean;
  hasPrev: boolean;
};

/**
 * Response returned by GET /connectors/navigate.
 *
 * @remarks
 *
 * Field names are snake_case, matching the knowledge graph's internal
 * view models. `text` carries the same flat-text rendering PipesHub's
 * own agent sees for this node; the remaining fields carry the same
 * information in structured form.
 */
export type NavigateKnowledgeGraphResponseSchema = {
  /**
   * The node that was opened. Null at the root listing.
   */
  current: NavigateKnowledgeGraphResponseSchemaCurrent | null;
  /**
   * Root to parent, not including `current`.
   */
  breadcrumbs: Array<KnowledgeGraphNodeRefSchema>;
  /**
   * The current node's children for this page. With `depth` > 1 this is a flat list of all descendants up to that depth, each row carrying its own `level`.
   */
  rows: Array<KnowledgeGraphNodeRowSchema>;
  /**
   * Cross-referenced records (non-containment edges), e.g. the Confluence page linked from a Jira ticket. Page 1 only.
   */
  related: Array<KnowledgeGraphNodeRowSchema>;
  pagination: NavigateKnowledgeGraphResponseSchemaPagination | null;
  webUrl: string | null;
  indexingStatus: string | null;
  connector: string | null;
  /**
   * Type-specific metadata for the current node when it is a record — for a ticket, status, assignee, priority and dates.
   */
  contextBlock?: string | null | undefined;
  /**
   * Flat-text rendering of this view: breadcrumbs, the current node's
   *
   * @remarks
   * metadata, the children listing with an id per row, `Related:`, and
   * a closing `Next:` line naming a follow-up call.
   *
   * Shape depends on the page: pages after the first omit the header,
   * breadcrumbs and related rows to stay compact, while the structured
   * fields above remain complete. Capped at 25,000 bytes, with a
   * truncation marker appended when exceeded.
   */
  text: string;
};

/** @internal */
export const NavigateKnowledgeGraphResponseSchemaCurrent$inboundSchema:
  z.ZodMiniType<NavigateKnowledgeGraphResponseSchemaCurrent, unknown> = z.pipe(
    z.object({
      id: types.string(),
      name: types.string(),
      node_type: types.string(),
      sub_type: types.nullable(types.string()),
      is_record: types.boolean(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "node_type": "nodeType",
        "sub_type": "subType",
        "is_record": "isRecord",
      });
    }),
  );

export function navigateKnowledgeGraphResponseSchemaCurrentFromJSON(
  jsonString: string,
): SafeParseResult<
  NavigateKnowledgeGraphResponseSchemaCurrent,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      NavigateKnowledgeGraphResponseSchemaCurrent$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'NavigateKnowledgeGraphResponseSchemaCurrent' from JSON`,
  );
}

/** @internal */
export const NavigateKnowledgeGraphResponseSchemaPagination$inboundSchema:
  z.ZodMiniType<NavigateKnowledgeGraphResponseSchemaPagination, unknown> = z
    .pipe(
      z.object({
        page: types.number(),
        limit: types.number(),
        total: types.number(),
        has_next: types.boolean(),
        has_prev: types.boolean(),
      }),
      z.transform((v) => {
        return remap$(v, {
          "has_next": "hasNext",
          "has_prev": "hasPrev",
        });
      }),
    );

export function navigateKnowledgeGraphResponseSchemaPaginationFromJSON(
  jsonString: string,
): SafeParseResult<
  NavigateKnowledgeGraphResponseSchemaPagination,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      NavigateKnowledgeGraphResponseSchemaPagination$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'NavigateKnowledgeGraphResponseSchemaPagination' from JSON`,
  );
}

/** @internal */
export const NavigateKnowledgeGraphResponseSchema$inboundSchema: z.ZodMiniType<
  NavigateKnowledgeGraphResponseSchema,
  unknown
> = z.pipe(
  z.object({
    current: types.nullable(
      z.lazy(() => NavigateKnowledgeGraphResponseSchemaCurrent$inboundSchema),
    ),
    breadcrumbs: z.array(KnowledgeGraphNodeRefSchema$inboundSchema),
    rows: z.array(KnowledgeGraphNodeRowSchema$inboundSchema),
    related: z.array(KnowledgeGraphNodeRowSchema$inboundSchema),
    pagination: types.nullable(
      z.lazy(() =>
        NavigateKnowledgeGraphResponseSchemaPagination$inboundSchema
      ),
    ),
    web_url: types.nullable(types.string()),
    indexing_status: types.nullable(types.string()),
    connector: types.nullable(types.string()),
    context_block: z.optional(z.nullable(types.string())),
    text: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "web_url": "webUrl",
      "indexing_status": "indexingStatus",
      "context_block": "contextBlock",
    });
  }),
);

export function navigateKnowledgeGraphResponseSchemaFromJSON(
  jsonString: string,
): SafeParseResult<NavigateKnowledgeGraphResponseSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      NavigateKnowledgeGraphResponseSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NavigateKnowledgeGraphResponseSchema' from JSON`,
  );
}
