/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * OAuth Protected Resource Metadata (RFC 9728).
 *
 * @remarks
 * Describes the protected resource, its authorization servers, supported scopes, and bearer token methods.
 */
export type OAuthProtectedResourceMetadata = {
  /**
   * Protected resource identifier
   */
  resource: string;
  /**
   * Authorization servers that can issue tokens for this resource
   */
  authorizationServers: Array<string>;
  /**
   * OAuth scopes supported by this resource
   */
  scopesSupported?: Array<string> | undefined;
  /**
   * Methods supported for sending bearer tokens
   */
  bearerMethodsSupported?: Array<string> | undefined;
  /**
   * URL to human-readable documentation for the resource
   */
  resourceDocumentation?: string | undefined;
};

/** @internal */
export const OAuthProtectedResourceMetadata$inboundSchema: z.ZodMiniType<
  OAuthProtectedResourceMetadata,
  unknown
> = z.pipe(
  z.object({
    resource: types.string(),
    authorization_servers: z.array(types.string()),
    scopes_supported: types.optional(z.array(types.string())),
    bearer_methods_supported: types.optional(z.array(types.string())),
    resource_documentation: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "authorization_servers": "authorizationServers",
      "scopes_supported": "scopesSupported",
      "bearer_methods_supported": "bearerMethodsSupported",
      "resource_documentation": "resourceDocumentation",
    });
  }),
);

export function oAuthProtectedResourceMetadataFromJSON(
  jsonString: string,
): SafeParseResult<OAuthProtectedResourceMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OAuthProtectedResourceMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OAuthProtectedResourceMetadata' from JSON`,
  );
}
