/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const PersistedSemanticSearchSharedWithEntryAccessLevel = {
  Read: "read",
  Write: "write",
} as const;
export type PersistedSemanticSearchSharedWithEntryAccessLevel = OpenEnum<
  typeof PersistedSemanticSearchSharedWithEntryAccessLevel
>;

/**
 * Entry inside `sharedWith[]`. The schema sets `_id: false` on these
 *
 * @remarks
 * sub-docs, so no auto-injected `_id` is present.
 */
export type PersistedSemanticSearchSharedWithEntry = {
  userId: string;
  accessLevel: PersistedSemanticSearchSharedWithEntryAccessLevel;
};

/** @internal */
export const PersistedSemanticSearchSharedWithEntryAccessLevel$inboundSchema:
  z.ZodMiniType<PersistedSemanticSearchSharedWithEntryAccessLevel, unknown> =
    openEnums.inboundSchema(PersistedSemanticSearchSharedWithEntryAccessLevel);

/** @internal */
export const PersistedSemanticSearchSharedWithEntry$inboundSchema:
  z.ZodMiniType<PersistedSemanticSearchSharedWithEntry, unknown> = z.object({
    userId: types.string(),
    accessLevel:
      PersistedSemanticSearchSharedWithEntryAccessLevel$inboundSchema,
  });

export function persistedSemanticSearchSharedWithEntryFromJSON(
  jsonString: string,
): SafeParseResult<PersistedSemanticSearchSharedWithEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PersistedSemanticSearchSharedWithEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PersistedSemanticSearchSharedWithEntry' from JSON`,
  );
}
