/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Bounding box subdocument embedded in persisted citation metadata.
 *
 * @remarks
 * `boundingBoxSchema` does not set `_id: false`, so Mongoose auto-injects an `_id`.
 */
export type PersistedSemanticSearchBoundingBox = {
  id: string;
  x: number;
  y: number;
};

/** @internal */
export const PersistedSemanticSearchBoundingBox$inboundSchema: z.ZodMiniType<
  PersistedSemanticSearchBoundingBox,
  unknown
> = z.pipe(
  z.object({
    _id: types.string(),
    x: types.number(),
    y: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_id": "id",
    });
  }),
);

export function persistedSemanticSearchBoundingBoxFromJSON(
  jsonString: string,
): SafeParseResult<PersistedSemanticSearchBoundingBox, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PersistedSemanticSearchBoundingBox$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PersistedSemanticSearchBoundingBox' from JSON`,
  );
}
