/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  ProjectAppliedFilters,
  ProjectAppliedFilters$inboundSchema,
} from "./project-applied-filters.js";
import {
  ProjectKnowledgeScope,
  ProjectKnowledgeScope$inboundSchema,
} from "./project-knowledge-scope.js";
import {
  ProjectMember,
  ProjectMember$inboundSchema,
} from "./project-member.js";

/**
 * `org` makes the project (and, per `chatSharing`, its
 *
 * @remarks
 * `project`-visible conversations) readable by every member of the
 * organization, without adding them to `members[]`. Also grants
 * the organization's synthetic all-members team `READER` access
 * on the linked hidden Collection.
 */
export const ProjectVisibility = {
  Private: "private",
  Org: "org",
} as const;
/**
 * `org` makes the project (and, per `chatSharing`, its
 *
 * @remarks
 * `project`-visible conversations) readable by every member of the
 * organization, without adding them to `members[]`. Also grants
 * the organization's synthetic all-members team `READER` access
 * on the linked hidden Collection.
 */
export type ProjectVisibility = OpenEnum<typeof ProjectVisibility>;

/**
 * Owner-controlled default for new conversations created in this
 *
 * @remarks
 * project. `private` keeps new chats visible to their own owner
 * only; `members` exposes them to every project member
 * (`projectVisibility: project`). A conversation's own
 * `projectVisibility` can override this default per-chat.
 */
export const ProjectChatSharing = {
  Private: "private",
  Members: "members",
} as const;
/**
 * Owner-controlled default for new conversations created in this
 *
 * @remarks
 * project. `private` keeps new chats visible to their own owner
 * only; `members` exposes them to every project member
 * (`projectVisibility: project`). A conversation's own
 * `projectVisibility` can override this default per-chat.
 */
export type ProjectChatSharing = OpenEnum<typeof ProjectChatSharing>;

/**
 * A workspace that groups related assistant and agent conversations
 *
 * @remarks
 * under a shared name, instructions, knowledge scope, tool
 * selection, and its own hidden Collection of uploaded files. See
 * the `Projects` tag description for the sharing model.
 */
export type Project = {
  id?: string | undefined;
  orgId?: string | undefined;
  /**
   * Owner. Ownership never transfers.
   */
  userId?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  icon?: string | undefined;
  color?: string | undefined;
  /**
   * Injected into every conversation in this project as a dedicated,
   *
   * @remarks
   * author-attributed `project_instructions` prompt section — additive,
   * never overrides agent identity or system prompts.
   */
  instructions?: string | undefined;
  /**
   * Retrieval scope (app connector / knowledge-base ids) inherited by
   *
   * @remarks
   * every conversation in the project when the request itself carries no
   * `filters`. Same id shapes as `Filters`.
   */
  knowledgeScope?: ProjectKnowledgeScope | undefined;
  /**
   * Display-friendly mirror of `knowledgeScope`, for rendering scope chips without a round trip.
   */
  appliedFilters?: ProjectAppliedFilters | undefined;
  /**
   * Tool fullNames (toolset + MCP tools, same format as the
   *
   * @remarks
   * composer's `agentStreamTools`) this project's agent-mode chats
   * may use. Empty means no tools beyond the project's own files.
   */
  tools?: Array<string> | undefined;
  /**
   * Id of the hidden Collection holding this project's uploaded
   *
   * @remarks
   * files, created lazily on first upload via
   * `POST /projects/{projectId}/knowledge-base`. `null` until then.
   */
  linkedKnowledgeBaseId?: string | null | undefined;
  /**
   * `org` makes the project (and, per `chatSharing`, its
   *
   * @remarks
   * `project`-visible conversations) readable by every member of the
   * organization, without adding them to `members[]`. Also grants
   * the organization's synthetic all-members team `READER` access
   * on the linked hidden Collection.
   */
  visibility: ProjectVisibility;
  /**
   * Owner-controlled default for new conversations created in this
   *
   * @remarks
   * project. `private` keeps new chats visible to their own owner
   * only; `members` exposes them to every project member
   * (`projectVisibility: project`). A conversation's own
   * `projectVisibility` can override this default per-chat.
   */
  chatSharing: ProjectChatSharing;
  members?: Array<ProjectMember> | undefined;
  /**
   * Owner-scoped pin state in V1 (not per-viewer).
   */
  isPinned: boolean;
  isArchived: boolean;
  archivedBy?: string | null | undefined;
  isDeleted: boolean;
  deletedBy?: string | null | undefined;
  /**
   * Epoch milliseconds, bumped whenever a linked conversation streams a turn.
   */
  lastActivityAt?: number | undefined;
  metadata?: { [k: string]: any } | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
};

/** @internal */
export const ProjectVisibility$inboundSchema: z.ZodMiniType<
  ProjectVisibility,
  unknown
> = openEnums.inboundSchema(ProjectVisibility);

/** @internal */
export const ProjectChatSharing$inboundSchema: z.ZodMiniType<
  ProjectChatSharing,
  unknown
> = openEnums.inboundSchema(ProjectChatSharing);

/** @internal */
export const Project$inboundSchema: z.ZodMiniType<Project, unknown> = z.pipe(
  z.object({
    _id: types.optional(types.string()),
    orgId: types.optional(types.string()),
    userId: types.optional(types.string()),
    name: types.optional(types.string()),
    description: types.optional(types.string()),
    icon: types.optional(types.string()),
    color: types.optional(types.string()),
    instructions: types.optional(types.string()),
    knowledgeScope: types.optional(ProjectKnowledgeScope$inboundSchema),
    appliedFilters: types.optional(ProjectAppliedFilters$inboundSchema),
    tools: types.optional(z.array(types.string())),
    linkedKnowledgeBaseId: z.optional(z.nullable(types.string())),
    visibility: z._default(ProjectVisibility$inboundSchema, "private"),
    chatSharing: z._default(ProjectChatSharing$inboundSchema, "private"),
    members: types.optional(z.array(ProjectMember$inboundSchema)),
    isPinned: z._default(types.boolean(), false),
    isArchived: z._default(types.boolean(), false),
    archivedBy: z.optional(z.nullable(types.string())),
    isDeleted: z._default(types.boolean(), false),
    deletedBy: z.optional(z.nullable(types.string())),
    lastActivityAt: types.optional(types.number()),
    metadata: types.optional(z.record(z.string(), z.any())),
    createdAt: types.optional(types.date()),
    updatedAt: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_id": "id",
    });
  }),
);

export function projectFromJSON(
  jsonString: string,
): SafeParseResult<Project, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Project$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Project' from JSON`,
  );
}
