/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * User record returned with a refreshed access token
 */
export type RefreshTokenUser = {
  /**
   * User ID
   */
  id: string;
  /**
   * Organization ID
   */
  orgId: string;
  email: string;
  fullName: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  designation?: string | undefined;
  hasLoggedIn: boolean;
  isDeleted: boolean;
  slug: string;
  createdAt: string;
  updatedAt: string;
  v: number;
};

/** @internal */
export const RefreshTokenUser$inboundSchema: z.ZodMiniType<
  RefreshTokenUser,
  unknown
> = z.pipe(
  z.object({
    _id: types.string(),
    orgId: types.string(),
    email: types.string(),
    fullName: types.string(),
    firstName: types.optional(types.string()),
    lastName: types.optional(types.string()),
    designation: types.optional(types.string()),
    hasLoggedIn: types.boolean(),
    isDeleted: types.boolean(),
    slug: types.string(),
    createdAt: types.string(),
    updatedAt: types.string(),
    __v: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "_id": "id",
      "__v": "v",
    });
  }),
);

export function refreshTokenUserFromJSON(
  jsonString: string,
): SafeParseResult<RefreshTokenUser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RefreshTokenUser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RefreshTokenUser' from JSON`,
  );
}
