/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Optional request body for `DELETE /personal-access-tokens/{tokenId}`
 *
 * @remarks
 * and `DELETE /personal-access-tokens/admin/{tokenId}`. The body itself
 * is optional; `reason`, if present, is stored on the revocation for
 * auditing.
 */
export type RevokePatRequest = {
  reason?: string | undefined;
};

/** @internal */
export type RevokePatRequest$Outbound = {
  reason?: string | undefined;
};

/** @internal */
export const RevokePatRequest$outboundSchema: z.ZodMiniType<
  RevokePatRequest$Outbound,
  RevokePatRequest
> = z.object({
  reason: z.optional(z.string()),
});

export function revokePatRequestToJSON(
  revokePatRequest: RevokePatRequest,
): string {
  return JSON.stringify(
    RevokePatRequest$outboundSchema.parse(revokePatRequest),
  );
}
