/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  SemanticSearchHistoryFilters,
  SemanticSearchHistoryFilters$inboundSchema,
} from "./semantic-search-history-filters.js";
import {
  SemanticSearchHistoryItem,
  SemanticSearchHistoryItem$inboundSchema,
} from "./semantic-search-history-item.js";
import {
  SemanticSearchHistoryMeta,
  SemanticSearchHistoryMeta$inboundSchema,
} from "./semantic-search-history-meta.js";
import {
  SemanticSearchHistoryPagination,
  SemanticSearchHistoryPagination$inboundSchema,
} from "./semantic-search-history-pagination.js";

/**
 * Envelope returned by `GET /search`. The handler runs `find()` plus
 *
 * @remarks
 * `countDocuments()` in parallel and assembles `{ searchHistory,
 * pagination, filters, meta }` (es_controller.ts:3925-3973).
 */
export type SemanticSearchHistoryResponse = {
  searchHistory: Array<SemanticSearchHistoryItem>;
  /**
   * Pagination block emitted by `buildPaginationMetadata` (utils.ts:417).
   *
   * @remarks
   * `totalPages` is `Math.ceil(totalCount / limit)`, so an empty result
   * has `totalPages: 0`, not `1`.
   */
  pagination: SemanticSearchHistoryPagination;
  filters: SemanticSearchHistoryFilters;
  /**
   * `requestId` comes from `req.context?.requestId` and is omitted from
   *
   * @remarks
   * the JSON when upstream middleware did not set it.
   */
  meta: SemanticSearchHistoryMeta;
};

/** @internal */
export const SemanticSearchHistoryResponse$inboundSchema: z.ZodMiniType<
  SemanticSearchHistoryResponse,
  unknown
> = z.object({
  searchHistory: z.array(SemanticSearchHistoryItem$inboundSchema),
  pagination: SemanticSearchHistoryPagination$inboundSchema,
  filters: SemanticSearchHistoryFilters$inboundSchema,
  meta: SemanticSearchHistoryMeta$inboundSchema,
});

export function semanticSearchHistoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<SemanticSearchHistoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SemanticSearchHistoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SemanticSearchHistoryResponse' from JSON`,
  );
}
