/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Generic "filter X is available, current value is Y" block used for
 *
 * @remarks
 * `shared`, `tags`, `minMessages`, `search`, and `messageType`. Either
 * `type` (free-form value) or `values` (enum of allowed strings) is
 * present, not both. `current` is the caller-supplied value passed
 * through from `req.query`, hence string-or-null even when `type` is
 * `'number'`.
 */
export type SemanticSearchHistoryFilterToggle = {
  type?: string | undefined;
  values?: Array<string> | undefined;
  description: string;
  current: string | null;
  applied: boolean;
};

/** @internal */
export const SemanticSearchHistoryFilterToggle$inboundSchema: z.ZodMiniType<
  SemanticSearchHistoryFilterToggle,
  unknown
> = z.object({
  type: types.optional(types.string()),
  values: types.optional(z.array(types.string())),
  description: types.string(),
  current: types.nullable(types.string()),
  applied: types.boolean(),
});

export function semanticSearchHistoryFilterToggleFromJSON(
  jsonString: string,
): SafeParseResult<SemanticSearchHistoryFilterToggle, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SemanticSearchHistoryFilterToggle$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SemanticSearchHistoryFilterToggle' from JSON`,
  );
}
