/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const UpdateOAuthAppRequestAllowedGrantType = {
  AuthorizationCode: "authorization_code",
  ClientCredentials: "client_credentials",
  RefreshToken: "refresh_token",
} as const;
export type UpdateOAuthAppRequestAllowedGrantType = ClosedEnum<
  typeof UpdateOAuthAppRequestAllowedGrantType
>;

/**
 * Request to update an OAuth app (`updateAppSchema` in `oauth.validators.ts`).
 *
 * @remarks
 *
 * All fields are optional — include only fields that should change. URL fields (`homepageUrl`, `privacyPolicyUrl`, `termsOfServiceUrl`) accept `null` to clear them (nullable in Zod).
 *
 * **Redirect rule (Zod refine):** If `allowedGrantTypes` includes `authorization_code` and `redirectUris` is present in the body, `redirectUris` must contain at least one URI.
 */
export type UpdateOAuthAppRequest = {
  /**
   * App name
   */
  name?: string | undefined;
  /**
   * App description
   */
  description?: string | undefined;
  /**
   * Allowed redirect URIs (up to 10). Required when `authorization_code` grant type is enabled.
   *
   * @remarks
   * Preserved in the database even if `authorization_code` is removed from grant types.
   */
  redirectUris?: Array<string> | undefined;
  allowedGrantTypes?: Array<UpdateOAuthAppRequestAllowedGrantType> | undefined;
  allowedScopes?: Array<string> | undefined;
  homepageUrl?: string | null | undefined;
  privacyPolicyUrl?: string | null | undefined;
  termsOfServiceUrl?: string | null | undefined;
  accessTokenLifetime?: number | undefined;
  refreshTokenLifetime?: number | undefined;
};

/** @internal */
export const UpdateOAuthAppRequestAllowedGrantType$outboundSchema:
  z.ZodMiniEnum<typeof UpdateOAuthAppRequestAllowedGrantType> = z.enum(
    UpdateOAuthAppRequestAllowedGrantType,
  );

/** @internal */
export type UpdateOAuthAppRequest$Outbound = {
  name?: string | undefined;
  description?: string | undefined;
  redirectUris?: Array<string> | undefined;
  allowedGrantTypes?: Array<string> | undefined;
  allowedScopes?: Array<string> | undefined;
  homepageUrl?: string | null | undefined;
  privacyPolicyUrl?: string | null | undefined;
  termsOfServiceUrl?: string | null | undefined;
  accessTokenLifetime?: number | undefined;
  refreshTokenLifetime?: number | undefined;
};

/** @internal */
export const UpdateOAuthAppRequest$outboundSchema: z.ZodMiniType<
  UpdateOAuthAppRequest$Outbound,
  UpdateOAuthAppRequest
> = z.object({
  name: z.optional(z.string()),
  description: z.optional(z.string()),
  redirectUris: z.optional(z.array(z.string())),
  allowedGrantTypes: z.optional(
    z.array(UpdateOAuthAppRequestAllowedGrantType$outboundSchema),
  ),
  allowedScopes: z.optional(z.array(z.string())),
  homepageUrl: z.optional(z.nullable(z.string())),
  privacyPolicyUrl: z.optional(z.nullable(z.string())),
  termsOfServiceUrl: z.optional(z.nullable(z.string())),
  accessTokenLifetime: z.optional(z.int()),
  refreshTokenLifetime: z.optional(z.int()),
});

export function updateOAuthAppRequestToJSON(
  updateOAuthAppRequest: UpdateOAuthAppRequest,
): string {
  return JSON.stringify(
    UpdateOAuthAppRequest$outboundSchema.parse(updateOAuthAppRequest),
  );
}
